import { describe,it,expect } from 'vitest';
import { parseFlowMetricQuery,flowMetricView } from './metric-contract';
const id='11111111-1111-4111-8111-111111111111',from='2026-09-01T00:00:00Z',through='2026-10-01T00:00:00Z';
describe('Bounded flow cohorts preserve absent data and precise cursors',()=>{
 it('keeps the existing seven-day query and supports an explicit observation window',()=>{const value=parseFlowMetricQuery(new URLSearchParams(),Date.parse(through));expect(value.days).toBe(7);expect(value.through).toBe('2026-10-01T00:00:00.000Z');expect(parseFlowMetricQuery(new URLSearchParams({from,through}))).toMatchObject({from,through,days:null});});
 it.each(['days=NaN','days=0','days=91','days=1.5','days=7&days=30','actor_id=x','from='+from,'from='+from+'&through='+through+'&days=7','from='+through+'&through='+from])('rejects ambiguous or invalid windows %s',query=>{expect(()=>parseFlowMetricQuery(new URLSearchParams(query))).toThrow('invalid_flow_metrics');});
 it('preserves sub-millisecond cursor text rather than rounding it through Date',()=>{const cursor={id,started_at:'2026-09-15T12:00:00.123456Z'},raw=Buffer.from(JSON.stringify(cursor)).toString('base64url');expect(parseFlowMetricQuery(new URLSearchParams({from,through,cursor:raw})).cursor).toEqual(cursor);});
 it('rejects authority or malformed cursor content',()=>{for(const raw of [{id,started_at:from,actor_id:id},{id,started_at:'infinity'},null])expect(()=>parseFlowMetricQuery(new URLSearchParams({from,through,cursor:Buffer.from(JSON.stringify(raw)).toString('base64url')}))).toThrow('invalid_flow_metrics');});
 it('rejects silent counter truncation and duplicate evidence',()=>{const raw={flow_id:id,from_at:from,through_at:through,attribution:'recorded_execution',total_runs:1,node_entries:2,by_node:{start:2},by_status:{completed:1},evidence_filter:{node_key:null,status:null},matched_runs:1,records:[{id,conversation_id:id,status:'completed',started_at:'2026-09-15T12:00:00Z',ended_at:null}],next_cursor:null};expect(flowMetricView.safeParse(raw).success).toBe(true);for(const bad of [{...raw,node_entries:1001},{...raw,total_runs:2},{...raw,records:[...raw.records,...raw.records],matched_runs:2},{...raw,next_cursor:{id,started_at:from}},{...raw,secret:'NO'}])expect(flowMetricView.safeParse(bad).success).toBe(false);});
});
