import {beforeEach,describe,expect,it,vi} from 'vitest';
import {NextResponse} from 'next/server';
const ws='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',callId='33333333-3333-4333-8333-333333333333',id='44444444-4444-4444-8444-444444444444';
const f=vi.hoisted(()=>({enabled:true,locale:'es',user:{id:'22222222-2222-4222-8222-222222222222'} as {id:string}|null,auth:vi.fn(),resolve:vi.fn(),csrf:vi.fn(),limit:vi.fn(),read:vi.fn(),request:vi.fn(),join:vi.fn(),manage:vi.fn()}));
vi.mock('@/lib/ui/improvements-preview',()=>({get SHOW_RIVERZ_IMPROVEMENTS(){return f.enabled;}}));
vi.mock('@/lib/supabase/server',()=>({createClient:async()=>({auth:{getUser:f.auth}})}));
vi.mock('@/lib/channels/admin-client',()=>({supabaseAdmin:()=>({private:true})}));
vi.mock('@/lib/workspaces/resolve',()=>({resolveWorkspaceIdForUser:f.resolve}));
vi.mock('@/lib/csrf',()=>({csrfGuard:f.csrf}));vi.mock('@/lib/i18n/server',()=>({getLocale:async()=>f.locale}));
vi.mock('@/lib/rate-limit',()=>({limitByKey:f.limit,rateLimitResponse:()=>NextResponse.json({error:'limited'},{status:429})}));
vi.mock('@/lib/voice/human-handoff',async original=>({...await original<typeof import('@/lib/voice/human-handoff')>(),readHumanHandoff:f.read,requestHumanHandoff:f.request,createHumanHandoffGrant:f.join,manageHumanHandoff:f.manage}));
import {VoiceHandoffError} from '@/lib/voice/human-handoff';
import {GET,POST} from './route';
const post=(body:unknown={action:'request',input:{id,callId}},workspace=ws)=>new Request('https://riverz.co/api/voice/handoff',{method:'POST',headers:{'Content-Type':'application/json','x-workspace-id':workspace},body:JSON.stringify(body)});
const get=(query='callId='+callId,workspace=ws)=>new Request('https://riverz.co/api/voice/handoff?'+query,{headers:{'x-workspace-id':workspace}});
beforeEach(()=>{f.enabled=true;f.locale='es';f.user={id:actor};f.auth.mockReset().mockImplementation(async()=>({data:{user:f.user}}));f.resolve.mockReset().mockResolvedValue(ws);f.csrf.mockReset().mockResolvedValue(null);f.limit.mockReset().mockResolvedValue({success:true});for(const fn of [f.read,f.request,f.join,f.manage])fn.mockReset().mockResolvedValue({fixture:true});});
describe('Human takeover API is explicit, scoped and hidden',()=>{
 it('keeps the gate closed before auth, body or SDK access',async()=>{f.enabled=false;expect((await GET(get())).status).toBe(404);expect((await POST(post())).status).toBe(404);for(const fn of [f.auth,f.csrf,f.request,f.join])expect(fn).not.toHaveBeenCalled();});
 it('derives actor and workspace instead of accepting caller-supplied authority',async()=>{const response=await POST(post());expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toBe('private, no-store');expect(f.request).toHaveBeenCalledExactlyOnceWith({private:true},ws,actor,{id,callId});expect((await POST(post(undefined,id))).status).toBe(404);expect(f.request).toHaveBeenCalledTimes(1);});
 it('enforces CSRF on mutations before auth and authenticates reads',async()=>{f.csrf.mockResolvedValueOnce(NextResponse.json({error:'csrf'},{status:403}));expect((await POST(post())).status).toBe(403);expect(f.auth).not.toHaveBeenCalled();f.user=null;expect((await GET(get())).status).toBe(401);});
 it.each(['room','token','actorId','workspaceId','phone','phase'])('rejects caller-controlled %s',async key=>{expect((await POST(post({action:'join',input:{id,callId,[key]:'FORGED'}}))).status).toBe(400);expect(f.join).not.toHaveBeenCalled();});
 it.each(['callId='+callId+'&callId='+callId,'callId='+callId+'&room=other','callId=invalid',''])('rejects malformed/unrecognized read query %s',async query=>{expect((await GET(get(query))).status).toBe(400);expect(f.read).not.toHaveBeenCalled();});
 it('mints a token only on explicit join, not on request/read/renew/end',async()=>{
  await GET(get());await POST(post());await POST(post({action:'renew',input:{id,callId}}));await POST(post({action:'end',input:{id,callId}}));expect(f.join).not.toHaveBeenCalled();
  expect((await POST(post({action:'join',input:{id,callId}}))).status).toBe(200);expect(f.join).toHaveBeenCalledExactlyOnceWith({private:true},ws,actor,{id,callId});
 });
 it('bounds actual streamed body bytes and rate-limits before token creation',async()=>{const oversized=new Request('https://riverz.co/api/voice/handoff',{method:'POST',headers:{'Content-Type':'application/json','x-workspace-id':ws},body:'x'.repeat(2049)});expect((await POST(oversized)).status).toBe(400);expect(f.request).not.toHaveBeenCalled();f.limit.mockResolvedValue({success:false});const response=await POST(post({action:'join',input:{id,callId}}));expect(response.status).toBe(429);expect(response.headers.get('cache-control')).toBe('private, no-store');expect(f.join).not.toHaveBeenCalled();});
 it.each(['es','en'])('localizes errors and excludes secrets from %s responses',async locale=>{f.locale=locale;f.join.mockRejectedValue(new Error('PRIVATE_LIVEKIT_SECRET'));const response=await POST(post({action:'join',input:{id,callId}}));expect(response.status).toBe(503);expect(await response.text()).not.toMatch(/PRIVATE_LIVEKIT_SECRET|voice\.handoffError/);});
 it('maps changed/revoked authority without exposing internal diagnostics',async()=>{f.request.mockRejectedValue(new VoiceHandoffError('changed'));expect((await POST(post())).status).toBe(409);f.request.mockRejectedValue(new VoiceHandoffError('notFound'));expect((await POST(post())).status).toBe(404);});
});
