import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { beforeEach, afterEach, describe, it, expect, vi } from 'vitest';
import { translate } from '@/lib/i18n/translate';
const h=vi.hoisted(()=>({enabled:true,locale:'es' as 'es'|'en',index:0,bank:[] as unknown[],fetch:vi.fn(),csrf:vi.fn()}));
vi.mock('@/lib/ui/improvements-preview',()=>({get SHOW_RIVERZ_IMPROVEMENTS(){return h.enabled;}}));vi.mock('@/hooks/use-locale',()=>({useLocale:()=>({t:(key:string,args?:Record<string,string>)=>translate(h.locale,key,args)})}));vi.mock('@/hooks/use-format',()=>({useFormat:()=>({number:String,dateTime:String})}));vi.mock('@/lib/api/fetch-with-csrf',()=>({useFetchWithCsrf:()=>h.csrf}));
vi.mock('react',async()=>({...await vi.importActual<typeof import('react')>('react'),useState:(initial:unknown)=>{const i=h.index++;if(!(i in h.bank))h.bank[i]=initial;return[h.bank[i],(next:unknown)=>{h.bank[i]=typeof next==='function'?next(h.bank[i]):next;}];},useRef:(initial:unknown)=>{const i=h.index++;if(!(i in h.bank))h.bank[i]={current:initial};return h.bank[i];},useEffect:vi.fn()}));
import { RuleReview } from './rule-review';
const conv='11111111-1111-4111-8111-111111111111',turn='22222222-2222-4222-8222-222222222222',rule='33333333-3333-4333-8333-333333333333',actor='44444444-4444-4444-8444-444444444444';
const view={turn_id:turn,rule_id:rule,rule_revision:1,rule:{titulo:'Synthetic rule',cuando:null,hacer:'Historical instruction'},review:null,history:[],history_truncated:false,can_edit:true,attribution:'team_assessment'};
type Element=React.ReactElement<Record<string,unknown>>;
function nodes(node:React.ReactNode):Element[]{if(Array.isArray(node))return node.flatMap(nodes);if(!React.isValidElement(node))return[];const item=node as Element;return[item,...nodes(item.props.children as React.ReactNode)];}
function render(){h.index=0;return RuleReview({conversationId:conv,turnId:turn,ruleId:rule});}
function find(type:string,index=0){const value=nodes(render()).filter(item=>item.type===type)[index];if(!value)throw new Error('Missing '+type);return value;}
async function open(){const target={open:true};(find('details').props.onToggle as(event:unknown)=>void)({currentTarget:target,target});await vi.waitFor(()=>expect(h.bank[0]).not.toBeNull());}
beforeEach(()=>{vi.clearAllMocks();h.enabled=true;h.locale='es';h.bank=[];h.fetch.mockImplementation(async()=>new Response(JSON.stringify(view)));h.csrf.mockImplementation(async(_url:string,init:RequestInit)=>{const body=JSON.parse(String(init.body));return new Response(JSON.stringify({id:body.id,turn_id:turn,rule_id:rule,attribution:'team_assessment',review:{revision:1,...body.decision,confirmed:undefined,actor_id:actor,actor_name:'Synthetic',changed_at:'2026-10-01T12:00:00Z'}}));});vi.stubGlobal('fetch',h.fetch);});
afterEach(()=>vi.unstubAllGlobals());
describe('Human assessment stays optional, explicit and deterministic',()=>{
 it.each(['es','en'] as const)('stays hidden outside comparison in %s',locale=>{h.locale=locale;h.enabled=false;expect(renderToStaticMarkup(render())).toBe('');expect(h.fetch).not.toHaveBeenCalled();});
 it.each(['es','en'] as const)('loads lazily and renders historical configuration in %s',async locale=>{h.locale=locale;render();expect(h.fetch).not.toHaveBeenCalled();await open();const html=renderToStaticMarkup(render());expect(html).toContain('Historical instruction');expect(html).not.toContain('reglas.review');expect(h.csrf).not.toHaveBeenCalled();});
 it('requires confirmation and an explanation for missed application',async()=>{await open();(find('select').props.onChange as(event:unknown)=>void)({target:{value:'missed'}});(find('button').props.onClick as()=>void)();expect(h.csrf).not.toHaveBeenCalled();(find('input').props.onChange as(event:unknown)=>void)({target:{checked:true}});(find('button').props.onClick as()=>void)();expect(h.csrf).not.toHaveBeenCalled();});
 it('retains its operation ID after uncertain storage and reloads current state after recovery',async()=>{await open();(find('input').props.onChange as(event:unknown)=>void)({target:{checked:true}});h.csrf.mockRejectedValueOnce(new Error('Synthetic timeout'));(find('button').props.onClick as()=>void)();await vi.waitFor(()=>expect(h.bank[1]).toBe(false));(find('button').props.onClick as()=>void)();await vi.waitFor(()=>expect(h.bank[1]).toBe(false));expect(JSON.parse(h.csrf.mock.calls[0][1].body).id).toBe(JSON.parse(h.csrf.mock.calls[1][1].body).id);expect(h.fetch).toHaveBeenCalledTimes(2);expect(h.bank[6]).toBe(false);});
 it('never opens editing for a read-only actor',async()=>{h.fetch.mockResolvedValue(new Response(JSON.stringify({...view,can_edit:false})));await open();expect(nodes(render()).filter(item=>item.type==='textarea'||item.type==='input')).toHaveLength(0);});
 it('clears a stale view when refresh loses access',async()=>{await open();h.fetch.mockResolvedValue(new Response(JSON.stringify({error:'Unavailable'}),{status:404}));const buttons=nodes(render()).filter(item=>item.type==='button');(buttons.at(-1)!.props.onClick as()=>void)();await vi.waitFor(()=>expect(h.bank[0]).toBeNull());expect(h.csrf).not.toHaveBeenCalled();});
 it('does not reload or clear a decision when a nested detail toggles',async()=>{await open();(find('select').props.onChange as(event:unknown)=>void)({target:{value:'missed'}});(find('details').props.onToggle as(event:unknown)=>void)({currentTarget:{open:true},target:{open:true}});expect(h.fetch).toHaveBeenCalledTimes(1);expect(h.bank[3]).toBe('missed');});
});
