import React from 'react';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {translate} from '@/lib/i18n/translate';
const ws='11111111-1111-4111-8111-111111111111',conversationId='22222222-2222-4222-8222-222222222222',contactId='33333333-3333-4333-8333-333333333333',connectionId='44444444-4444-4444-8444-444444444444',revision='55555555-5555-4555-8555-555555555555',peer='+573001234567';
const h=vi.hoisted(()=>({enabled:true,locale:'es' as 'es'|'en',index:0,bank:[] as unknown[],effects:[] as (()=>void|(()=>void))[],fetch:vi.fn(),storage:new Map<string,string>()}));
vi.mock('@/lib/ui/improvements-preview',()=>({get SHOW_RIVERZ_IMPROVEMENTS(){return h.enabled;}}));
vi.mock('@/hooks/use-locale',()=>({useT:()=> (key:string,vars?:Record<string,string|number>)=>translate(h.locale,key,vars)}));vi.mock('@/lib/api/fetch-with-csrf',()=>({useFetchWithCsrf:()=>h.fetch}));
vi.mock('react',async()=>({...await vi.importActual<typeof import('react')>('react'),useState:(initial:unknown)=>{const n=h.index++;if(!(n in h.bank))h.bank[n]=initial;return [h.bank[n],(value:unknown)=>{h.bank[n]=typeof value==='function'?value(h.bank[n]):value;}];},useRef:(initial:unknown)=>{const n=h.index++;if(!(n in h.bank))h.bank[n]={current:initial};return h.bank[n];},useEffect:(effect:()=>void|(()=>void))=>{h.effects.push(effect);}}));
import {SmsCaseTools} from './sms-case-tools';
import {SmsSettings} from '@/components/settings/sms-settings';
type Element=React.ReactElement<Record<string,unknown>>;
function nodes(raw:React.ReactNode):Element[]{if(Array.isArray(raw))return raw.flatMap(nodes);if(!React.isValidElement(raw))return [];const e=raw as Element;return [e,...nodes(e.props.children as React.ReactNode)];}
function text(raw:unknown):string{if(Array.isArray(raw))return raw.map(text).join('');if(React.isValidElement(raw))return text((raw as Element).props.children);return typeof raw==='string'?raw:'';}
function render(){h.index=0;return nodes(SmsCaseTools({workspaceId:ws,conversationId,contactId,connectionId,peer}));}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
async function initialize(){render();const cleanup=h.effects[0]();await tick();return cleanup;}
const policy={connectionId,phone:'+12025550100',revision,enabled:true,maxSegments:3,dailySegments:100,consent:true,consentSource:'human',consentAt:new Date().toISOString()},storageKey=`riverz:sms:${ws}:${conversationId}`;
const receipt=(id:string,state='accepted')=>({attemptId:id,conversationId,contactId,peer,text:'Approved fixture text',segments:1,state,providerStatus:state==='accepted'?'queued':null,providerParts:state==='accepted'?1:null,cost:null,deliveryConfirmed:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
const button=(key:string)=>render().find(e=>typeof e.props.onClick==='function'&&text(e.props.children)===translate(h.locale,'settings.'+key));
function write(value='Approved fixture text'){const field=render().find(e=>e.props.maxLength===6700)!;(field.props.onChange as (event:unknown)=>void)({target:{value}});}
function confirm(){const field=render().find(e=>e.type==='input'&&e.props.type==='checkbox')!;(field.props.onChange as (event:unknown)=>void)({target:{checked:true}});}
beforeEach(()=>{h.enabled=true;h.locale='es';h.index=0;h.bank=[];h.effects=[];h.storage.clear();vi.stubGlobal('sessionStorage',{getItem:(key:string)=>h.storage.get(key)??null,setItem:(key:string,value:string)=>h.storage.set(key,value),removeItem:(key:string)=>h.storage.delete(key)});h.fetch.mockReset().mockImplementation(async(url:string,init?:RequestInit)=>{if(url.includes('view=policy'))return Response.json(policy);if(url.includes('view=receipt'))return Response.json(receipt(h.storage.get(storageKey)!));const body=JSON.parse(String(init?.body));return Response.json({receipt:receipt(body.attemptId)});});});
afterEach(()=>vi.unstubAllGlobals());
describe('Private reviewed SMS composer',()=>{
 it('renders nothing and makes no requests in the public stage',async()=>{h.enabled=false;expect(render()).toEqual([]);h.effects[0]();await tick();expect(h.fetch).not.toHaveBeenCalled();});
 it.each(['es','en'] as const)('requires review of the exact text and shows queued, not delivered, in %s',async locale=>{h.locale=locale;await initialize();write();expect(button('smsSend')?.props.disabled).toBe(true);confirm();expect(button('smsSend')?.props.disabled).toBe(false);write('Changed after review');expect(button('smsSend')?.props.disabled).toBe(true);write();confirm();await(button('smsSend')!.props.onClick as ()=>Promise<void>)();expect(text(render())).toContain(translate(locale,'settings.smsStatus_queued'));expect(text(render())).not.toContain(translate(locale,'settings.smsDeliveryConfirmed'));expect(text(render())).not.toMatch(/settings\.sms/);});
 it('blocks a double click with one stable browser attempt',async()=>{await initialize();write();confirm();let resolve:(value:Response)=>void=()=>{};h.fetch.mockImplementation(()=>new Promise<Response>(done=>{resolve=done;}));const send=button('smsSend')!.props.onClick as ()=>Promise<void>,first=send(),second=send();expect(h.fetch).toHaveBeenCalledTimes(2);resolve(Response.json({receipt:receipt(h.storage.get(storageKey)!)}));await Promise.all([first,second]);expect(h.storage.size).toBe(1);});
 it('keeps a lost response in recovery mode and never performs a second POST',async()=>{await initialize();write();confirm();h.fetch.mockRejectedValueOnce(new Error('Fixture lost response'));await(button('smsSend')!.props.onClick as ()=>Promise<void>)();expect(button('smsSend')).toBeUndefined();expect(button('smsRecover')).toBeDefined();await(button('smsRecover')!.props.onClick as ()=>Promise<void>)();expect(h.fetch.mock.calls.map(([,init])=>init?.method??'GET')).toEqual(['GET','POST','GET']);});
 it('recovers a saved uncertain attempt after a remount and offers no new send',async()=>{const id='66666666-6666-4666-8666-666666666666';h.storage.set(storageKey,id);await initialize();h.fetch.mockResolvedValue(Response.json(receipt(id,'uncertain')));await(button('smsRecover')!.props.onClick as ()=>Promise<void>)();expect(button('smsSend')).toBeUndefined();expect(button('smsPrepareNew')).toBeUndefined();expect(h.fetch.mock.calls.every(([,init])=>init?.method!=='POST')).toBe(true);});
 it('rejects a returned receipt for another conversation',async()=>{const id='66666666-6666-4666-8666-666666666666';h.storage.set(storageKey,id);await initialize();h.fetch.mockResolvedValue(Response.json({...receipt(id),conversationId:ws}));await(button('smsRecover')!.props.onClick as ()=>Promise<void>)();expect(render().some(e=>e.props.role==='alert')).toBe(true);expect(button('smsPrepareNew')).toBeUndefined();});
 it('allows a fresh draft only after a known accepted/canceled result and clears prior confirmation',async()=>{await initialize();write();confirm();await(button('smsSend')!.props.onClick as ()=>Promise<void>)();(button('smsPrepareNew')!.props.onClick as ()=>void)();expect(h.storage.has(storageKey)).toBe(false);expect(button('smsSend')?.props.disabled).toBe(true);expect(render().find(e=>e.props.maxLength===6700)?.props.value).toBe('');});
 it('does not expose a send without explicit SMS consent',async()=>{h.fetch.mockImplementation(async()=>Response.json({...policy,consent:false,consentSource:null}));await initialize();write();expect(button('smsSend')?.props.disabled).toBe(true);expect(text(render())).toContain(translate('es','settings.smsConsentMissing'));});
 it('does not let a signed STOP be replaced by a manual grant',async()=>{h.fetch.mockImplementation(async()=>Response.json({...policy,consent:false,consentSource:'STOP'}));await initialize();expect(button('smsConsentSave')).toBeUndefined();expect(text(render())).toContain(translate('es','settings.smsConsentStop'));});
 it('does not send when saving the browser receipt fails',async()=>{await initialize();write();confirm();vi.stubGlobal('sessionStorage',{setItem:()=>{throw new Error('Fixture storage unavailable');}});await(button('smsSend')!.props.onClick as ()=>Promise<void>)();expect(h.fetch).toHaveBeenCalledOnce();});
});
describe('Private SMS installation settings',()=>{
 function renderSettings(){h.index=0;return nodes(SmsSettings({workspaceId:ws}));}
 const configured={configured:true,connectionId,revision,phoneNumberId:'1293384261075731499',phone:'+12025550100',profileId:conversationId,organizationId:contactId,enabled:true,maxSegments:3,dailySegments:100};
 it('does not request or render installation controls in the public stage',async()=>{h.enabled=false;expect(renderSettings()).toEqual([]);h.effects[0]();await tick();expect(h.fetch).not.toHaveBeenCalled();});
 it.each(['es','en'] as const)('disables without entering or receiving credentials in %s',async locale=>{
  h.locale=locale;h.fetch.mockImplementation(async(_url:string,init?:RequestInit)=>Response.json({...configured,...(init?.method==='POST'?{enabled:false}:{})}));renderSettings();h.effects[0]();await tick();
  const checkbox=renderSettings().find(e=>e.type==='input'&&e.props.type==='checkbox')!;(checkbox.props.onChange as (event:unknown)=>void)({target:{checked:false}});
  const save=renderSettings().find(e=>typeof e.props.onClick==='function'&&text(e.props.children)===translate(locale,'settings.smsSave'))!;await(save.props.onClick as ()=>Promise<void>)();
  const body=JSON.parse(String(h.fetch.mock.calls[1][1].body));expect(body.input.enabled).toBe(false);expect(body.input).not.toHaveProperty('key');expect(body.input).not.toHaveProperty('publicKey');expect(renderSettings().find(e=>e.props.type==='password')?.props.value).toBe('');expect(text(renderSettings())).not.toMatch(/settings\.sms/);
 });
 it('rejects a settings response containing private fields without exposing a credential',async()=>{h.fetch.mockImplementation(async()=>Response.json({...configured,key:'PRIVATE_FIXTURE_KEY'}));renderSettings();h.effects[0]();await tick();expect(text(renderSettings())).not.toContain('PRIVATE_FIXTURE_KEY');expect(renderSettings().some(e=>e.props.role==='alert')).toBe(true);expect(renderSettings().some(e=>e.props.type==='password')).toBe(false);});
 it('retries failed inbox ingestion and rereads canonical counts without a send or credentials',async()=>{
  let retried=false;h.fetch.mockImplementation(async(_url:string,init?:RequestInit)=>{if(init?.method==='POST'){retried=true;return Response.json({queued:2});}return Response.json({...configured,inboundQueue:{pending:retried?2:0,failed:retried?0:2}});});renderSettings();h.effects[0]();await tick();
  const retry=renderSettings().find(e=>typeof e.props.onClick==='function'&&text(e.props.children)===translate('es','settings.smsRetryInbox'))!;await(retry.props.onClick as ()=>Promise<void>)();
  expect(h.fetch.mock.calls.map(([,init])=>init?.method??'GET')).toEqual(['GET','POST','GET']);expect(JSON.parse(String(h.fetch.mock.calls[1][1].body))).toEqual({action:'retryInbox',connectionId});expect(text(renderSettings())).toContain(translate('es','settings.smsQueuePending',{count:2}));expect(text(renderSettings())).not.toContain(translate('es','settings.smsRetryInbox'));
 });
});
