import React from 'react';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {translate} from '@/lib/i18n/translate';
const ws='11111111-1111-4111-8111-111111111111',connectionId='33333333-3333-4333-8333-333333333333',revision='88888888-8888-4888-8888-888888888888',conversationId='99999999-9999-4999-8999-999999999999',orderId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const h=vi.hoisted(()=>({enabled:true,locale:'es' as 'es'|'en',index:0,bank:[] as unknown[],effects:[] as (()=>void|(()=>void))[],fetch:vi.fn(),storage:new Map<string,string>(),receipt:null as Record<string,unknown>|null}));
vi.mock('@/lib/ui/improvements-preview',()=>({get SHOW_RIVERZ_IMPROVEMENTS(){return h.enabled;}}));
vi.mock('@/hooks/use-locale',()=>({useT:()=> (key:string,vars?:Record<string,string|number>)=>translate(h.locale,key,vars)}));
vi.mock('@/hooks/use-workspace',()=>({useWorkspace:()=>({workspace:{id:'11111111-1111-4111-8111-111111111111'}})}));
vi.mock('@/lib/api/fetch-with-csrf',()=>({useFetchWithCsrf:()=>h.fetch}));
vi.mock('react',async()=>({...await vi.importActual<typeof import('react')>('react'),useState:(initial:unknown)=>{const n=h.index++;if(!(n in h.bank))h.bank[n]=initial;return [h.bank[n],(value:unknown)=>{h.bank[n]=typeof value==='function'?value(h.bank[n]):value;}];},useRef:(initial:unknown)=>{const n=h.index++;if(!(n in h.bank))h.bank[n]={current:initial};return h.bank[n];},useEffect:(effect:()=>void|(()=>void))=>{h.effects.push(effect);}}));
import {NativeSubscriptionTools,SubscriptionCaseTools} from './subscription-case-tools';
import {SubscriptionSettings} from '@/components/settings/subscription-settings';
type Element=React.ReactElement<Record<string,unknown>>;
function nodes(raw:React.ReactNode):Element[]{if(Array.isArray(raw))return raw.flatMap(nodes);if(!React.isValidElement(raw))return [];const e=raw as Element;return [e,...nodes(e.props.children as React.ReactNode)];}
function text(raw:unknown):string{if(Array.isArray(raw))return raw.map(text).join('');if(React.isValidElement(raw))return text((raw as Element).props.children);return typeof raw==='string'?raw:'';}
const props={workspaceId:ws,conversationId,orderId},storageKey=`riverz:subscription:${ws}:${conversationId}:${orderId}`;
const before={id:111,customerId:22,addressId:33,status:'active',quantity:2,price:'12.50',productId:'444',variantId:'555',title:'Fixture product',variantTitle:null,orderIntervalFrequency:1,chargeIntervalFrequency:'1',orderIntervalUnit:'month',nextChargeScheduledAt:'2026-10-20',isPrepaid:false,isSkippable:true,updatedAt:'2026-10-02T10:00:00Z',cancellationReason:null,cancellationComments:null,cancelledAt:null};
const row={subscription:before,snapshot:'a'.repeat(64),blocked:false,ownAttemptId:null,skipOptions:[{chargeId:66,date:'2026-10-20',otherItems:1}]};
const page={configured:true,enabled:true,connectionId,revision,shopDomain:'fixture-store.myshopify.com',customerId:22,rows:[row],complete:true};
const quote={connectionId,revision,shopDomain:page.shopDomain,conversationId,orderId,subscriptionId:111,snapshot:'b'.repeat(64),before,change:{type:'quantity',quantity:3},otherChargeItems:0};
function render(){h.index=0;return nodes(NativeSubscriptionTools(props));}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const button=(key:string)=>render().find(e=>typeof e.props.onClick==='function'&&text(e.props.children)===translate(h.locale,'settings.'+key));
async function initialize(load=true){render();h.effects[0]();if(load)await(button('subscriptionLoad')!.props.onClick as ()=>Promise<void>)();await tick();}
function select(){(button('subscriptionReview')!.props.onClick as ()=>void)();}
function quantity(value=3){const field=render().find(e=>e.props.type==='number')!;(field.props.onChange as (event:unknown)=>void)({target:{value:String(value)}});}
async function review(){await(button('subscriptionReview')!.props.onClick as ()=>Promise<void>)();}
function confirm(){for(const field of render().filter(e=>e.type==='input'&&e.props.type==='checkbox'))(field.props.onChange as (event:unknown)=>void)({target:{checked:true}});}
function makeReceipt(input:Record<string,unknown>,state='observed'){return {...input,before,change:input.change,state,providerAccepted:state!=='uncertain',desiredStateObserved:state==='observed',causalityVerified:false,emailRequested:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),confirmed:undefined,reviewedBillingEffects:undefined};}
beforeEach(()=>{
 h.enabled=true;h.locale='es';h.index=0;h.bank=[];h.effects=[];h.storage.clear();h.receipt=null;
 vi.stubGlobal('sessionStorage',{getItem:(key:string)=>h.storage.get(key)??null,setItem:(key:string,value:string)=>h.storage.set(key,value),removeItem:(key:string)=>h.storage.delete(key)});
 h.fetch.mockReset().mockImplementation(async(url:string,init?:RequestInit)=>{
  if(url.includes('view=page'))return Response.json(page);if(url.includes('view=receipt')||url.includes('view=reconcile'))return h.receipt?Response.json(h.receipt):Response.json({code:'attemptNotFound'},{status:404});
  const body=JSON.parse(String(init?.body));if(body.action==='preview')return Response.json({...quote,change:body.input.change});if(body.action==='abandon')return Response.json({abandoned:true});
  const input={...body.input};delete input.confirmed;delete input.reviewedBillingEffects;h.receipt=makeReceipt(input);return Response.json({receipt:h.receipt});
 });
});
afterEach(()=>vi.unstubAllGlobals());
describe('Human-reviewed subscriptions UI',()=>{
 it('adds no controls or requests to the public stage',async()=>{h.enabled=false;expect(SubscriptionCaseTools({conversationId,orderId})).toBeNull();expect(render()).toEqual([]);h.effects[0]();await tick();expect(h.fetch).not.toHaveBeenCalled();});
 it('makes no request on mounting collapsed tools',async()=>{await initialize(false);expect(h.fetch).not.toHaveBeenCalled();});
 it.each(['es','en'] as const)('requires exact review and both confirmations, with localized receipt in %s',async locale=>{h.locale=locale;await initialize();select();quantity();expect(button('subscriptionApply')).toBeUndefined();await review();expect(button('subscriptionApply')?.props.disabled).toBe(true);confirm();expect(button('subscriptionApply')?.props.disabled).toBe(false);await(button('subscriptionApply')!.props.onClick as ()=>Promise<void>)();expect(text(render())).toContain(translate(locale,'settings.subscriptionState_observed'));expect(text(render())).not.toMatch(/settings\.subscription/);});
 it('editing after review removes the approval rather than reusing it',async()=>{await initialize();select();quantity();await review();confirm();quantity(4);expect(button('subscriptionApply')).toBeUndefined();expect(render().some(e=>e.props.type==='checkbox')).toBe(false);});
 it('one double click produces one execution POST and durable identifiers only',async()=>{await initialize();select();quantity();await review();confirm();let resolve:(value:Response)=>void=()=>{};h.fetch.mockImplementationOnce(()=>new Promise<Response>(done=>{resolve=done;}));const apply=button('subscriptionApply')!.props.onClick as ()=>Promise<void>,first=apply(),second=apply();expect(h.fetch.mock.calls.filter(([,init])=>JSON.parse(String(init?.body??'{}')).action==='execute')).toHaveLength(1);const pending=JSON.parse(h.storage.get(storageKey)!);expect(Object.keys(pending).sort()).toEqual(['attemptId','connectionId','conversationId','orderId','subscriptionId'].sort());resolve(Response.json({receipt:makeReceipt({...pending,revision,snapshot:quote.snapshot,change:quote.change})}));await Promise.all([first,second]);});
 it('a lost response recovers only by GET with no repeated execution',async()=>{await initialize();select();quantity();await review();confirm();h.fetch.mockImplementationOnce(async(_url:string,init?:RequestInit)=>{const input={...JSON.parse(String(init?.body)).input};delete input.confirmed;delete input.reviewedBillingEffects;h.receipt=makeReceipt(input,'uncertain');throw new Error('lost fictional response');});await(button('subscriptionApply')!.props.onClick as ()=>Promise<void>)();await(button('subscriptionRecover')!.props.onClick as ()=>Promise<void>)();await tick();await(button('subscriptionReconcile')!.props.onClick as ()=>Promise<void>)();await tick();expect(h.fetch.mock.calls.filter(([,init])=>JSON.parse(String(init?.body??'{}')).action==='execute')).toHaveLength(1);expect(text(render())).toContain(translate('es','settings.subscriptionState_uncertain'));});
 it('an absent receipt never clears pending authority or permits another execution',async()=>{await initialize();select();quantity();await review();confirm();h.fetch.mockRejectedValueOnce(new Error('lost fictional response'));await(button('subscriptionApply')!.props.onClick as ()=>Promise<void>)();await(button('subscriptionRecover')!.props.onClick as ()=>Promise<void>)();expect(h.storage.has(storageKey)).toBe(true);expect(button('subscriptionApply')?.props.disabled).toBe(true);});
 it('clears an absent pending attempt only after durable server abandonment',async()=>{await initialize();select();quantity();await review();confirm();h.fetch.mockRejectedValueOnce(new Error('lost fictional response'));await(button('subscriptionApply')!.props.onClick as ()=>Promise<void>)();await(button('subscriptionAbandon')!.props.onClick as ()=>Promise<void>)();expect(h.storage.has(storageKey)).toBe(false);expect(text(render())).toContain(translate('es','settings.subscriptionAbandoned'));});
 it('cannot abandon a provider-claimed uncertain result',async()=>{await initialize();select();quantity();await review();confirm();await(button('subscriptionApply')!.props.onClick as ()=>Promise<void>)();h.fetch.mockResolvedValueOnce(Response.json({abandoned:false}));await(button('subscriptionAbandon')!.props.onClick as ()=>Promise<void>)();expect(h.storage.has(storageKey)).toBe(true);});
 it('restores a pending attempt after remount without a provider call',async()=>{const pending={attemptId:'55555555-5555-4555-8555-555555555555',connectionId,conversationId,orderId,subscriptionId:111};h.storage.set(storageKey,JSON.stringify(pending));h.receipt=makeReceipt({...pending,revision,snapshot:quote.snapshot,change:quote.change},'uncertain');await initialize(false);await(button('subscriptionRecover')!.props.onClick as ()=>Promise<void>)();expect(h.fetch).toHaveBeenCalledOnce();expect(h.fetch.mock.calls[0][1]?.method).toBeUndefined();});
 it('fails closed on corrupted pending storage instead of exposing a fresh write',async()=>{h.storage.set(storageKey,'invalid');await initialize();select();quantity();await review();expect(h.fetch).toHaveBeenCalledOnce();expect(render().some(e=>e.type==='fieldset'&&e.props.disabled)).toBe(true);});
 it('does not execute if browser persistence fails',async()=>{await initialize();select();quantity();await review();confirm();vi.stubGlobal('sessionStorage',{setItem:()=>{throw new Error('fixture storage unavailable');}});await(button('subscriptionApply')!.props.onClick as ()=>Promise<void>)();expect(h.fetch).toHaveBeenCalledTimes(2);});
 it.each([{orderId:ws},{connectionId:ws},{subscriptionId:112},{snapshot:'c'.repeat(64)},{change:{type:'quantity',quantity:4}}])('rejects a mismatched execution receipt',async patch=>{await initialize();select();quantity();await review();confirm();h.fetch.mockImplementationOnce(async(_url:string,init?:RequestInit)=>{const input={...JSON.parse(String(init?.body)).input};delete input.confirmed;delete input.reviewedBillingEffects;return Response.json({receipt:{...makeReceipt(input),...patch}});});await(button('subscriptionApply')!.props.onClick as ()=>Promise<void>)();expect(button('subscriptionClose')).toBeUndefined();expect(h.storage.has(storageKey)).toBe(true);});
 it('keeps the subscription blocked after closing a known result until a fresh read',async()=>{await initialize();select();quantity();await review();confirm();await(button('subscriptionApply')!.props.onClick as ()=>Promise<void>)();(button('subscriptionClose')!.props.onClick as ()=>void)();expect(h.storage.has(storageKey)).toBe(false);expect(button('subscriptionReview')).toBeUndefined();expect(button('subscriptionRecover')).toBeDefined();});
});
describe('Installer-owned Recharge settings',()=>{
 function renderSettings(){h.index=0;return nodes(SubscriptionSettings({workspaceId:ws}));}
 const settings={configured:true,connectionId,revision,shopifyConnectionId:ws,shopDomain:page.shopDomain,storeId:7,identifier:'store-id',enabled:true,dailyChanges:50,stores:[]};
 async function open(){renderSettings();h.effects[0]();(renderSettings().find(e=>typeof e.props.onToggle==='function')!.props.onToggle as (event:unknown)=>void)({currentTarget:{open:true}});await tick();}
 it('has no request while collapsed',async()=>{renderSettings();h.effects[0]();await tick();expect(h.fetch).not.toHaveBeenCalled();});
 it.each(['es','en'] as const)('pauses an installation without exposing or resubmitting a key in %s',async locale=>{h.locale=locale;h.fetch.mockImplementation(async(_url:string,init?:RequestInit)=>Response.json({...settings,enabled:init?.method==='POST'?false:true}));await open();const checkbox=renderSettings().find(e=>e.type==='input'&&e.props.type==='checkbox')!;(checkbox.props.onChange as (event:unknown)=>void)({target:{checked:false}});const save=renderSettings().find(e=>typeof e.props.onClick==='function'&&text(e.props.children)===translate(locale,'settings.subscriptionSave'))!;await(save.props.onClick as ()=>Promise<void>)();const body=JSON.parse(String(h.fetch.mock.calls[1][1].body));expect(body.input.enabled).toBe(false);expect(body.input).not.toHaveProperty('key');expect(renderSettings().find(e=>e.props.type==='password')?.props.value).toBe('');expect(text(renderSettings())).not.toMatch(/settings\.subscription/);});
 it('never renders private fields from an invalid settings response',async()=>{h.fetch.mockResolvedValue(Response.json({...settings,key:'PRIVATE_FIXTURE_KEY'}));await open();expect(text(renderSettings())).not.toContain('PRIVATE_FIXTURE_KEY');expect(renderSettings().some(e=>e.props.role==='alert')).toBe(true);});
});
