'use client';
import {useEffect,useRef,useState} from 'react';
import type {z} from 'zod';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {useT} from '@/hooks/use-locale';
import {useWorkspace} from '@/hooks/use-workspace';
import {useFetchWithCsrf} from '@/lib/api/fetch-with-csrf';
import {SHOW_RIVERZ_IMPROVEMENTS} from '@/lib/ui/improvements-preview';
import {subscriptionCasePage,subscriptionChange,subscriptionPreview,subscriptionActionReceipt,subscriptionPending,type SubscriptionChange,type NativeSubscription,type NativeSubscriptionReceipt} from '@/lib/integrations/expansion/subscription-ui-contract';
type Pending=z.infer<typeof subscriptionPending>;type Page=z.infer<typeof subscriptionCasePage>;type Quote=z.infer<typeof subscriptionPreview>;
export function SubscriptionCaseTools(props:{conversationId:string;orderId:string}){return SHOW_RIVERZ_IMPROVEMENTS?<WorkspaceTools {...props}/>:null;}
function WorkspaceTools(props:{conversationId:string;orderId:string}){const {workspace}=useWorkspace();return workspace?<NativeSubscriptionTools key={`${workspace.id}:${props.conversationId}:${props.orderId}`} workspaceId={workspace.id} {...props}/>:null;}
function SubscriptionSummary({value}:{value:NativeSubscription}){const t=useT();return <dl className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-1 text-xs"><dt>{t('settings.subscriptionQuantity')}</dt><dd>{value.quantity}</dd><dt>{t('settings.subscriptionPrice')}</dt><dd>{value.price}</dd><dt>{t('settings.subscriptionCadence')}</dt><dd>{value.orderIntervalFrequency} / {value.chargeIntervalFrequency} {t(`settings.subscriptionUnit_${value.orderIntervalUnit}`)}</dd><dt>{t('settings.subscriptionNextDate')}</dt><dd className="break-all">{value.nextChargeScheduledAt??'—'}</dd></dl>;}
function ChangeSummary({change}:{change:SubscriptionChange}){const t=useT();return <div className="space-y-1 text-xs"><p className="font-medium">{t(`settings.subscriptionChange_${change.type}`)}</p>{change.type==='quantity'&&<p>{change.quantity}</p>}{change.type==='cadence'&&<p>{change.orderFrequency} / {change.chargeFrequency} {t(`settings.subscriptionUnit_${change.unit}`)}</p>}{(change.type==='date'||change.type==='skip')&&<p>{change.date}</p>}{change.type==='cancel'&&<><p className="whitespace-pre-wrap break-words">{change.reason}</p><p className="whitespace-pre-wrap break-words">{change.comments}</p></>}</div>;}
export function NativeSubscriptionTools({workspaceId,conversationId,orderId}:{workspaceId:string;conversationId:string;orderId:string}){
 const t=useT(),fetch=useFetchWithCsrf(),version=useRef(0),inFlight=useRef(false),pendingRef=useRef<Pending|null>(null);
 const [page,setPage]=useState<Page|null>(null),[selected,setSelected]=useState<number|null>(null),[draft,setDraft]=useState<Record<string,unknown>>({type:'quantity',quantity:1}),[quote,setQuote]=useState<Quote|null>(null),[confirmed,setConfirmed]=useState(false),[effects,setEffects]=useState(false),[pending,setPending]=useState<Pending|null>(null),[receipt,setReceipt]=useState<NativeSubscriptionReceipt|null>(null),[storageSafe,setStorageSafe]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[abandoned,setAbandoned]=useState(false);
 const storageKey=`riverz:subscription:${workspaceId}:${conversationId}:${orderId}`;
 useEffect(()=>{const lifecycle=version;lifecycle.current++;inFlight.current=false;pendingRef.current=null;setPage(null);setSelected(null);setQuote(null);setConfirmed(false);setEffects(false);setPending(null);setReceipt(null);setStorageSafe(true);setBusy(false);setError('');setAbandoned(false);
  if(SHOW_RIVERZ_IMPROVEMENTS)try{const raw=sessionStorage.getItem(storageKey);if(raw){const parsed=subscriptionPending.safeParse(JSON.parse(raw));if(!parsed.success||parsed.data.conversationId!==conversationId||parsed.data.orderId!==orderId)throw new Error('invalid');pendingRef.current=parsed.data;setPending(parsed.data);}}catch{setStorageSafe(false);setError('unavailable');}return()=>{lifecycle.current++;};
 },[workspaceId,conversationId,orderId,storageKey]);
 if(!SHOW_RIVERZ_IMPROVEMENTS)return null;
 function code(value:unknown){return typeof value==='string'&&['invalid','notAllowed','uncertain'].includes(value)?value:'unavailable';}
 function invalidate(){setQuote(null);setConfirmed(false);setEffects(false);setError('');setAbandoned(false);}
 const row=page?.configured?page.rows.find(item=>item.subscription.id===selected):undefined;
 function choose(type:string,item=row){if(!item)return;const value=item.subscription,skip=item.skipOptions[0];setDraft(type==='quantity'?{type,quantity:value.quantity}:type==='cadence'?{type,unit:value.orderIntervalUnit,orderFrequency:value.orderIntervalFrequency,chargeFrequency:Number(value.chargeIntervalFrequency)}:type==='date'?{type,date:value.nextChargeScheduledAt?.slice(0,10)??''}:type==='cancel'?{type,reason:'',comments:''}:type==='activate'?{type}:{type,chargeId:skip?.chargeId,date:skip?.date});invalidate();}
 function edit(name:string,value:unknown){setDraft(current=>({...current,[name]:value}));invalidate();}
 async function load(){if(inFlight.current)return;const generation=version.current;inFlight.current=true;setBusy(true);setSelected(null);invalidate();try{const query=new URLSearchParams({view:'page',conversationId,orderId}),response=await fetch(`/api/integrations/subscriptions?${query}`,{cache:'no-store',headers:{'x-workspace-id':workspaceId}}),raw=await response.json();if(!response.ok)throw new Error(code(raw.code));const parsed=subscriptionCasePage.safeParse(raw);if(!parsed.success)throw new Error('unavailable');if(version.current===generation)setPage(parsed.data);}catch(cause){if(version.current===generation){setPage(null);setError(code(cause instanceof Error?cause.message:null));}}finally{if(version.current===generation){inFlight.current=false;setBusy(false);}}}
 function select(id:number){if(inFlight.current||pendingRef.current)return;const item=page?.configured?page.rows.find(item=>item.subscription.id===id):null;if(!item||item.blocked)return;setSelected(id);choose(item.subscription.status==='cancelled'?'activate':'quantity',item);}
 async function review(){const check=subscriptionChange.safeParse(draft);if(!check.success||!row||row.blocked||!page?.configured||inFlight.current||pendingRef.current||!storageSafe)return;const generation=version.current;inFlight.current=true;setBusy(true);invalidate();try{const response=await fetch('/api/integrations/subscriptions',{method:'POST',headers:{'Content-Type':'application/json','x-workspace-id':workspaceId},body:JSON.stringify({action:'preview',input:{conversationId,orderId,subscriptionId:row.subscription.id,change:check.data}})}),raw=await response.json();if(!response.ok)throw new Error(code(raw.code));const parsed=subscriptionPreview.safeParse(raw);if(!parsed.success||parsed.data.conversationId!==conversationId||parsed.data.orderId!==orderId||parsed.data.subscriptionId!==row.subscription.id||parsed.data.connectionId!==page.connectionId||parsed.data.revision!==page.revision||JSON.stringify(parsed.data.change)!==JSON.stringify(check.data))throw new Error('unavailable');if(version.current===generation)setQuote(parsed.data);}catch(cause){if(version.current===generation)setError(code(cause instanceof Error?cause.message:null));}finally{if(version.current===generation){inFlight.current=false;setBusy(false);}}}
 function accept(raw:unknown,target:Pending){const parsed=subscriptionActionReceipt.safeParse(raw);if(!parsed.success||parsed.data.attemptId!==target.attemptId||parsed.data.connectionId!==target.connectionId||parsed.data.conversationId!==target.conversationId||parsed.data.orderId!==target.orderId||parsed.data.subscriptionId!==target.subscriptionId)throw new Error('uncertain');return parsed.data;}
 async function recover(reconcile=false){const target=pendingRef.current;if(!target||inFlight.current)return;const generation=version.current;inFlight.current=true;setBusy(true);setError('');try{const query=new URLSearchParams({view:reconcile?'reconcile':'receipt',attemptId:target.attemptId}),response=await fetch(`/api/integrations/subscriptions?${query}`,{cache:'no-store',headers:{'x-workspace-id':workspaceId}}),raw=await response.json();
  // Absence alone never authorizes another POST; a delayed request may arrive.
  if(!response.ok)throw new Error(response.status===404?'uncertain':code(raw.code));const value=accept(raw,target);if(version.current===generation)setReceipt(value);}catch(cause){if(version.current===generation)setError(code(cause instanceof Error?cause.message:null));}finally{if(version.current===generation){inFlight.current=false;setBusy(false);}}}
 async function apply(){if(!quote||!row||row.blocked||!confirmed||!effects||inFlight.current||pendingRef.current||!storageSafe)return;const check=subscriptionChange.safeParse(draft);if(!check.success||JSON.stringify(check.data)!==JSON.stringify(quote.change))return;const generation=version.current;inFlight.current=true;setBusy(true);setError('');try{const target={attemptId:crypto.randomUUID(),connectionId:quote.connectionId,conversationId,orderId,subscriptionId:quote.subscriptionId};sessionStorage.setItem(storageKey,JSON.stringify(target));pendingRef.current=target;setPending(target);setConfirmed(false);setEffects(false);
  const response=await fetch('/api/integrations/subscriptions',{method:'POST',headers:{'Content-Type':'application/json','x-workspace-id':workspaceId},body:JSON.stringify({action:'execute',input:{...target,revision:quote.revision,snapshot:quote.snapshot,change:quote.change,confirmed:true,reviewedBillingEffects:true}})}),raw=await response.json();if(!response.ok)throw new Error(code(raw.code));const value=accept(raw.receipt,target);if(value.snapshot!==quote.snapshot||value.revision!==quote.revision||JSON.stringify(value.change)!==JSON.stringify(quote.change))throw new Error('uncertain');if(version.current===generation)setReceipt(value);}catch(cause){if(version.current===generation)setError(code(cause instanceof Error?cause.message:null));}finally{if(version.current===generation){inFlight.current=false;setBusy(false);}}}
 function clearPending(){sessionStorage.removeItem(storageKey);pendingRef.current=null;setPending(null);setReceipt(null);setSelected(null);invalidate();}
 async function abandon(){const target=pendingRef.current;if(!target||inFlight.current)return;const generation=version.current;inFlight.current=true;setBusy(true);setError('');try{const response=await fetch('/api/integrations/subscriptions',{method:'POST',headers:{'Content-Type':'application/json','x-workspace-id':workspaceId},body:JSON.stringify({action:'abandon',input:target})}),raw=await response.json();if(!response.ok)throw new Error(code(raw.code));if(raw.abandoned!==true)throw new Error('uncertain');if(version.current===generation){clearPending();setAbandoned(true);}}catch(cause){if(version.current===generation)setError(code(cause instanceof Error?cause.message:null));}finally{if(version.current===generation){inFlight.current=false;setBusy(false);}}}
 function close(){if(!receipt||!['observed','accepted','canceled','uncertain'].includes(receipt.state)||inFlight.current)return;try{const old=receipt;if(old.state!=='canceled')setPage(current=>current?.configured?{...current,rows:current.rows.map(item=>item.subscription.id===old.subscriptionId?{...item,blocked:true,ownAttemptId:old.attemptId}:item)}:current);clearPending();}catch{setError('unavailable');}}
 function openSaved(target:Pending){if(inFlight.current||pendingRef.current||!storageSafe)return;try{sessionStorage.setItem(storageKey,JSON.stringify(target));pendingRef.current=target;setPending(target);setReceipt(null);setSelected(null);invalidate();}catch{setError('unavailable');}}
 const disabled=busy||!!pending||!storageSafe;
 return <section className="min-w-0 rounded-lg border p-3"><details onToggle={event=>{if(event.currentTarget.open&&!page&&!inFlight.current&&!pendingRef.current)void load();}}><summary className="cursor-pointer text-xs font-medium">{t('settings.subscriptionTitle')}</summary><div className="mt-3 min-w-0 space-y-3">
 {pending&&<div className="space-y-2 rounded-lg border p-3 text-xs"><p>{t('settings.subscriptionPendingNote')}</p><p>Recharge · #{pending.subscriptionId}</p><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={()=>void recover()}>{t('settings.subscriptionRecover')}</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>void recover(true)}>{t('settings.subscriptionReconcile')}</Button><Button size="sm" variant="outline" disabled={busy} onClick={abandon}>{t('settings.subscriptionAbandon')}</Button></div>
 {receipt&&<div role="status" className="space-y-2"><p>{t(`settings.subscriptionState_${receipt.state}`)}</p><ChangeSummary change={receipt.change}/>{receipt.state==='uncertain'&&receipt.desiredStateObserved&&<p>{t('settings.subscriptionObservedUncertain')}</p>}<p className="text-muted-foreground">{t('settings.subscriptionEvidenceNote')}</p>{['observed','accepted','canceled','uncertain'].includes(receipt.state)&&<Button size="sm" variant="outline" disabled={busy} onClick={close}>{t('settings.subscriptionClose')}</Button>}</div>}</div>}
 {abandoned&&<p role="status" className="text-xs">{t('settings.subscriptionAbandoned')}</p>}<Button size="sm" variant="outline" disabled={busy} onClick={load}>{t('settings.subscriptionLoad')}</Button>
 {page&&!page.configured&&<p className="text-xs text-muted-foreground">{t('settings.subscriptionConfigure')}</p>}
 {page?.configured&&<><p className="break-words text-xs">{page.shopDomain}</p>{!page.rows.length&&<p className="text-xs">{t('settings.subscriptionEmpty')}</p>}<ul className="space-y-3">{page.rows.map(item=><li key={item.subscription.id} className="min-w-0 rounded-lg border p-3 space-y-2"><p className="break-words text-sm font-medium">{item.subscription.title??t('settings.subscriptionProduct',{id:item.subscription.id})}</p><p className="text-xs text-muted-foreground">#{item.subscription.id} · {t(`settings.subscriptionStatus_${item.subscription.status}`)}</p><SubscriptionSummary value={item.subscription}/>
 {item.blocked?<div className="space-y-2 text-xs"><p>{t('settings.subscriptionPendingNote')}</p>{item.ownAttemptId&&<Button size="sm" variant="outline" disabled={disabled} onClick={()=>openSaved({attemptId:item.ownAttemptId!,connectionId:page.connectionId,conversationId,orderId,subscriptionId:item.subscription.id})}>{t('settings.subscriptionRecover')}</Button>}</div>:item.subscription.status!=='expired'&&selected!==item.subscription.id?<Button size="sm" variant="outline" disabled={disabled} onClick={()=>select(item.subscription.id)}>{t('settings.subscriptionReview')}</Button>:selected===item.subscription.id&&<fieldset disabled={disabled} className="min-w-0 space-y-2">
 <select aria-label={t('settings.subscriptionAfter')} className="h-9 w-full rounded-md border bg-background px-2 text-sm" value={String(draft.type)} onChange={event=>choose(event.target.value)}>{(item.subscription.status==='cancelled'?['activate']:['quantity','cadence','date',...(item.skipOptions.length?['skip']:[]),'cancel']).map(type=><option key={type} value={type}>{t(`settings.subscriptionChange_${type}`)}</option>)}</select>
 {draft.type==='quantity'&&<label className="block space-y-1 text-xs">{t('settings.subscriptionQuantity')}<Input type="number" min={1} max={100} value={String(draft.quantity??'')} onChange={event=>edit('quantity',Number(event.target.value))}/></label>}
 {draft.type==='cadence'&&<div className="space-y-2"><select className="h-9 w-full rounded-md border bg-background px-2 text-sm" aria-label={t('settings.subscriptionCadence')} value={String(draft.unit)} onChange={event=>edit('unit',event.target.value)}>{['day','week','month'].map(value=><option key={value} value={value}>{t(`settings.subscriptionUnit_${value}`)}</option>)}</select>{[['orderFrequency','subscriptionOrderFrequency'],['chargeFrequency','subscriptionChargeFrequency']].map(([field,label])=><label key={field} className="block text-xs">{t('settings.'+label)}<Input type="number" min={1} max={1000} value={String(draft[field]??'')} onChange={event=>edit(field,Number(event.target.value))}/></label>)}</div>}
 {draft.type==='date'&&<label className="block space-y-1 text-xs">{t('settings.subscriptionNextDate')}<Input type="date" value={String(draft.date??'')} onChange={event=>edit('date',event.target.value)}/></label>}
 {draft.type==='skip'&&<label className="block space-y-1 text-xs">{t('settings.subscriptionDelivery')}<select className="h-9 w-full rounded-md border bg-background px-2 text-sm" value={item.skipOptions.findIndex(option=>option.chargeId===draft.chargeId&&option.date===draft.date)} onChange={event=>{const option=item.skipOptions[Number(event.target.value)];if(option){setDraft({type:'skip',chargeId:option.chargeId,date:option.date});invalidate();}}}>{item.skipOptions.map((option,index)=><option key={`${option.chargeId}:${option.date}`} value={index}>{option.date}</option>)}</select></label>}
 {draft.type==='cancel'&&<><label className="block space-y-1 text-xs">{t('settings.subscriptionReason')}<Input maxLength={1000} value={String(draft.reason??'')} onChange={event=>edit('reason',event.target.value)}/></label><label className="block space-y-1 text-xs">{t('settings.subscriptionComments')}<Textarea maxLength={1024} value={String(draft.comments??'')} onChange={event=>edit('comments',event.target.value)}/></label></>}
 <Button size="sm" variant="outline" disabled={disabled||!subscriptionChange.safeParse(draft).success} onClick={review}>{t('settings.subscriptionReview')}</Button>
 {quote&&<div className="space-y-2 rounded-lg border p-3"><p className="text-xs font-medium">{t('settings.subscriptionBefore')}</p><SubscriptionSummary value={quote.before}/><p className="text-xs font-medium">{t('settings.subscriptionAfter')}</p><ChangeSummary change={quote.change}/>{quote.change.type==='skip'&&<p className="text-xs">{t('settings.subscriptionOtherItems',{count:quote.otherChargeItems})}</p>}<label className="flex items-start gap-2 text-xs"><input type="checkbox" checked={effects} onChange={event=>setEffects(event.target.checked)}/>{t('settings.subscriptionBillingEffects')}</label><label className="flex items-start gap-2 text-xs"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>{t('settings.subscriptionConfirm',{id:quote.subscriptionId,shop:quote.shopDomain})}</label><Button size="sm" disabled={disabled||!confirmed||!effects} onClick={apply}>{t('settings.subscriptionApply')}</Button></div>}
 </fieldset>}
 </li>)}</ul></>}{error&&<p role="alert" className="text-xs text-destructive">{t(`settings.subscriptionError_${code(error)}`)}</p>}
 </div></details></section>;
}
