import React from 'react';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {translate} from '@/lib/i18n/translate';
const ws='11111111-1111-4111-8111-111111111111',connectionId='44444444-4444-4444-8444-444444444444',revision='55555555-5555-4555-8555-555555555555';
const h=vi.hoisted(()=>({enabled:true,locale:'es' as 'es'|'en',index:0,bank:[] as unknown[],effects:[] as (()=>void|(()=>void))[],fetch:vi.fn(),storage:new Map<string,string>()}));
vi.mock('@/lib/ui/improvements-preview',()=>({get SHOW_RIVERZ_IMPROVEMENTS(){return h.enabled;}}));
vi.mock('@/hooks/use-locale',()=>({useT:()=> (key:string,vars?:Record<string,string|number>)=>translate(h.locale,key,vars)}));
vi.mock('@/hooks/use-workspace',()=>({useWorkspace:()=>({workspace:{id:'11111111-1111-4111-8111-111111111111'}})}));
vi.mock('@/lib/api/fetch-with-csrf',()=>({useFetchWithCsrf:()=>h.fetch}));
vi.mock('react',async()=>({...await vi.importActual<typeof import('react')>('react'),useState:(initial:unknown)=>{const n=h.index++;if(!(n in h.bank))h.bank[n]=initial;return [h.bank[n],(value:unknown)=>{h.bank[n]=typeof value==='function'?value(h.bank[n]):value;}];},useRef:(initial:unknown)=>{const n=h.index++;if(!(n in h.bank))h.bank[n]={current:initial};return h.bank[n];},useEffect:(effect:()=>void|(()=>void))=>{h.effects.push(effect);}}));
import {StoreReviewTools,StoreReviews} from './store-reviews';
import {ReviewSettings} from '@/components/settings/review-settings';
type Element=React.ReactElement<Record<string,unknown>>;
function nodes(raw:React.ReactNode):Element[]{if(Array.isArray(raw))return raw.flatMap(nodes);if(!React.isValidElement(raw))return [];const e=raw as Element;return [e,...nodes(e.props.children as React.ReactNode)];}
function text(raw:unknown):string{if(Array.isArray(raw))return raw.map(text).join('');if(React.isValidElement(raw))return text((raw as Element).props.children);return typeof raw==='string'?raw:'';}
function render(){h.index=0;return nodes(StoreReviewTools({workspaceId:ws}));}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const row={id:42,title:'Fixture title',body:'<script>untrusted review</script>',rating:5,hidden:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),productExternalId:123,productTitle:'Fixture product',snapshot:'a'.repeat(64),reply:{blocked:false,state:null,ownAttemptId:null}};
const page={configured:true,connectionId,revision,shopDomain:'fixture.myshopify.com',enabled:true,rows:[row],page:1,hasNext:false},storageKey=`riverz:review:${ws}`;
const receipt=(id:string,state='accepted')=>({attemptId:id,connectionId,reviewId:42,text:'Approved fixture reply',state,providerConfirmedCreation:state==='accepted',independentPublicationVerified:false,emailRequested:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
const button=(key:string)=>render().find(e=>typeof e.props.onClick==='function'&&text(e.props.children)===translate(h.locale,'settings.'+key));
async function initialize(load=true){render();h.effects[0]();if(load)await(button('reviewLoad')!.props.onClick as ()=>Promise<void>)();await tick();}
function openReply(){(button('reviewReply')!.props.onClick as ()=>void)();}
function write(value='Approved fixture reply'){const field=render().find(e=>e.props.maxLength===4000)!;(field.props.onChange as (event:unknown)=>void)({target:{value}});}
function confirm(){for(const field of render().filter(e=>e.type==='input'&&e.props.type==='checkbox'))(field.props.onChange as (event:unknown)=>void)({target:{checked:true}});}
beforeEach(()=>{h.enabled=true;h.locale='es';h.index=0;h.bank=[];h.effects=[];h.storage.clear();vi.stubGlobal('sessionStorage',{getItem:(key:string)=>h.storage.get(key)??null,setItem:(key:string,value:string)=>h.storage.set(key,value),removeItem:(key:string)=>h.storage.delete(key)});h.fetch.mockReset().mockImplementation(async(url:string,init?:RequestInit)=>{if(url.includes('view=page'))return Response.json(page);if(url.includes('view=receipt'))return Response.json(receipt(JSON.parse(h.storage.get(storageKey)!).attemptId));const body=JSON.parse(String(init?.body));return Response.json({receipt:receipt(body.input.attemptId)});});});
afterEach(()=>vi.unstubAllGlobals());
describe('Human-reviewed store replies',()=>{
 it('renders no new UI and makes no requests in the public stage',async()=>{h.enabled=false;expect(StoreReviews()).toBeNull();expect(render()).toEqual([]);h.effects[0]();await tick();expect(h.fetch).not.toHaveBeenCalled();});
 it('loads only on explicit opening/refresh and escapes review content as text',async()=>{await initialize(false);expect(h.fetch).not.toHaveBeenCalled();await(button('reviewLoad')!.props.onClick as ()=>Promise<void>)();await tick();expect(text(render())).toContain(row.body);expect(render().some(e=>e.props.dangerouslySetInnerHTML)).toBe(false);});
 it.each(['es','en'] as const)('requires two reviews, clears them on editing, and shows creation with no visibility proof in %s',async locale=>{h.locale=locale;await initialize();openReply();write();expect(button('reviewPublish')?.props.disabled).toBe(true);confirm();expect(button('reviewPublish')?.props.disabled).toBe(false);write('Changed after review');expect(button('reviewPublish')?.props.disabled).toBe(true);write();confirm();await(button('reviewPublish')!.props.onClick as ()=>Promise<void>)();expect(text(render())).toContain(translate(locale,'settings.reviewState_accepted'));expect(text(render())).toContain(translate(locale,'settings.reviewVisibilityPending'));expect(text(render())).not.toMatch(/settings\.review/);});
 it('blocks double clicks with one durable attempt and one POST',async()=>{await initialize();openReply();write();confirm();let resolve:(value:Response)=>void=()=>{};h.fetch.mockImplementation(()=>new Promise<Response>(done=>{resolve=done;}));const publish=button('reviewPublish')!.props.onClick as ()=>Promise<void>,first=publish(),second=publish();expect(h.fetch).toHaveBeenCalledTimes(2);const saved=JSON.parse(h.storage.get(storageKey)!);resolve(Response.json({receipt:receipt(saved.attemptId)}));await Promise.all([first,second]);expect(h.storage.size).toBe(1);});
 it('recovers a lost acknowledgement through GET without another publication',async()=>{await initialize();openReply();write();confirm();h.fetch.mockRejectedValueOnce(new Error('Fixture lost response'));await(button('reviewPublish')!.props.onClick as ()=>Promise<void>)();expect(button('reviewPublish')?.props.disabled).toBe(true);await(button('reviewRecover')!.props.onClick as ()=>Promise<void>)();expect(h.fetch.mock.calls.map(([,init])=>init?.method??'GET')).toEqual(['GET','POST','GET']);});
 it('recovers after remount even when the provider connection is unavailable',async()=>{const id='66666666-6666-4666-8666-666666666666';h.storage.set(storageKey,JSON.stringify({attemptId:id,connectionId,reviewId:42}));await initialize(false);h.fetch.mockResolvedValueOnce(Response.json({code:'notAllowed'},{status:403}));await(button('reviewLoad')!.props.onClick as ()=>Promise<void>)();await tick();h.fetch.mockResolvedValueOnce(Response.json(receipt(id,'uncertain')));await(button('reviewRecover')!.props.onClick as ()=>Promise<void>)();expect(button('reviewCloseReceipt')).toBeUndefined();expect(text(render())).toContain(translate('es','settings.reviewState_uncertain'));expect(h.fetch.mock.calls.every(([,init])=>init?.method!=='POST')).toBe(true);});
 it.each([{connectionId:ws},{reviewId:43},{text:'Rewritten unapproved response'}])('rejects a mismatched publication receipt: %s',async change=>{await initialize();openReply();write();confirm();h.fetch.mockImplementationOnce(async(_url:string,init?:RequestInit)=>Response.json({receipt:{...receipt(JSON.parse(String(init?.body)).input.attemptId),...change}}));await(button('reviewPublish')!.props.onClick as ()=>Promise<void>)();expect(button('reviewCloseReceipt')).toBeUndefined();expect(render().some(e=>e.props.role==='alert')).toBe(true);});
 it('offers no fresh reply for hidden or previously accepted reviews',async()=>{h.fetch.mockResolvedValue(Response.json({...page,rows:[{...row,hidden:true},{...row,id:43,reply:{blocked:true,state:'accepted',ownAttemptId:null}}]}));await initialize();expect(button('reviewReply')).toBeUndefined();expect(text(render())).toContain(translate('es','settings.reviewHidden'));});
 it('does not publish when durable browser storage is unavailable',async()=>{await initialize();openReply();write();confirm();vi.stubGlobal('sessionStorage',{setItem:()=>{throw new Error('Fixture unavailable');}});await(button('reviewPublish')!.props.onClick as ()=>Promise<void>)();expect(h.fetch).toHaveBeenCalledOnce();});
 it('keeps accepted reviews blocked after closing the known result',async()=>{await initialize();openReply();write();confirm();await(button('reviewPublish')!.props.onClick as ()=>Promise<void>)();(button('reviewCloseReceipt')!.props.onClick as ()=>void)();expect(h.storage.has(storageKey)).toBe(false);expect(button('reviewReply')).toBeUndefined();});
 it('rejects HTML/unpaired Unicode drafts without calling the publisher',async()=>{await initialize();openReply();for(const value of ['<b>Reply</b>','Broken\ud800']){write(value);confirm();expect(button('reviewPublish')?.props.disabled).toBe(true);await(button('reviewPublish')!.props.onClick as ()=>Promise<void>)();}expect(h.fetch).toHaveBeenCalledOnce();});
 it('shows the query limit without claiming a full-store total',async()=>{h.fetch.mockImplementation(async(url:string)=>Response.json({...page,page:Number(new URL(url,'https://fixture.invalid').searchParams.get('page')),hasNext:true}));await initialize();for(let n=2;n<=50;n++){await(button('reviewNext')!.props.onClick as ()=>Promise<void>)();await tick();}expect(button('reviewNext')?.props.disabled).toBe(true);expect(text(render())).toContain(translate('es','settings.reviewPageLimit'));expect(text(render())).toContain(translate('es','settings.reviewPage',{page:50,count:1}));});
});
describe('Private review configuration',()=>{
 function renderSettings(){h.index=0;return nodes(ReviewSettings({workspaceId:ws}));}
 const configured={configured:true,connectionId,revision,shopifyConnectionId:ws,shopDomain:'fixture.myshopify.com',enabled:true,dailyReplies:50,stores:[]};
 async function loadSettings(){renderSettings();h.effects[0]();(renderSettings().find(e=>typeof e.props.onToggle==='function')!.props.onToggle as (event:unknown)=>void)({currentTarget:{open:true}});await tick();}
 it('makes no request while collapsed or while hidden in the public stage',async()=>{renderSettings();h.effects[0]();await tick();expect(h.fetch).not.toHaveBeenCalled();h.enabled=false;expect(renderSettings()).toEqual([]);expect(h.fetch).not.toHaveBeenCalled();});
 it.each(['es','en'] as const)('disables a disconnected shop without re-entering or exposing keys in %s',async locale=>{h.locale=locale;h.fetch.mockImplementation(async(_url:string,init?:RequestInit)=>Response.json({...configured,...(init?.method==='POST'?{enabled:false}:{})}));await loadSettings();const checkbox=renderSettings().find(e=>e.type==='input'&&e.props.type==='checkbox')!;(checkbox.props.onChange as (event:unknown)=>void)({target:{checked:false}});const save=renderSettings().find(e=>typeof e.props.onClick==='function'&&text(e.props.children)===translate(locale,'settings.reviewSave'))!;await(save.props.onClick as ()=>Promise<void>)();const body=JSON.parse(String(h.fetch.mock.calls[1][1].body));expect(body.input.enabled).toBe(false);expect(body.input.shopDomain).toBe(configured.shopDomain);expect(body.input).not.toHaveProperty('key');expect(renderSettings().find(e=>e.props.type==='password')?.props.value).toBe('');expect(text(renderSettings())).not.toMatch(/settings\.review/);});
 it('rejects private fields in a settings response without rendering credentials',async()=>{h.fetch.mockResolvedValue(Response.json({...configured,key:'PRIVATE_FIXTURE_KEY'}));await loadSettings();expect(text(renderSettings())).not.toContain('PRIVATE_FIXTURE_KEY');expect(renderSettings().some(e=>e.props.role==='alert')).toBe(true);});
});
