# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "57bf672c917dc8a03d3ba61f6c0d5fed"
application_url = "https://riverz.co"
embedded = true
name = "Riverz"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "https://riverz.co/api/shopify/webhooks/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://riverz.co/api/shopify/webhooks/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://riverz.co/api/shopify/webhooks/shop-redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customers,write_customers,read_orders,write_orders,read_products,read_fulfillments,write_fulfillments,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_price_rules,write_price_rules,write_discounts,read_order_edits,write_order_edits,read_draft_orders,write_draft_orders"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://riverz.co/api/shopify/oauth/callback",
  "https://riverz.co/api/shopify/callback"
]
