import {beforeEach,describe,expect,it,vi} from 'vitest';
import {createJudgeMeClient} from './judgeme-client';
const review={id:111,title:'Example',body:'<script>untrusted</script>',rating:5,hidden:true,created_at:'2026-10-02T10:00:00Z',updated_at:'2026-10-02T10:00:00Z',product_external_id:999,product_title:'Product',reviewer:{email:'private@example.invalid'},ip_address:'192.0.2.1'},read=vi.fn<typeof fetch>();
beforeEach(()=>{read.mockReset().mockImplementation(async()=>Response.json({current_page:1,per_page:100,reviews:[review]}));});
const client=()=>createJudgeMeClient('example.myshopify.com','fixture-private-key',read);
describe('Judge.me contract, private fixtures only',()=>{
 it('lists only the selected store with a private header and no dangerous product filter',async()=>{const result=await client().list(1);expect(result.done).toBe(true);expect(result.reviews[0]).toMatchObject({id:111,hidden:true,productExternalId:999,body:review.body});expect(JSON.stringify(result)).not.toMatch(/private@example|192\.0\.2|reviewer/);const [url,init]=read.mock.calls[0];expect(String(url)).toBe('https://api.judge.me/api/v1/reviews?shop_domain=example.myshopify.com&page=1&per_page=100');expect(init?.headers).toMatchObject({'X-Api-Token':'fixture-private-key'});});
 it('does not call a full page terminal or invent a total',async()=>{read.mockImplementationOnce(async()=>Response.json({current_page:1,per_page:100,reviews:Array.from({length:100},(_,n)=>({...review,id:n+1}))}));const result=await client().list(1);expect(result.done).toBe(false);expect(result).not.toHaveProperty('total');});
 it.each([{current_page:2,per_page:100,reviews:[review]},{current_page:1,per_page:100,reviews:[review,review]},{current_page:1,per_page:100,reviews:[{...review,hidden:undefined}]}])('rejects an inconsistent page without dropping the problem row',async value=>{read.mockImplementationOnce(async()=>Response.json(value));await expect(client().list(1)).rejects.toMatchObject({code:'unavailable'});});
 it('reads the exact review and rejects another returned record',async()=>{read.mockImplementationOnce(async()=>Response.json({review}));expect(await client().review(111)).toMatchObject({id:111});read.mockImplementationOnce(async()=>Response.json({review:{...review,id:112}}));await expect(client().review(111)).rejects.toMatchObject({code:'unavailable'});});
 it('requires review authority before posting and explicitly disables incidental email',async()=>{const authorize=vi.fn().mockResolvedValue(false);await expect(client().publicReply(111,'Thank you',authorize)).rejects.toMatchObject({code:'notAllowed'});expect(read).not.toHaveBeenCalled();authorize.mockResolvedValue(true);read.mockImplementationOnce(async()=>new Response('',{status:200}));expect(await client().publicReply(111,'Thank you',authorize)).toEqual({providerConfirmedCreation:true,reviewId:111,content:'Thank you',emailRequested:false,independentPublicationVerified:false});expect(JSON.parse(String(read.mock.calls[0][1]?.body))).toEqual({review_id:111,send_reply_email:false,reply:{content:'Thank you'}});});
 it('does not repeat an uncertain publish or accept an undocumented status as creation',async()=>{read.mockRejectedValueOnce(new Error('PRIVATE_SECRET'));await expect(client().publicReply(111,'Thank you',async()=>true)).rejects.toMatchObject({code:'uncertain'});expect(read).toHaveBeenCalledOnce();read.mockImplementationOnce(async()=>new Response('',{status:202}));await expect(client().publicReply(111,'Thank you',async()=>true)).rejects.toMatchObject({code:'uncertain'});});
 it.each(['https://example.myshopify.com','example.myshopify.com.evil.invalid','OTHER.myshopify.com'])('rejects a different/unvalidated shop domain %s',shop=>expect(()=>createJudgeMeClient(shop,'fixture-private-key',read)).toThrow('expansion_provider_invalid'));
});
