import {beforeEach,describe,expect,it,vi} from 'vitest';
import {expansionHttp,privateProviderSecret} from './provider-http';
const read=vi.fn<typeof fetch>();beforeEach(()=>{read.mockReset().mockImplementation(async()=>Response.json({data:{id:'fixture'}}));});
describe('Fixed expansion provider HTTP boundary, no real requests',()=>{
 it('keeps credentials in headers and disables cache, redirect and retry',async()=>{await expansionHttp('telnyx',read)('/v2/messages/fixture',{headers:{Authorization:'Bearer fixture-private-key'}});expect(read).toHaveBeenCalledOnce();expect(read.mock.calls[0]).toMatchObject(['https://api.telnyx.com/v2/messages/fixture',{method:'GET',cache:'no-store',redirect:'error',headers:{Authorization:'Bearer fixture-private-key'}}]);});
 it.each(['https://evil.invalid/x','//evil.invalid/x','/v2/x?token=key','/v2/x#fragment','/v2/\\evil'])('rejects a caller-controlled path %s before fetching',async path=>{await expect(expansionHttp('telnyx',read)(path,{headers:{}})).rejects.toMatchObject({code:'invalid'});expect(read).not.toHaveBeenCalled();});
 it('rejects query credentials and a GET body',async()=>{await expect(expansionHttp('judgeme',read)('/api/v1/reviews',{headers:{},query:{api_token:'PRIVATE'}})).rejects.toMatchObject({code:'invalid'});await expect(expansionHttp('telnyx',read)('/v2/messages',{headers:{},body:{text:'x'}})).rejects.toMatchObject({code:'invalid'});expect(read).not.toHaveBeenCalled();});
 it('requires current durable authority immediately before a mutation',async()=>{const authorize=vi.fn().mockResolvedValue(false);await expect(expansionHttp('telnyx',read)('/v2/messages',{method:'POST',headers:{},body:{},authorize})).rejects.toMatchObject({code:'notAllowed'});expect(read).not.toHaveBeenCalled();authorize.mockResolvedValue(true);await expansionHttp('telnyx',read)('/v2/messages',{method:'POST',headers:{},body:{text:'fixture'},authorize});expect(authorize.mock.invocationCallOrder[1]).toBeLessThan(read.mock.invocationCallOrder[0]);});
 it.each(['GET','POST'] as const)('sanitizes an uncertain %s without a retry',async method=>{read.mockRejectedValue(new Error('PRIVATE_PROVIDER_KEY'));await expect(expansionHttp('telnyx',read)('/v2/messages',{method,headers:{},...(method==='POST'?{body:{},authorize:async()=>true}:{})})).rejects.toMatchObject({code:method==='GET'?'unavailable':'uncertain',message:`expansion_provider_${method==='GET'?'unavailable':'uncertain'}`});expect(read).toHaveBeenCalledOnce();});
 it('bounds streamed response size and rejects non-JSON success',async()=>{read.mockImplementationOnce(async()=>new Response('x'.repeat(512*1024+1)));await expect(expansionHttp('judgeme',read)('/api/v1/reviews',{headers:{}})).rejects.toMatchObject({code:'unavailable'});read.mockImplementationOnce(async()=>new Response('not JSON'));await expect(expansionHttp('judgeme',read)('/api/v1/reviews',{headers:{}})).rejects.toMatchObject({code:'unavailable'});});
 it.each(['short','private key','private\nkey'])('rejects invalid credentials %s',value=>expect(()=>privateProviderSecret(value)).toThrow('expansion_provider_invalid'));
});
