import {beforeEach,describe,expect,it,vi} from 'vitest';
import {createRechargeClient,subscriptionSkipObserved} from './recharge-client';
import {nativeSubscription,subscriptionChange,subscriptionChangeObserved,subscriptionDate} from './subscription-ui-contract';

const raw={id:111,customer_id:22,address_id:33,status:'active',quantity:2,price:'12.50',external_product_id:{ecommerce:'444'},external_variant_id:{ecommerce:'555'},product_title:'Product',variant_title:null,order_interval_frequency:1,charge_interval_frequency:'1',order_interval_unit:'month',next_charge_scheduled_at:'2026-10-20',is_prepaid:false,is_skippable:true,updated_at:'2026-10-02T10:00:00Z',cancellation_reason:null,cancellation_reason_comments:null,cancelled_at:null,email:'private@example.invalid',billing_address:{private:'omit'}};
const current=nativeSubscription.parse({id:111,customerId:22,addressId:33,status:'active',quantity:2,price:'12.50',productId:'444',variantId:'555',title:'Product',variantTitle:null,orderIntervalFrequency:1,chargeIntervalFrequency:'1',orderIntervalUnit:'month',nextChargeScheduledAt:'2026-10-20',isPrepaid:false,isSkippable:true,updatedAt:'2026-10-02T10:00:00Z',cancellationReason:null,cancellationComments:null,cancelledAt:null});
const charge={id:66,address_id:33,customer:{id:22,email:'private@example.invalid'},scheduled_at:'2026-10-20',status:'queued',has_uncommitted_changes:false,line_items:[{purchase_item_id:111,purchase_item_type:'subscription',quantity:2},{purchase_item_id:112,purchase_item_type:'subscription',quantity:1}]};
const deliveries=[{date:'2026-10-20',addressId:33,chargeId:66,lines:[{subscriptionId:111,isSkipped:false,isSkippable:true,isPrepaid:false},{subscriptionId:112,isSkipped:false,isSkippable:true,isPrepaid:false}]}];
const skip={type:'skip' as const,chargeId:66,date:'2026-10-20'};
const read=vi.fn<typeof fetch>(),authorize=vi.fn<()=>Promise<boolean>>();
const client=()=>createRechargeClient('fixture-recharge-key',read);
beforeEach(()=>{read.mockReset();authorize.mockReset().mockResolvedValue(true);});
describe('Recharge selected contract, fictional transport only',()=>{
 it('pins origin/version and projects only account metadata with nested token scopes',async()=>{
  read.mockResolvedValueOnce(Response.json({store:{id:7,external_platform:'shopify',identifier:'store-id',email:'private@example.invalid'}})).mockResolvedValueOnce(Response.json({token_information:{scopes:['read_store','read_customers','read_subscriptions'],private:'omit'}}));
  expect(await client().account()).toEqual({storeId:7,platform:'shopify',identifier:'store-id',scopes:['read_store','read_customers','read_subscriptions']});
  for(const [url,init] of read.mock.calls){expect(new URL(String(url)).origin).toBe('https://api.rechargeapps.com');expect(init?.headers).toMatchObject({'X-Recharge-Access-Token':'fixture-recharge-key','X-Recharge-Version':'2021-11'});expect(String(url)).not.toContain('fixture-recharge-key');}
 });
 it.each([{scopes:['read_store']},{token_information:{scopes:'read_store'}},{token_information:{scopes:['read_store','read_store']}}])('rejects undocumented/ambiguous scope structure',async value=>{
  read.mockResolvedValueOnce(Response.json({store:{id:7,external_platform:'shopify',identifier:'store-id'}})).mockResolvedValueOnce(Response.json(value));await expect(client().account()).rejects.toMatchObject({code:'unavailable'});
 });
 it('keeps the exact external customer filter throughout cursor pagination',async()=>{
  read.mockResolvedValueOnce(Response.json({customers:[{id:22,external_customer_id:{ecommerce:'999'}}],next_cursor:'opaque/a+b='})).mockResolvedValueOnce(Response.json({customers:[],next_cursor:null}));
  expect(await client().customerForShopify('999')).toEqual({id:22,externalCustomerId:'999'});
  expect(new URL(String(read.mock.calls[0][0])).searchParams.get('external_customer_id')).toBe('999');
  const next=new URL(String(read.mock.calls[1][0]));expect(next.searchParams.get('cursor')).toBe('opaque/a+b=');expect(next.searchParams.get('external_customer_id')).toBe('999');expect(next.searchParams.has('page')).toBe(false);
 });
 it('returns absent only after a complete empty lookup',async()=>{read.mockResolvedValueOnce(Response.json({customers:[],next_cursor:null}));expect(await client().customerForShopify('999')).toBeNull();});
 it.each([
  {customers:[{id:22,external_customer_id:{ecommerce:'998'}}]},
  {customers:[{id:22,external_customer_id:{ecommerce:'999'}},{id:23,external_customer_id:{ecommerce:'999'}}]},
 ])('rejects a mismatched or nonunique external customer identity',async value=>{read.mockResolvedValueOnce(Response.json(value));await expect(client().customerForShopify('999')).rejects.toMatchObject({code:'notAllowed'});});
 it.each(['gid://shopify/Customer/999','0','0999','999@example.invalid','-2'])('never guesses external IDs from %s',async value=>{await expect(client().customerForShopify(value)).rejects.toMatchObject({code:'invalid'});expect(read).not.toHaveBeenCalled();});
 it('checks both IDs on fresh customer read without exposing a full customer',async()=>{
  read.mockResolvedValueOnce(Response.json({customer:{id:22,external_customer_id:{ecommerce:'999'},email:'private@example.invalid'}}));expect(await client().customer(22,'999')).toEqual({id:22,externalCustomerId:'999'});
  read.mockResolvedValueOnce(Response.json({customer:{id:23,external_customer_id:{ecommerce:'999'}}}));await expect(client().customer(22,'999')).rejects.toMatchObject({code:'notAllowed'});
 });
 it('projects subscriptions without personal data and preserves documented cadence/date types',async()=>{
  read.mockResolvedValueOnce(Response.json({subscriptions:[raw,{...raw,id:112,charge_interval_frequency:2,next_charge_scheduled_at:'2026-10-20T12:00:00Z'}]}));
  const result=await client().subscriptions(22);expect(result).toHaveLength(2);expect(result[0]).toEqual(current);expect(result[1].chargeIntervalFrequency).toBe(2);expect(JSON.stringify(result)).not.toMatch(/private@example|billing_address|email/);expect(new URL(String(read.mock.calls[0][0])).searchParams.get('customer_id')).toBe('22');
 });
 it('rejects another customer subscription',async()=>{read.mockResolvedValueOnce(Response.json({subscriptions:[{...raw,customer_id:23}]}));await expect(client().subscriptions(22)).rejects.toMatchObject({code:'notAllowed'});});
 it('rejects duplicate records across pages',async()=>{read.mockResolvedValueOnce(Response.json({subscriptions:[raw],next_cursor:'next'})).mockResolvedValueOnce(Response.json({subscriptions:[raw]}));await expect(client().subscriptions(22)).rejects.toMatchObject({code:'unavailable'});});
 it('rejects a repeated cursor rather than looping',async()=>{read.mockResolvedValueOnce(Response.json({subscriptions:[raw],next_cursor:'next'})).mockResolvedValueOnce(Response.json({subscriptions:[{...raw,id:112}],next_cursor:'next'}));await expect(client().subscriptions(22)).rejects.toMatchObject({code:'unavailable'});expect(read).toHaveBeenCalledTimes(2);});
 it('does not silently claim a limited traversal is complete',async()=>{read.mockImplementation(async()=>Response.json({subscriptions:[{...raw,id:100+read.mock.calls.length}],next_cursor:`next-${read.mock.calls.length}`}));await expect(client().subscriptions(22)).rejects.toMatchObject({code:'unavailable'});expect(read).toHaveBeenCalledTimes(10);});
 it.each([{...raw,price:12.5},{...raw,charge_interval_frequency:'monthly'},{...raw,next_charge_scheduled_at:'2026-02-30'},{...raw,order_interval_frequency:'1'},{...raw,next_charge_scheduled_at:undefined}])('rejects an undocumented subscription field instead of guessing',async value=>{read.mockResolvedValueOnce(Response.json({subscription:value}));await expect(client().subscription(current)).rejects.toMatchObject({code:'unavailable'});});
 it.each([{id:112},{customer_id:23},{address_id:34}])('rechecks subscription/customer/address tuple',async patch=>{read.mockResolvedValueOnce(Response.json({subscription:{...raw,...patch}}));await expect(client().subscription(current)).rejects.toMatchObject({code:'notAllowed'});});
 it('projects the camelCase delivery envelope and individual skip state',async()=>{
  read.mockResolvedValueOnce(Response.json({deliverySchedule:{customer:{id:22,email:'private@example.invalid'},deliveries:[{date:'2026-10-20',orders:[{address_id:33,charge_id:66,line_items:[{subscription_id:111,is_skipped:false,is_skippable:true,is_prepaid:false},{subscription_id:112,is_skipped:false,is_skippable:true,is_prepaid:false}]}]}]}}));expect(await client().deliveries(22)).toEqual(deliveries);
 });
 it.each([{delivery_schedule:{customer:{id:22},deliveries:[]}},{deliverySchedule:{customer:{id:23},deliveries:[]}}])('rejects undocumented or wrong-customer schedule',async value=>{read.mockResolvedValueOnce(Response.json(value));await expect(client().deliveries(22)).rejects.toThrow();});
 it('reads charges with purchase item identity, not a guessed subscription_id',async()=>{read.mockResolvedValueOnce(Response.json({charge}));const result=await client().charge(66,current);expect(result.lines).toEqual([{itemId:111,type:'subscription',quantity:2},{itemId:112,type:'subscription',quantity:1}]);expect(JSON.stringify(result)).not.toContain('private@example');});
 it.each([{...charge,id:67},{...charge,customer:{id:23}},{...charge,address_id:34},{...charge,line_items:[{purchase_item_id:111,purchase_item_type:'onetime',quantity:1}]}])('rejects a charge not bound to this exact subscription',async value=>{read.mockResolvedValueOnce(Response.json({charge:value}));await expect(client().charge(66,current)).rejects.toMatchObject({code:'notAllowed'});});
 it.each([
  [{type:'quantity',quantity:3},'PUT','/subscriptions/111',{quantity:3}],
  [{type:'cadence',unit:'week',orderFrequency:2,chargeFrequency:4},'PUT','/subscriptions/111',{order_interval_unit:'week',order_interval_frequency:2,charge_interval_frequency:4}],
  [{type:'date',date:'2026-11-20'},'POST','/subscriptions/111/set_next_charge_date',{date:'2026-11-20'}],
  [{type:'cancel',reason:'Customer requested',comments:'Reviewed'},'POST','/subscriptions/111/cancel',{cancellation_reason:'Customer requested',cancellation_reason_comments:'Reviewed',send_email:false}],
 ] as const)('sends the exact selected mutation after one durable authorization',async(change,method,path,body)=>{
  read.mockResolvedValueOnce(Response.json({subscription:raw}));expect(await client().change(current,change,authorize)).toMatchObject({providerAccepted:true,subscription:current});expect(authorize).toHaveBeenCalledOnce();expect(read).toHaveBeenCalledOnce();expect(new URL(String(read.mock.calls[0][0])).pathname).toBe(path);expect(read.mock.calls[0][1]?.method).toBe(method);expect(JSON.parse(String(read.mock.calls[0][1]?.body))).toEqual(body);
 });
 it('activates only a canceled subscription with an explicit empty body',async()=>{read.mockResolvedValueOnce(Response.json({subscription:raw}));await client().change({...current,status:'cancelled'},{type:'activate'},authorize);expect(new URL(String(read.mock.calls[0][0])).pathname).toBe('/subscriptions/111/activate');expect(read.mock.calls[0][1]?.body).toBe('{}');});
 it('denied durable authority causes no provider request',async()=>{authorize.mockResolvedValue(false);await expect(client().change(current,{type:'cancel',reason:'Customer requested',comments:''},authorize)).rejects.toMatchObject({code:'notAllowed'});expect(read).not.toHaveBeenCalled();});
 it.each([{type:'quantity',quantity:2},{type:'date',date:'2026-10-20'},{type:'cadence',unit:'month',orderFrequency:1,chargeFrequency:1}])('rejects an unchanged mutation before claiming',async value=>{await expect(client().change(current,value,authorize)).rejects.toMatchObject({code:'invalid'});expect(authorize).not.toHaveBeenCalled();expect(read).not.toHaveBeenCalled();});
 it('rejects an activation of an already active subscription',async()=>{await expect(client().change(current,{type:'activate'},authorize)).rejects.toMatchObject({code:'notAllowed'});expect(authorize).not.toHaveBeenCalled();});
 it.each([()=>Promise.reject(new Error('PRIVATE_SECRET')),()=>Promise.resolve(Response.json({subscription:{...raw,id:999}})),()=>Promise.resolve(Response.json({subscription:raw},{status:202})),()=>Promise.resolve(Response.json({accepted:true}))])('keeps any unresolved write uncertain with no transport retry',async response=>{read.mockImplementation(response);await expect(client().change(current,{type:'quantity',quantity:3},authorize)).rejects.toMatchObject({code:'uncertain'});expect(read).toHaveBeenCalledOnce();});
 it('skips only the selected purchase item, preserving a multiitem charge request',async()=>{read.mockResolvedValueOnce(Response.json({charge}));await client().skip(current,{id:66,customerId:22,addressId:33,scheduledAt:'2026-10-20',status:'queued',hasUncommittedChanges:false,lines:[{itemId:111,type:'subscription',quantity:2},{itemId:112,type:'subscription',quantity:1}]},skip,authorize);expect(JSON.parse(String(read.mock.calls[0][1]?.body))).toEqual({purchase_item_ids:[111]});expect(new URL(String(read.mock.calls[0][0])).pathname).toBe('/charges/66/skip');});
 it.each([{isPrepaid:true},{isSkippable:false},{status:'cancelled' as const}])('refuses a non-skippable/prepaid/inactive subscription',async patch=>{await expect(client().skip({...current,...patch},{id:66,customerId:22,addressId:33,scheduledAt:'2026-10-20',status:'queued',hasUncommittedChanges:false,lines:[{itemId:111,type:'subscription',quantity:2}]},skip,authorize)).rejects.toMatchObject({code:'notAllowed'});expect(authorize).not.toHaveBeenCalled();expect(read).not.toHaveBeenCalled();});
});
describe('reviewed changes and readback observations',()=>{
 it.each(['2026-02-30','2026-13-01','2026-00-01','2026-10-20T00:00:00Z'])('rejects invalid action date %s',value=>expect(subscriptionDate.safeParse(value).success).toBe(false));
 it.each(['2024-02-29','2026-10-20'])('accepts real calendar date %s',value=>expect(subscriptionDate.safeParse(value).success).toBe(true));
 it.each([{type:'cancel',reason:'<script>',comments:''},{type:'cancel',reason:'\ud800',comments:''},{type:'cancel',reason:'Customer',comments:'x'.repeat(1025)},{type:'date',date:'2026-10-20',send_email:true},{type:'quantity',quantity:1.5}])('rejects modified or invalid approval payload',value=>expect(subscriptionChange.safeParse(value).success).toBe(false));
 it('does not interpret updated_at or HTTP acceptance as the desired quantity/date',()=>{expect(subscriptionChangeObserved({type:'quantity',quantity:3},current,{...current,updatedAt:'2026-10-03T10:00:00Z'})).toBe(false);expect(subscriptionChangeObserved({type:'date',date:'2026-11-20'},current,{...current,updatedAt:'2026-10-03T10:00:00Z'})).toBe(false);});
 it('requires both the desired state and unchanged identity',()=>{expect(subscriptionChangeObserved({type:'quantity',quantity:3},current,{...current,quantity:3})).toBe(true);expect(subscriptionChangeObserved({type:'quantity',quantity:3},current,{...current,id:112,quantity:3})).toBe(false);});
 it('compares cadence values without inventing one fixed response type',()=>expect(subscriptionChangeObserved({type:'cadence',unit:'month',orderFrequency:1,chargeFrequency:2},current,{...current,chargeIntervalFrequency:'2'})).toBe(true));
 it('matches cancellation reason and comments for the exact subscription',()=>{const change={type:'cancel' as const,reason:'Customer requested',comments:'Reviewed'};expect(subscriptionChangeObserved(change,current,{...current,status:'cancelled',cancellationReason:change.reason,cancellationComments:change.comments})).toBe(true);expect(subscriptionChangeObserved(change,current,{...current,status:'cancelled'})).toBe(false);});
 it('requires the target delivery item to be skipped and all other items preserved',()=>{const after=structuredClone(deliveries);after[0].lines[0].isSkipped=true;expect(subscriptionSkipObserved(skip,current,deliveries,after)).toBe(true);after[0].lines[1].isSkipped=true;expect(subscriptionSkipObserved(skip,current,deliveries,after)).toBe(false);});
 it('does not use a different charge/date/address or missing item as skip evidence',()=>{for(const patch of [{chargeId:67},{addressId:34},{date:'2026-10-21'},{lines:[]}]){const after=structuredClone(deliveries);Object.assign(after[0],patch);expect(subscriptionSkipObserved(skip,current,deliveries,after)).toBe(false);}});
});
