import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {afterAll,beforeAll,beforeEach,describe,expect,it} from 'vitest';
const db=new PGlite(),ws='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',connection='33333333-3333-4333-8333-333333333333',other='44444444-4444-4444-8444-444444444444',attempt='55555555-5555-4555-8555-555555555555',shop='66666666-6666-4666-8666-666666666666',nonce='77777777-7777-4777-8777-777777777777',revision='88888888-8888-4888-8888-888888888888',domain='fixture-store.myshopify.com',snapshot='a'.repeat(64);
const scalar=async(sql:string,args:unknown[]=[])=>Object.values((await db.query<Record<string,unknown>>(sql,args)).rows[0])[0];
const projection={id:100,title:'Fixture title',body:'Untrusted review text',rating:4,hidden:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),productExternalId:123,productTitle:'Fixture product',snapshot};
const save=(enabled=true,daily=50,who=actor)=>scalar('SELECT set_native_reviews_settings($1,$2,$3,$4,$5,$6,$7,$8,$9)',[ws,who,connection,shop,domain,revision,'a'.repeat(80),enabled,daily]);
const cache=(rows:unknown=[projection],who=actor)=>scalar('SELECT cache_native_store_reviews($1,$2,$3,$4,$5)',[ws,who,connection,revision,rows]);
const review=(values:Partial<{id:string;who:string;content:string;publication:boolean;hash:string;reviewId:number}>={})=>{const p={id:attempt,who:actor,content:'Reviewed public fixture reply',publication:true,hash:snapshot,reviewId:100,...values};return scalar('SELECT review_native_store_reply($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[ws,p.who,p.id,connection,revision,p.reviewId,p.hash,p.content,p.publication,nonce]);};
const claim=()=>scalar('SELECT claim_native_store_reply($1,$2)',[attempt,nonce]);
const finish=(outcome='accepted')=>scalar('SELECT finish_native_store_reply($1,$2,$3)',[attempt,nonce,outcome]);
const receipt=(who=actor)=>scalar('SELECT native_review_reply_receipt($1,$2,$3)',[ws,who,attempt]);
beforeAll(async()=>{
 await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY);
 CREATE TABLE workspaces(id uuid PRIMARY KEY,owner_id uuid,deleted_at timestamptz,writable boolean DEFAULT true);CREATE TABLE workspace_members(workspace_id uuid,user_id uuid,role text,allowed_sections jsonb);
 CREATE TABLE shopify_connections(id uuid PRIMARY KEY,workspace_id uuid,shop_domain text,status text,platform text);
 CREATE FUNCTION workspace_billing_write_allowed(ws uuid) RETURNS boolean LANGUAGE sql AS $$SELECT writable FROM public.workspaces WHERE id=ws$$;
 GRANT USAGE ON SCHEMA public TO anon,authenticated,service_role;`);
 await db.exec(readFileSync('supabase/migrations/373_native_store_reviews.sql','utf8'));
},30000);
afterAll(async()=>{await db.close();});
beforeEach(async()=>{
 await db.exec('RESET ROLE;TRUNCATE native_review_replies,native_store_reviews,native_review_settings,shopify_connections,workspace_members,workspaces,auth.users CASCADE');
 await db.query('INSERT INTO auth.users VALUES($1),($2)',[actor,other]);await db.query('INSERT INTO workspaces(id,owner_id) VALUES($1,$2),($3,$3)',[ws,actor,other]);
 await db.query("INSERT INTO shopify_connections VALUES($1,$2,$3,'active','shopify'),($4,$4,'other-store.myshopify.com','active','shopify')",[shop,ws,domain,other]);
});
describe('Native store review publication authority, local database only',()=>{
 it('keeps keys, cached reviews and publication functions private from browser roles and direct service-role table reads',async()=>{
  for(const role of ['anon','authenticated','service_role'])expect(await scalar(`SELECT has_table_privilege('${role}','native_review_settings','SELECT')`)).toBe(false);
  for(const role of ['anon','authenticated'])expect(await scalar(`SELECT has_function_privilege('${role}','claim_native_store_reply(uuid,uuid)','EXECUTE')`)).toBe(false);
  await db.exec('SET ROLE service_role');expect(await scalar('SELECT native_store_reviews_ready()')).toBe(true);await db.exec('RESET ROLE');
 });
 it('projects current selected stores and settings without returning encrypted credentials',async()=>{const result=await save();expect(result).toMatchObject({shopDomain:domain,enabled:true,stores:[{id:shop,shopDomain:domain}]});expect(JSON.stringify(result)).not.toContain('a'.repeat(80));});
 it('fails the deployment probe if a cache table or publication function becomes browser-accessible',async()=>{await db.exec('GRANT SELECT ON native_store_reviews TO anon');expect(await scalar('SELECT native_store_reviews_ready()')).toBe(false);await db.exec('REVOKE SELECT ON native_store_reviews FROM anon;GRANT EXECUTE ON FUNCTION finish_native_store_reply(uuid,uuid,text) TO authenticated');expect(await scalar('SELECT native_store_reviews_ready()')).toBe(false);await db.exec('REVOKE EXECUTE ON FUNCTION finish_native_store_reply(uuid,uuid,text) FROM authenticated');expect(await scalar('SELECT native_store_reviews_ready()')).toBe(true);});
 it('requires current settings admin and section permission; null actor/section are never allowed',async()=>{await expect(save(true,50,other)).rejects.toThrow('expansion_not_allowed');await db.query("INSERT INTO workspace_members VALUES($1,$2,'agent','[\"/ajustes\"]')",[ws,other]);await expect(save(true,50,other)).rejects.toThrow('expansion_not_allowed');expect(await scalar('SELECT native_review_actor($1,$2,NULL,false)',[ws,actor])).toBe(false);});
 it('binds the installation to the exact active Shopify connection and rejects another workspace/domain',async()=>{await expect(scalar('SELECT set_native_reviews_settings($1,$2,$3,$4,$5,$6,$7,true,50)',[ws,actor,connection,other,'other-store.myshopify.com',revision,'a'.repeat(80)])).rejects.toThrow('expansion_not_allowed');await save();await expect(scalar('SELECT set_native_reviews_settings($1,$2,$3,$4,$5,$6,$7,true,50)',[ws,actor,connection,shop,'other-store.myshopify.com',revision,'a'.repeat(80)])).rejects.toThrow('expansion_changed');});
 it('can disable after uninstall or read-only billing without reading reviews or publishing',async()=>{await save();await db.exec("UPDATE workspaces SET writable=false;UPDATE shopify_connections SET status='uninstalled'");expect(await save(false)).toMatchObject({enabled:false});await expect(cache()).rejects.toThrow('expansion_not_allowed');});
 it('rejects reviewer PII/raw unknown fields and duplicate provider IDs before storing any page',async()=>{await save();for(const rows of [[{...projection,email:'private@example.invalid'}],[projection,projection],[{...projection,hidden:'false'}],[{...projection,rating:10}],[{...projection,id:1.5}]])await expect(cache(rows)).rejects.toThrow('invalid_expansion');expect(await scalar('SELECT count(*) FROM native_store_reviews')).toBe(0);});
 it('does not expose review cache to a member without current Products access',async()=>{await save();await db.query("INSERT INTO workspace_members VALUES($1,$2,'agent','[\"/bandeja\"]')",[ws,other]);await expect(cache([projection],other)).rejects.toThrow('expansion_not_allowed');});
 it('claims one reviewed public reply, preserves creation acknowledgement without inventing publication or email proof',async()=>{await save();await cache();expect(await review()).toMatchObject({claimed:true});expect(await review()).toMatchObject({claimed:false});expect(await claim()).toBe(true);expect(await claim()).toBe(false);await finish();expect(await receipt()).toMatchObject({state:'accepted',providerConfirmedCreation:true,independentPublicationVerified:false,emailRequested:false});await expect(review({id:other,content:'Another reply'})).rejects.toThrow('expansion_changed');});
 it('requires explicit current storefront review and exact immutable content/snapshot',async()=>{await save();await cache();await expect(review({publication:false})).rejects.toThrow('invalid_expansion');await review();await expect(review({content:'Changed'})).rejects.toThrow('expansion_changed');await expect(review({hash:'b'.repeat(64)})).rejects.toThrow('expansion_changed');});
 it('never replies to a hidden, stale or unobserved review',async()=>{await save();await expect(review()).rejects.toThrow('expansion_changed');await cache([{...projection,hidden:true}]);await expect(review()).rejects.toThrow('expansion_changed');await cache();await expect(review({hash:'b'.repeat(64)})).rejects.toThrow('expansion_changed');});
 it.each(['actor','billing','shop','revision','snapshot','hidden','paused','expired'] as const)('rechecks %s immediately before one provider publication',async reason=>{
  await save();await cache();await review();if(reason==='actor')await db.query('UPDATE workspaces SET owner_id=$1',[other]);if(reason==='billing')await db.exec('UPDATE workspaces SET writable=false');if(reason==='shop')await db.exec("UPDATE shopify_connections SET status='uninstalled'");if(reason==='revision')await db.query('UPDATE native_review_settings SET revision=$1',[other]);if(reason==='snapshot')await cache([{...projection,snapshot:'b'.repeat(64)}]);if(reason==='hidden')await cache([{...projection,hidden:true}]);if(reason==='paused')await save(false);if(reason==='expired')await db.exec("UPDATE native_review_replies SET created_at=clock_timestamp()-interval '4 minutes'");expect(await claim()).toBe(false);
 });
 it('never turns an uncertain claimed publication into cancellation or another reply',async()=>{await save();await cache();await review();await claim();await finish('uncertain');await expect(finish('canceled')).rejects.toThrow('expansion_changed');await expect(review({id:other})).rejects.toThrow('expansion_changed');});
 it('expires only a provably unclaimed review on receipt recovery and preserves claimed uncertainty',async()=>{await save();await cache();await review();await db.exec("UPDATE native_review_replies SET created_at=clock_timestamp()-interval '4 minutes'");expect(await receipt()).toMatchObject({state:'canceled'});await review({id:other});await scalar('SELECT claim_native_store_reply($1,$2)',[other,nonce]);await db.exec("UPDATE native_review_replies SET claimed_at=clock_timestamp()-interval '4 minutes' WHERE state='dispatching'");expect(await scalar('SELECT native_review_reply_receipt($1,$2,$3)',[ws,actor,other])).toMatchObject({state:'uncertain'});});
 it('records a late known creation acknowledgement under the same claimed nonce without another publication or independent visibility proof',async()=>{await save();await cache();await review();await claim();await finish('uncertain');expect(await finish('accepted')).toBe(true);expect(await receipt()).toMatchObject({state:'accepted',providerConfirmedCreation:true,independentPublicationVerified:false});});
 it('allows a fresh review only after a proven pre-publication cancellation',async()=>{await save();await cache();await review();await finish('canceled');expect(await claim()).toBe(false);expect(await review({id:other})).toMatchObject({claimed:true});});
 it('counts reviewed/uncertain/accepted attempts toward the daily limit',async()=>{await save(true,1);await cache([projection,{...projection,id:101}]);await review();await claim();await finish('uncertain');await expect(review({id:other,reviewId:101})).rejects.toThrow('expansion_limit');});
 it('keeps receipts actor-bound even when another current member can view Products',async()=>{await save();await cache();await review();await db.query("INSERT INTO workspace_members VALUES($1,$2,'agent','[\"/productos\"]')",[ws,other]);expect(await receipt(other)).toBeNull();});
 it('retains dispatch uncertainty and clears deleted tenant keys only after grace, in the local fixture',async()=>{await save();await cache();await review();await claim();await db.exec("UPDATE native_review_replies SET claimed_at=clock_timestamp()-interval '4 minutes'");expect(await scalar('SELECT purge_native_store_reviews(30)')).toEqual({connections:0});expect(await receipt()).toMatchObject({state:'uncertain'});await db.exec("UPDATE workspaces SET deleted_at=clock_timestamp()-interval '40 days'");expect(await scalar('SELECT purge_native_store_reviews(30)')).toEqual({connections:1});expect(await scalar('SELECT count(*) FROM native_review_settings')).toBe(0);});
});
