import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {afterAll,beforeAll,beforeEach,describe,expect,it} from 'vitest';
const db=new PGlite(),ws='11111111-1111-4111-8111-111111111111',owner='22222222-2222-4222-8222-222222222222',connection='33333333-3333-4333-8333-333333333333',other='44444444-4444-4444-8444-444444444444',attempt='55555555-5555-4555-8555-555555555555',contact='66666666-6666-4666-8666-666666666666',nonce='77777777-7777-4777-8777-777777777777',conversation='88888888-8888-4888-8888-888888888888',revision='99999999-9999-4999-8999-999999999999',profile='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',organization='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',messageId='cccccccc-cccc-4ccc-8ccc-cccccccccccc',eventId='dddddddd-dddd-4ddd-8ddd-dddddddddddd',peer='+573001234567',phone='+12025550100';
const identity={phoneNumberId:'1293384261075731499',phone,profileId:profile,organizationId:organization};
const scalar=async(sql:string,args:unknown[]=[])=>Object.values((await db.query<Record<string,unknown>>(sql,args)).rows[0])[0];
const save=(values:Partial<{workspace:string;actor:string;connection:string;revision:string;identity:typeof identity;enabled:boolean;daily:number}>={})=>{const p={workspace:ws,actor:owner,connection,revision,identity,enabled:true,daily:100,...values};return scalar('SELECT set_native_sms_settings($1,$2,$3,$4,$5,$6,$7,$8,3,$9)',[p.workspace,p.actor,p.connection,p.revision,p.identity,'a'.repeat(80),'A'.repeat(43)+'=',p.enabled,p.daily]);};
const consent=(allowed=true,actor=owner)=>scalar('SELECT native_sms_consent($1,$2,$3,$4,$5,$6)',[ws,actor,connection,peer,allowed,'Customer requested SMS; fixture evidence only']);
const review=(values:Partial<{id:string;actor:string;workspace:string;revision:string;contact:string;conversation:string;peer:string;body:string;segments:number}>={})=>{const p={id:attempt,actor:owner,workspace:ws,revision,contact,conversation,peer,body:'Fixture message',segments:1,...values};return scalar('SELECT review_native_sms_send($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[p.workspace,p.actor,p.id,connection,p.conversation,p.contact,p.revision,p.peer,p.body,p.segments,nonce]);};
const claim=()=>scalar('SELECT claim_native_sms_send($1,$2)',[attempt,nonce]);
const finish=(outcome='accepted')=>scalar('SELECT finish_native_sms_send($1,$2,$3,$4,$5,$6,$7)',[attempt,nonce,outcome,outcome==='accepted'?messageId:null,outcome==='accepted'?'queued':null,outcome==='accepted'?1:null,null]);
const receipt=(actor=owner)=>scalar('SELECT native_sms_receipt($1,$2,$3)',[ws,actor,attempt]);
const event=(values:Partial<{eventId:string;eventType:string;occurredAt:string;messageId:string;organizationId:string;profileId:string;direction:string;businessPhone:string;peer:string;text:string;status:string|null;optOutAction:string|null;parts:number|null;cost:unknown}>={})=>({eventId,eventType:'message.received',occurredAt:new Date().toISOString(),messageId,organizationId:organization,profileId:profile,direction:'inbound',businessPhone:phone,peer,text:'Fixture inbound',status:null,optOutAction:null,parts:1,cost:null,...values});
const enqueue=(value=event())=>scalar('SELECT enqueue_native_sms_event($1,$2)',[connection,value]);
beforeAll(async()=>{
 await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY);
 CREATE TABLE workspaces(id uuid PRIMARY KEY,owner_id uuid,deleted_at timestamptz,writable boolean DEFAULT true);CREATE TABLE workspace_members(workspace_id uuid,user_id uuid,role text,allowed_sections jsonb);
 CREATE TABLE channel_connections(id uuid PRIMARY KEY,workspace_id uuid,channel text,label text,status text,external_account_id text,config jsonb,secrets jsonb,created_by uuid,updated_at timestamptz DEFAULT clock_timestamp());
 CREATE TABLE contacts(id uuid PRIMARY KEY,workspace_id uuid,channel text,external_id text);
 CREATE TABLE conversations(id uuid PRIMARY KEY,workspace_id uuid,contact_id uuid,connection_id uuid,channel text,deleted_at timestamptz,is_spam boolean DEFAULT false,last_message_text text,last_message_at timestamptz,last_sender_type text,last_message_status text);
 CREATE TABLE messages(conversation_id uuid,channel text,sender_type text,sender_id uuid,content_type text,content_text text,message_id text,status text,created_at timestamptz,delivery_unconfirmed_at timestamptz,UNIQUE(conversation_id,message_id));CREATE FUNCTION workspace_billing_write_allowed(ws uuid) RETURNS boolean LANGUAGE sql AS $$SELECT writable FROM public.workspaces WHERE id=ws$$;
 GRANT USAGE ON SCHEMA public TO anon,authenticated,service_role;`);
 await db.exec(readFileSync('supabase/migrations/372_native_sms_authority.sql','utf8'));
},30000);
afterAll(async()=>{await db.close();});
beforeEach(async()=>{
 await db.exec('RESET ROLE;TRUNCATE native_sms_events,native_sms_attempts,native_sms_consents,native_sms_settings,messages,conversations,contacts,channel_connections,workspace_members,workspaces,auth.users CASCADE');
 await db.query('INSERT INTO auth.users VALUES($1),($2)',[owner,other]);await db.query('INSERT INTO workspaces(id,owner_id) VALUES($1,$2),($3,$3)',[ws,owner,other]);
 await db.query("INSERT INTO contacts VALUES($1,$2,'sms',$3)",[contact,ws,peer]);await db.query("INSERT INTO conversations(id,workspace_id,contact_id,connection_id,channel) VALUES($1,$2,$3,$4,'sms')",[conversation,ws,contact,connection]);
});
describe('Durable native SMS authority, local database only',()=>{
 it('keeps all private control tables and mutation functions inaccessible to browser roles',async()=>{
  for(const role of ['anon','authenticated']){expect(await scalar(`SELECT has_table_privilege('${role}','native_sms_settings','SELECT')`)).toBe(false);expect(await scalar(`SELECT has_function_privilege('${role}','claim_native_sms_send(uuid,uuid)','EXECUTE')`)).toBe(false);}
  await db.exec('SET ROLE service_role');expect(await scalar('SELECT native_sms_ready()')).toBe(true);await db.exec('RESET ROLE');
 });
 it('stores only display metadata on the ordinary channel row; settings output never returns credentials',async()=>{
  const result=await save();expect(result).toMatchObject({phone,enabled:true,connectionId:connection});expect(JSON.stringify(result)).not.toContain('a'.repeat(80));
  expect(await scalar('SELECT secrets FROM channel_connections')).toEqual({});expect(await scalar('SELECT config FROM channel_connections')).toEqual({phone,native_sms:true});
 });
 it('requires current admin and section access to configure a number',async()=>{
  await expect(save({actor:other})).rejects.toThrow('expansion_not_allowed');await db.query("INSERT INTO workspace_members VALUES($1,$2,'agent','[\"/ajustes\"]')",[ws,other]);await expect(save({actor:other})).rejects.toThrow('expansion_not_allowed');
  await db.exec("UPDATE workspace_members SET role='admin',allowed_sections='[\"/bandeja\"]'");await expect(save({actor:other})).rejects.toThrow('expansion_not_allowed');
 });
 it('never binds a profile/phone to two workspaces or changes installed provider identity',async()=>{
  await save();await expect(save({workspace:other,actor:other,connection:other})).rejects.toThrow('expansion_not_allowed');await expect(save({identity:{...identity,phone:'+12025550111'}})).rejects.toThrow('expansion_changed');
 });
 it('has no implicit consent from an incoming conversation or phone',async()=>{await save();expect(await scalar('SELECT native_sms_peer_policy($1,$2,$3,$4)',[ws,owner,connection,peer])).toMatchObject({consent:false});await expect(review()).rejects.toThrow('expansion_not_allowed');});
 it('reports a disconnected number as unavailable even if its private installation remains enabled',async()=>{await save();await consent();await db.exec("UPDATE channel_connections SET status='disconnected'");expect(await scalar('SELECT native_sms_peer_policy($1,$2,$3,$4)',[ws,owner,connection,peer])).toMatchObject({enabled:false,consent:true});expect(await scalar('SELECT native_sms_settings_read($1,$2)',[ws,owner])).toMatchObject({enabled:false});});
 it('claims exactly one provider POST and recovers the same reviewed payload locally',async()=>{
  await save();await consent();expect(await review()).toMatchObject({claimed:true});expect(await review()).toMatchObject({claimed:false,receipt:{state:'reviewed'}});expect(await claim()).toBe(true);expect(await claim()).toBe(false);
  await finish();expect(await receipt()).toMatchObject({state:'accepted',providerStatus:'queued',deliveryConfirmed:false,cost:null});expect(await review()).toMatchObject({claimed:false,receipt:{state:'accepted'}});
  expect(await scalar('SELECT count(*) FROM messages')).toBe(1);expect(await scalar('SELECT status FROM messages')).toBe('sending');
 });
 it('rejects changed payload or another actor on the same attempt',async()=>{await save();await consent();await review();await expect(review({body:'Changed'})).rejects.toThrow('expansion_changed');await expect(receipt(other)).rejects.toThrow('expansion_not_allowed');await db.query("INSERT INTO workspace_members VALUES($1,$2,'agent','[\"/bandeja\"]')",[ws,other]);expect(await receipt(other)).toBeNull();});
 it('blocks a second attempt to the same peer after an uncertain or dispatching send',async()=>{await save();await consent();await review();await claim();await expect(review({id:other,body:'A second message'})).rejects.toThrow('expansion_changed');await finish('uncertain');await expect(review({id:other})).rejects.toThrow('expansion_changed');expect(await claim()).toBe(false);});
 it('cancels only before a provider operation has been claimed',async()=>{await save();await consent();await review();await finish('canceled');expect(await claim()).toBe(false);await review({id:other});await scalar('SELECT claim_native_sms_send($1,$2)',[other,nonce]);await expect(scalar('SELECT finish_native_sms_send($1,$2,$3)',[other,nonce,'canceled'])).rejects.toThrow('expansion_changed');});
 it.each(['consent','revision','billing','connection','spam','contact','actor'] as const)('rechecks %s just before the one send',async kind=>{
  await save();await consent();await review();if(kind==='consent')await consent(false);if(kind==='revision')await save({revision:other});if(kind==='billing')await db.exec('UPDATE workspaces SET writable=false');if(kind==='connection')await db.exec("UPDATE channel_connections SET status='disconnected'");if(kind==='spam')await db.exec('UPDATE conversations SET is_spam=true');if(kind==='contact')await db.exec("UPDATE contacts SET external_id='+573001234568'");if(kind==='actor')await db.query('UPDATE workspaces SET owner_id=$1',[other]);expect(await claim()).toBe(false);
 });
 it('counts reviewed, dispatching and uncertain segments toward the UTC daily cap',async()=>{await save({daily:1});await consent();await review();await claim();await finish('uncertain');await db.query("INSERT INTO contacts VALUES($1,$2,'sms','+573001234568')",[other,ws]);await db.query("UPDATE conversations SET contact_id=$1",[other]);await scalar('SELECT native_sms_consent($1,$2,$3,$4,true,$5)',[ws,owner,connection,'+573001234568','Fixture consent']);await expect(review({id:other,contact:other,peer:'+573001234568'})).rejects.toThrow('expansion_limit');});
 it('persists signed event IDs once and refuses a conflicting duplicate',async()=>{await save();const value=event();expect(await enqueue(value)).toBe(true);expect(await enqueue(value)).toBe(false);await expect(enqueue({...value,text:'Different event'})).rejects.toThrow('expansion_changed');});
 it('does not let a webhook for another account/profile/business number touch a workspace',async()=>{await save();for(const value of [{organizationId:other},{profileId:other},{businessPhone:'+12025550111'}])await expect(enqueue(event(value))).rejects.toThrow('expansion_not_allowed');expect(await scalar('SELECT count(*) FROM native_sms_events')).toBe(0);});
 it('applies STOP immediately and does not let an older START reopen sending',async()=>{
  await save();await consent();await review();const stopTime=new Date(Date.now()+1000).toISOString();await enqueue(event({optOutAction:'STOP',occurredAt:stopTime}));expect(await claim()).toBe(false);
  await enqueue(event({eventId:other,optOutAction:'START',occurredAt:new Date(Date.now()-1000).toISOString()}));expect(await scalar('SELECT allowed FROM native_sms_consents')).toBe(false);
 });
 it('leases only inbound inbox work and makes a duplicate claim a no-op',async()=>{await save();await enqueue();expect(await scalar('SELECT claim_native_sms_events($1,20)',[nonce])).toMatchObject([{event_id:eventId,connection_id:connection}]);expect(await scalar('SELECT claim_native_sms_events($1,20)',[other])).toEqual([]);expect(await scalar('SELECT finish_native_sms_event($1,$2,true)',[eventId,other])).toBe(false);expect(await scalar('SELECT finish_native_sms_event($1,$2,true)',[eventId,nonce])).toBe(true);});
 it('keeps delivered proof after out-of-order sent events, including a callback before POST acknowledgement',async()=>{
  await save();await consent();await review();await claim();await enqueue(event({eventType:'message.finalized',direction:'outbound',status:'delivered',cost:{amount:'0.0123',currency:'USD'}}));await finish();expect(await receipt()).toMatchObject({providerStatus:'delivered',deliveryConfirmed:true,cost:{amount:'0.0123',currency:'USD'}});
  await enqueue(event({eventId:other,eventType:'message.sent',direction:'outbound',status:'sent',occurredAt:new Date(Date.now()+1000).toISOString()}));expect(await receipt()).toMatchObject({providerStatus:'delivered',deliveryConfirmed:true});
  expect(await scalar('SELECT count(*) FROM messages')).toBe(1);expect(await scalar('SELECT status FROM messages')).toBe('delivered');
 });
 it('does not associate an uncertain attempt with a guessed peer/text callback',async()=>{await save();await consent();await review();await claim();await finish('uncertain');await enqueue(event({eventType:'message.finalized',direction:'outbound',status:'delivered',text:'Fixture message'}));expect(await receipt()).toMatchObject({state:'uncertain',providerStatus:null,deliveryConfirmed:false});});
 it('retains pending inbound events during a pause or soft workspace deletion',async()=>{await save();await enqueue();await save({enabled:false});expect(await scalar('SELECT claim_native_sms_events($1,20)',[nonce])).toEqual([]);await save();await db.exec('UPDATE workspaces SET deleted_at=clock_timestamp()');expect(await scalar('SELECT claim_native_sms_events($1,20)',[nonce])).toEqual([]);expect(await scalar('SELECT count(*) FROM native_sms_events')).toBe(1);await expect(enqueue(event({eventId:other}))).rejects.toThrow('expansion_not_allowed');});
 it('lets only a current installation admin retry failed inbox ingestion, never a provider send',async()=>{await save();await enqueue();await db.exec("UPDATE native_sms_events SET state='failed',attempts=5");await expect(scalar('SELECT retry_native_sms_inbox($1,$2,$3)',[ws,other,connection])).rejects.toThrow('expansion_not_allowed');expect(await scalar('SELECT retry_native_sms_inbox($1,$2,$3)',[ws,owner,connection])).toBe(1);expect(await scalar('SELECT state FROM native_sms_events')).toBe('pending');expect(await scalar('SELECT count(*) FROM native_sms_attempts')).toBe(0);});
 it('supports hard contact/conversation deletion without a new foreign-key purge blockage',async()=>{await save();await consent();await review();await claim();await finish();await db.query('DELETE FROM contacts WHERE id=$1',[contact]);expect(await scalar('SELECT count(*) FROM native_sms_attempts')).toBe(0);});
 it('purges only expired processed event copies and grace-expired deleted tenant keys, locally',async()=>{
  await save();await enqueue();await db.exec("UPDATE native_sms_events SET created_at=clock_timestamp()-interval '40 days'");expect(await scalar('SELECT purge_native_sms_control(30)')).toEqual({connections:0,events:0});await db.exec("UPDATE native_sms_events SET state='done'");expect(await scalar('SELECT purge_native_sms_control(30)')).toEqual({connections:0,events:1});
  await consent();await db.exec("UPDATE workspaces SET deleted_at=clock_timestamp()-interval '40 days'");expect(await scalar('SELECT purge_native_sms_control(30)')).toEqual({connections:1,events:0});expect(await scalar('SELECT count(*) FROM native_sms_consents')).toBe(0);expect(await scalar('SELECT count(*) FROM native_sms_settings')).toBe(0);
 });
});
