import {generateKeyPairSync,sign} from 'node:crypto';
import {describe,expect,it} from 'vitest';
import {verifyTelnyxSmsEvent} from './sms-webhook';
const key=generateKeyPairSync('ed25519'),publicKey=(key.publicKey.export({format:'der',type:'spki'}) as Buffer).subarray(-32).toString('base64'),now=Date.parse('2026-10-02T12:00:00Z'),timestamp=String(now/1000);
const message={data:{id:'11111111-1111-4111-8111-111111111111',event_type:'message.received',occurred_at:'2026-10-02T12:00:00Z',payload:{id:'22222222-2222-4222-8222-222222222222',type:'SMS',direction:'inbound',organization_id:'33333333-3333-4333-8333-333333333333',messaging_profile_id:'44444444-4444-4444-8444-444444444444',from:{phone_number:'+573001234567'},to:[{phone_number:'+12025550100'}],text:'STOP',autoresponse_type:'STOP'}}};
function fixture(input:unknown=message,stamp=timestamp){const raw=Buffer.from(JSON.stringify(input,null,2)+'\n'),signature=sign(null,Buffer.concat([Buffer.from(stamp+'|'),raw]),key.privateKey).toString('base64');return {raw,signature,stamp};}
function read(input:unknown=message){const {raw,signature,stamp}=fixture(input);return verifyTelnyxSmsEvent(raw,signature,stamp,publicKey,now);}
describe('SMS webhook signature and event boundary, local crypto only',()=>{
 it('verifies exact whitespace/newline bytes and preserves durable event/message/account coordinates',()=>{expect(read()).toMatchObject({eventId:message.data.id,messageId:message.data.payload.id,businessPhone:'+12025550100',peer:'+573001234567',direction:'inbound',optOutAction:'STOP',status:null});});
 it('rejects JSON reserialization even when its meaning is unchanged',()=>{const {signature}=fixture();expect(()=>verifyTelnyxSmsEvent(Buffer.from(JSON.stringify(message)),signature,timestamp,publicKey,now)).toThrow('expansion_provider_invalid');});
 it.each([now+300001,now-300001])('rejects a replay/future timestamp against clock %s',clock=>{const {raw,signature}=fixture();expect(()=>verifyTelnyxSmsEvent(raw,signature,timestamp,publicKey,clock)).toThrow('expansion_provider_invalid');});
 it('rejects a different account public key or malformed signature before parsing',()=>{const {raw,signature}=fixture();expect(()=>verifyTelnyxSmsEvent(raw,signature,timestamp,Buffer.alloc(32).toString('base64'),now)).toThrow('expansion_provider_invalid');expect(()=>verifyTelnyxSmsEvent(raw,'bad signature',timestamp,publicKey,now)).toThrow('expansion_provider_invalid');});
 it('keeps finalized queued/sent statuses distinct from delivery',()=>{const event={...message,data:{...message.data,event_type:'message.finalized',payload:{...message.data.payload,direction:'outbound',from:{phone_number:'+12025550100'},to:[{phone_number:'+573001234567',status:'sent'}]}}};expect(read(event)).toMatchObject({peer:'+573001234567',businessPhone:'+12025550100',status:'sent',optOutAction:null});});
 it('ignores unsupported event kinds and MMS without fabricating an SMS message',()=>{expect(read({...message,data:{...message.data,event_type:'call.initiated'}})).toBeNull();expect(read({...message,data:{...message.data,payload:{...message.data.payload,type:'MMS'}}})).toBeNull();});
 it('rejects inconsistent direction or unknown final status',()=>{expect(()=>read({...message,data:{...message.data,event_type:'message.finalized'}})).toThrow('expansion_provider_invalid');expect(()=>read({...message,data:{...message.data,event_type:'message.sent',payload:{...message.data.payload,direction:'outbound',to:[{phone_number:'+12025550100',status:'guessed-delivered'}]}}})).toThrow('expansion_provider_invalid');});
});
