// Riverz chat films v3. Deterministic, bilingual, and mascot-free.
import { mkdir, copyFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { landingV4 as messages } from '../../src/lib/i18n/messages/landingV4.ts';
const root = resolve(process.argv[2] || 'C:/tmp/riverz-chat-v3');
const assets = resolve(process.argv[3] || 'C:/tmp/riverz-ui-films');
const css = `
@font-face{font-family:Instrument;src:url('sans.ttf')}@font-face{font-family:Mono;src:url('mono.ttf')}
*{box-sizing:border-box}body{margin:0;font-family:Instrument,sans-serif;color:#12201f;background:#f3f0eb}
#film{position:relative;width:960px;height:720px;overflow:hidden;background:#f3f0eb}
.stage{position:absolute;inset:0}.panel{position:absolute;background:#fffdf9;border:1px solid #ddd6ca;border-radius:26px;box-shadow:0 22px 42px -30px #12201f70;overflow:hidden}
.backplate{position:absolute;left:176px;top:50px;width:620px;height:595px;border:1px solid #d9d2c5;border-radius:28px;background:#e9e5dc;transform:rotate(3deg)}
.head{display:flex;align-items:center;gap:14px;padding:22px 26px;border-bottom:1px solid #e6e0d5;height:90px}.avatar{width:44px;height:44px;display:grid;place-items:center;border-radius:14px;background:#12201f;color:#f7ff9e;font-size:25px;font-weight:600;flex-shrink:0}.name{font-size:24px;font-weight:600}.sub{font-size:17px;color:#53615d;margin-top:3px}.tag{font:14px Mono,monospace;letter-spacing:.5px;text-transform:uppercase}.badge{font-size:17px;padding:8px 12px;border-radius:30px;background:#f7ff9e;white-space:nowrap}.head>.badge{margin-left:auto}
.bubble{position:absolute;padding:19px 23px;max-width:88%;font-size:27px;line-height:1.3;border-radius:22px;background:#eee8dd}.in{border-bottom-left-radius:5px}.out{background:#f7ff9e;border-bottom-right-radius:5px}.small{font-size:22px;line-height:1.35}.muted{color:#53615d}.typing{position:absolute;display:flex;gap:7px;align-items:center;background:#f7ff9e;padding:19px 24px;border-radius:22px}.dot{width:8px;height:8px;background:#12201f;border-radius:50%}
.product{display:flex;gap:18px;align-items:center;padding:18px;background:#faf7f1;border:1px solid #e1dbcf;border-radius:18px}.bottle{position:relative;flex-shrink:0;width:58px;height:65px;border-radius:12px 12px 17px 17px;background:#233e36;box-shadow:inset 8px 0 0 #3c5c49}.bottle:before{content:'';position:absolute;width:28px;height:16px;left:15px;top:-12px;border-radius:4px;background:#12201f}.bottle:after{content:'';position:absolute;left:12px;top:26px;width:35px;height:21px;border-radius:3px;background:#e7debd}
.product strong{display:block;font-size:24px}.product span{display:block;font-size:18px;color:#53615d;margin-top:5px}.link{font-size:23px;padding:15px 19px;border-radius:30px;background:#12201f;color:#faf7f1;display:flex;justify-content:space-between;align-items:center}.finish{position:absolute;left:62px;right:62px;bottom:35px;display:flex;gap:15px;align-items:center;font-size:24px}.check{width:36px;height:36px;display:grid;place-items:center;border-radius:50%;background:#f7ff9e;flex-shrink:0;font-size:23px}.channel{position:absolute;border:1px solid #d9d2c5;background:#fffdf9;border-radius:30px;padding:12px 19px;font-size:19px;box-shadow:0 10px 20px -15px #12201f55}
.knowledge{position:absolute;width:240px;height:145px;border:1px solid #d9d2c5;border-radius:20px;background:#fffdf9;padding:22px;box-shadow:0 18px 30px -24px #12201f65}.knowledge strong{display:block;font-size:24px;margin:13px 0 7px}.knowledge .tag{font-size:13px}.knowledge .check{position:absolute;right:17px;top:17px;width:27px;height:27px;font-size:18px}.rail{position:absolute;height:3px;background:#cdbca0;transform-origin:left center}.signal{position:absolute;width:12px;height:12px;border-radius:50%;background:#6b7626}.rule{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:19px 0;border-bottom:1px solid #e2dbcf;font-size:22px}.approval{padding:22px;background:#eee8dd;border-radius:19px}.button{display:block;background:#12201f;color:#faf7f1;text-align:center;border-radius:30px;padding:14px;font-size:23px;margin-top:18px}.cursor{position:absolute;z-index:5;width:28px;height:36px;pointer-events:none}.cursor svg{width:100%;height:100%}.ripple{position:absolute;border:2px solid #6b7626;border-radius:50%;width:50px;height:50px;pointer-events:none}.receipt{padding:27px}.receipt h2{font-size:30px;line-height:1.15;margin:20px 0}.receipt .rule{font-size:20px}.step{position:absolute;top:560px;width:240px;text-align:center;font-size:19px}.step .check{margin:0 auto 12px}.timeline{position:absolute;top:576px;left:220px;width:500px;height:2px;background:#cdbca0;transform-origin:left center}.ticket{position:absolute;left:25px;right:25px;padding:20px;border:1px solid #ddd6ca;border-radius:18px;background:#faf7f1;font-size:22px}.ticket .sub{margin-top:10px}.ticket strong{font-size:23px}.ticket .badge{display:inline-block;margin-top:14px}.inbox-row{padding:20px 23px;border-bottom:1px solid #ddd6ca;font-size:22px}.inbox-row span{display:block;font-size:17px;margin-top:9px;color:#53615d}.lens{position:absolute;inset:0;border:2px solid #a2ae4a;border-radius:18px;pointer-events:none}
.order-thread{display:flex;flex-direction:column;gap:16px;padding:22px 25px}.order-thread .bubble{position:relative;left:auto!important;top:auto!important;width:auto!important;max-width:85%;padding:17px 20px}.order-thread .in{align-self:flex-start}.order-thread .out,.order-thread .link{align-self:flex-end}.order-thread .link{width:85%;min-height:58px}
`;
const arrow = '<svg viewBox="0 0 28 36" fill="none"><path d="M3 2v29l7-9 7 12 5-3-7-12 11-1L3 2Z" fill="#12201f" stroke="#fffdf9" stroke-width="2"/></svg>';
for (const lang of ['es', 'en']) for (const scene of ['conversation','context','permissions','order','results']) {
  const t = key => messages[key][lang];
  const head = (label, channel = 'WhatsApp') => `<div class="head"><div class="avatar">r</div><div><div class="name">${label}</div><div class="sub">${channel}</div></div></div>`;
  const product = `<div class="bottle"></div><div><strong>${t('uiFilmProduct')}</strong><span>${t('chatCreativeUnit')}</span></div>`;
  const bubble = (id, txt, x,y,w,reply=false) => `<div id="${id}" class="bubble ${reply?'out':'in'}" style="left:${x}px;top:${y}px;width:${w}px">${txt}</div>`;
  const enter = (id, at, x=0, y=16) => `tl.fromTo('${id}',{opacity:0,x:${x},y:${y},scale:.96},{opacity:1,x:0,y:0,scale:1,duration:.65,ease:'power3.out'},${at});`;
  const exit = (id, at) => `tl.to('${id}',{opacity:0,y:-12,duration:.3,ease:'power2.in'},${at});`;
  let content='', motion='', proof='';
  if(scene==='conversation') {
    content=`<div class="backplate"></div><div class="panel" id="chat" style="left:150px;top:64px;width:660px;height:575px">${head(t('motionAgent'))}${bubble('question',t('uiFilmQuestion'),25,118,465)}<div class="typing" id="typing" style="right:26px;top:222px"><i class="dot"></i><i class="dot"></i><i class="dot"></i></div>${bubble('answer',t('uiFilmAnswer'),83,214,548,true)}<div id="product" class="product" style="position:absolute;left:83px;top:324px;width:548px">${product}</div><div class="link" id="checkout" style="position:absolute;left:83px;top:435px;width:548px">${t('motionLink')}<span>↗</span></div></div>`;
    motion=enter('#chat',0)+enter('#question',.5,-24)+enter('#typing',1.6)+`tl.to('.dot',{y:-5,duration:.22,stagger:.08,yoyo:true,repeat:5},1.8);`+exit('#typing',3)+enter('#answer',3.3,24)+enter('#product',5.1,24)+enter('#checkout',6.6);
    proof='#answer';
  } else if(scene==='context') {
    content=`<div class="panel" style="left:80px;top:45px;width:800px;height:128px">${bubble('question',t('uiFilmQuestion'),24,24,660)}</div><div class="rail" id="rail" style="left:206px;top:335px;width:548px"></div><div class="knowledge" id="catalog" style="left:70px;top:219px"><span class="tag">${t('motionCatalog')}</span><strong>${t('uiFilmProduct')}</strong><span class="check">✓</span></div><div class="knowledge" id="stock" style="left:360px;top:245px"><span class="tag">${t('motionStock')}</span><strong>${t('chatCreativeStock')}</strong><span class="check">✓</span></div><div class="knowledge" id="shipping" style="left:650px;top:219px"><span class="tag">${t('motionDelivery')}</span><strong>${t('chatCreativeShipping')}</strong><span class="check">✓</span></div><div class="signal" id="signal" style="left:195px;top:329px"></div><div class="panel" id="answer-card" style="left:80px;top:440px;width:800px;height:178px">${bubble('answer',t('uiFilmAnswer'),24,24,748,true)}</div>`;
    motion=enter('#question',.2,-25)+`tl.fromTo('#rail',{scaleX:0},{scaleX:1,duration:2.2,ease:'power2.inOut'},1.3);`+enter('#catalog',1,-22)+enter('#stock',2.5)+enter('#shipping',4,22)+`tl.fromTo('#signal',{opacity:0,x:0},{opacity:1,x:548,duration:3.8,ease:'none'},1.4);`+exit('#signal',5.2)+enter('#answer-card',5.5,0,28);
    proof='#answer-card';
  } else if(scene==='permissions') {
    content=`<div class="panel" id="chat" style="left:38px;top:92px;width:406px;height:504px">${head(t('chatCreativeCustomer'))}${bubble('question',t('chatCreativeAddress'),23,120,358)}${bubble('wait',t('chatCreativeWait'),43,238,338,true)}${bubble('answer',t('chatCreativeApproved'),43,350,338,true)}</div><div class="panel" id="approval-panel" style="left:474px;top:55px;width:444px;height:552px"><div class="head"><div class="avatar">✓</div><div class="name">${t('chatCreativeTeam')}</div></div><div style="padding:10px 25px"><div class="rule"><span>${t('motionTracking')}</span><span class="badge">${t('motionAuto')}</span></div><div class="rule"><span>${t('motionAddress')}</span></div><div id="request" class="approval" style="margin-top:24px"><div class="small">${t('uiFilmAddressRequest')}</div><div class="button" id="approve">${t('opApprove')}</div></div></div></div><div class="cursor" id="cursor" style="left:740px;top:424px">${arrow}</div><div class="ripple" id="ripple" style="left:720px;top:398px"></div>`;
    motion=enter('#chat',0)+enter('#question',.4,-20)+enter('#wait',1.8,20)+enter('#approval-panel',2.7,35)+enter('#cursor',4.5,110,80)+`tl.to(['#cursor','#approve'],{scale:.94,duration:.12,yoyo:true,repeat:1},5.5);tl.fromTo('#ripple',{scale:0,opacity:0},{scale:2.3,opacity:.6,duration:.35},5.5);tl.to('#ripple',{opacity:0,duration:.4},5.85);`+exit('#cursor',6.2)+enter('#answer',6.7,20);
    proof='#answer';
  } else if(scene==='order') {
    content=`<div class="panel" id="chat" style="left:72px;top:48px;width:448px;height:522px">${head(t('motionOrders'))}<div class="order-thread">${bubble('question',t('chatCreativeBuy'),0,0,0)}<div class="link" id="checkout">${t('motionLink')}<span>↗</span></div>${bubble('payment',t('chatCreativePaid'),0,0,0)}${bubble('answer',t('chatCreativeConfirmed'),0,0,0,true)}</div></div><div class="panel receipt" id="receipt" style="left:550px;top:72px;width:348px;height:476px"><span class="check">✓</span><h2>${t('chatCreativeOrder')}</h2><div class="product">${product}</div><div class="rule"><span>${t('motionPayment')}</span><span>✓</span></div><div class="rule"><span>Shopify</span><span>${t('motionSynced')}</span></div></div>`;
    motion=enter('#chat',0)+enter('#question',.3,-20)+enter('#checkout',1.7,20)+enter('#payment',3.1,-20)+enter('#answer',4.8,20)+enter('#receipt',6.2,38)+`tl.fromTo('#receipt>.check',{scale:.6,opacity:.4},{scale:1,opacity:1,duration:.5,ease:'back.out(1.5)'},8.1);`;
    proof='#receipt';
  } else {
    content=`<div class="panel" id="inbox" style="left:46px;top:70px;width:376px;height:522px"><div class="head"><div class="name">${t('motionResults')}</div></div><div class="inbox-row" id="row1">${t('chatCreativeOrder')}<span>WhatsApp · ${t('chatCreativeResolved')}</span></div><div class="inbox-row" id="row2">${t('chatCreativeCase')}<span>Instagram · ${t('chatCreativeResolved')}</span></div><div class="inbox-row" id="row3">${t('motionRefund')}<span>${t('chatCreativeReview')}</span></div></div><div class="panel" id="thread" style="left:453px;top:98px;width:460px;height:495px">${head(t('chatCreativeThread'),'Instagram')}${bubble('question',t('chatCreativeCase'),23,119,403)}${bubble('answer',t('chatCreativeTracking'),44,230,390,true)}<div id="tracking" class="link" style="position:absolute;left:44px;top:353px;width:390px">${t('motionTracking')}<span>↗</span></div></div>`;
    motion=enter('#inbox',0)+enter('#row1',.3)+enter('#row2',1)+enter('#row3',1.7)+`tl.to('#row2',{backgroundColor:'#f7ff9e',duration:.35},2.6);`+enter('#thread',3.2,35)+enter('#question',3.8,-20)+enter('#answer',5.3,20)+enter('#tracking',6.8);
    proof='#thread';
  }
  // Compress the original story beats to 6.5 seconds without changing their order.
  motion=motion.replace(/duration:(\d*\.?\d+)/g,(_,n)=>`duration:${(Number(n)*.72).toFixed(3)}`)
    .replace(/stagger:(\d*\.?\d+)/g,(_,n)=>`stagger:${(Number(n)*.72).toFixed(3)}`)
    .replace(/,(\d*\.?\d+)\);/g,(_,n)=>`,${(Number(n)*.72).toFixed(3)});`);
  const dir=resolve(root,`${scene}-${lang}`); await mkdir(dir,{recursive:true});
  for(const name of ['sans.ttf','mono.ttf','gsap.js']) await copyFile(resolve(assets,name),resolve(dir,name));
  await writeFile(resolve(dir,'index.html'),`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><style>${css}</style></head><body><div id="film" data-composition-id="film" data-width="960" data-height="720" data-duration="6.5"><div class="stage">${content}</div></div><script src="gsap.js"></script><script>const tl=gsap.timeline({paused:true});${motion}window.__timelines['film']=tl;</script></body></html>`);
  await writeFile(resolve(dir,'hyperframes.json'),JSON.stringify({width:960,height:720,fps:30}));
  await writeFile(resolve(dir,'index.motion.json'),JSON.stringify({duration:6.5,assertions:[{kind:'appearsBy',selector:proof,bySec:5.8},{kind:'staysInFrame',selector:proof}]}));
}
console.log(root);
