import {describe,expect,it} from 'vitest';
import {parseWhatsAppCallEvents,freshWhatsAppCallOffer} from './whatsapp-call-webhook';
const incoming={id:'wacid.fixture',event:'connect',direction:'USER_INITIATED',from:'12025550100',to:'573001234567',timestamp:String(Math.floor(Date.now()/1000)),session:{sdp_type:'offer',sdp:'v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\n'}};
const envelope=(calls:unknown[],field='calls')=>({object:'whatsapp_business_account',entry:[{id:'456789',changes:[{field,value:{metadata:{phone_number_id:'123456'},calls}}]}]});
describe('Signed call webhook parsing boundary',()=>{
 it.each(['wacid.fixture+/=','opaque:provider@id'])('preserves an opaque provider ID %s without inventing its alphabet',id=>expect(parseWhatsAppCallEvents(envelope([{...incoming,id}])).events[0]?.providerCallId).toBe(id));
 it.each(['has space','has\nline','has\u0000control',''])('rejects an invalid provider ID %s',id=>expect(parseWhatsAppCallEvents(envelope([{...incoming,id}])).events).toEqual([]));
 it('binds an incoming offer to WABA/business phone and customer, not business to',()=>expect(parseWhatsAppCallEvents(envelope([incoming]))).toMatchObject({invalid:0,events:[{wabaId:'456789',phoneNumberId:'123456',providerCallId:'wacid.fixture',direction:'inbound',peer:'12025550100',sdp:{type:'offer'}}]}));
 it('selects the outbound customer to, requires an answer',()=>{const result=parseWhatsAppCallEvents(envelope([{...incoming,direction:'BUSINESS_INITIATED',from:'573001234567',to:'12025550100',session:{...incoming.session,sdp_type:'answer'}}]));expect(result.events[0]).toMatchObject({direction:'outbound',peer:'12025550100',sdp:{type:'answer'}});});
 it('preserves a BSUID-only peer without fabricating a phone',()=>{const result=parseWhatsAppCallEvents(envelope([{...incoming,from:undefined,from_user_id:'opaque-bsuid'}]));expect(result).toMatchObject({invalid:0,events:[{peer:null,peerUserId:'opaque-bsuid'}]});});
 it('does not infer who hung up from the original call direction',()=>{const result=parseWhatsAppCallEvents(envelope([{...incoming,event:'terminate',session:undefined,status:'COMPLETED'}]));expect(result.events[0]).toMatchObject({event:'terminate',direction:'inbound',status:'COMPLETED',sdp:null});expect(result.events[0]).not.toHaveProperty('disconnectReason');});
 it('isolates malformed events while preserving a valid one',()=>{const result=parseWhatsAppCallEvents(envelope([{...incoming,session:{...incoming.session,sdp_type:'answer'}},incoming]));expect(result.invalid).toBe(1);expect(result.events).toHaveLength(1);});
 it.each([{...incoming,direction:'UNKNOWN'},{...incoming,from:undefined},{...incoming,event:'terminate',status:['COMPLETED']},{...incoming,session:{sdp_type:'offer',sdp:'x'.repeat(65537)}}])('rejects invalid/inconsistent provider payloads',call=>expect(parseWhatsAppCallEvents(envelope([call])).events).toEqual([]));
 it('ignores messaging events instead of treating them as calls',()=>expect(parseWhatsAppCallEvents(envelope([incoming],'messages'))).toEqual({events:[],invalid:0}));
 it('requires the documented account envelope',()=>expect(parseWhatsAppCallEvents({...envelope([incoming]),object:'other'}).events).toEqual([]));
 it('bounds freshness only for a first connect operation',()=>{const value=parseWhatsAppCallEvents(envelope([incoming])).events[0],now=value.timestamp*1000;expect(freshWhatsAppCallOffer(value,now)).toBe(true);expect(freshWhatsAppCallOffer(value,now+90001)).toBe(false);expect(freshWhatsAppCallOffer(value,now-15001)).toBe(false);expect(freshWhatsAppCallOffer({...value,event:'terminate'},now)).toBe(false);});
});
