// Read-only configuration snapshot, 2026-09-10 UTC. No account or contact identifiers.
import type { SnapshotFlow } from './canvas-graph';
export const automationSnapshot: Record<string, SnapshotFlow[]> = {
  pilar: [
    {
      steps: [
        {
          config: {},
          id: 'pilar-flow-0-step-0',
          parent: null,
          type: 'add_tag',
          branch: null,
          position: 0,
        },
        {
          config: {
            operand: '48h',
            value: 'false',
            subject: 'rejected_open',
          },
          id: 'pilar-flow-0-step-1',
          parent: 'pilar-flow-0-step-13',
          type: 'condition',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            operand: '48h',
            value: 'false',
            subject: 'messaged',
          },
          id: 'pilar-flow-0-step-2',
          parent: 'pilar-flow-0-step-1',
          type: 'condition',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            template_name: 'carrito_abandonado_pilar_v3',
            variables: {
              '1': '{{vars.contact_first_name}}',
            },
          },
          id: 'pilar-flow-0-step-3',
          parent: 'pilar-flow-0-step-2',
          type: 'send_template',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            operand: '1h',
            value: 'false',
            subject: 'messaged',
          },
          id: 'pilar-flow-0-step-4',
          parent: 'pilar-flow-0-step-14',
          type: 'condition',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            template_name: 'carrito_abandonado_pilar_intento_2',
            variables: {
              '1': '{{vars.contact_first_name}}',
            },
          },
          id: 'pilar-flow-0-step-5',
          parent: 'pilar-flow-0-step-4',
          type: 'send_template',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            operand: '1h',
            value: 'false',
            subject: 'messaged',
          },
          id: 'pilar-flow-0-step-6',
          parent: 'pilar-flow-0-step-16',
          type: 'condition',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            template_name: 'carrito_abandonado_pilar_intento_3',
            variables: {
              '1': '{{vars.contact_first_name}}',
            },
          },
          id: 'pilar-flow-0-step-7',
          parent: 'pilar-flow-0-step-6',
          type: 'send_template',
          branch: 'yes',
          position: 0,
        },
        {
          config: {},
          id: 'pilar-flow-0-step-8',
          parent: 'pilar-flow-0-step-15',
          type: 'add_tag',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            amount: 1,
            unit: 'hours',
          },
          id: 'pilar-flow-0-step-9',
          parent: 'pilar-flow-0-step-2',
          type: 'wait',
          branch: 'yes',
          position: 1,
        },
        {
          config: {
            amount: 5,
            unit: 'hours',
          },
          id: 'pilar-flow-0-step-10',
          parent: 'pilar-flow-0-step-4',
          type: 'wait',
          branch: 'yes',
          position: 1,
        },
        {
          config: {
            amount: 48,
            unit: 'hours',
          },
          id: 'pilar-flow-0-step-11',
          parent: 'pilar-flow-0-step-6',
          type: 'wait',
          branch: 'yes',
          position: 1,
        },
        {
          config: {
            amount: 15,
            unit: 'minutes',
          },
          id: 'pilar-flow-0-step-12',
          parent: null,
          type: 'wait',
          branch: null,
          position: 1,
        },
        {
          config: {
            operand: 'since_trigger',
            value: 'false',
            subject: 'purchased',
          },
          id: 'pilar-flow-0-step-13',
          parent: null,
          type: 'condition',
          branch: null,
          position: 2,
        },
        {
          config: {
            operand: 'since_trigger',
            value: 'false',
            subject: 'purchased',
          },
          id: 'pilar-flow-0-step-14',
          parent: 'pilar-flow-0-step-2',
          type: 'condition',
          branch: 'yes',
          position: 2,
        },
        {
          config: {
            operand: 'since_trigger',
            value: 'true',
            subject: 'purchased',
          },
          id: 'pilar-flow-0-step-15',
          parent: 'pilar-flow-0-step-6',
          type: 'condition',
          branch: 'yes',
          position: 2,
        },
        {
          config: {
            operand: 'since_trigger',
            value: 'false',
            subject: 'purchased',
          },
          id: 'pilar-flow-0-step-16',
          parent: 'pilar-flow-0-step-4',
          type: 'condition',
          branch: 'yes',
          position: 2,
        },
      ],
      id: 'pilar-flow-0',
      status: 'draft',
      trigger: 'shopify_abandoned_checkout',
      stopOnReply: true,
      title: 'pitch.canvasCartDraft',
    },
    {
      steps: [
        {
          config: {
            template_name: 'nuevo_pedido',
            variables: {},
          },
          id: 'pilar-flow-1-step-0',
          parent: null,
          type: 'send_template',
          branch: null,
          position: 0,
        },
      ],
      id: 'pilar-flow-1',
      status: 'active',
      trigger: 'shopify_order_created',
      stopOnReply: false,
      title: 'pitch.canvasOrder',
    },
    {
      steps: [
        {
          config: {
            operand: 'payment_gateway',
            value: 'Cash on Delivery',
            op: 'eq',
            subject: 'context_var',
          },
          id: 'pilar-flow-2-step-0',
          parent: null,
          type: 'condition',
          branch: null,
          position: 0,
        },
        {
          config: {},
          id: 'pilar-flow-2-step-1',
          parent: 'pilar-flow-2-step-0',
          type: 'voice_call',
          branch: 'yes',
          position: 0,
        },
      ],
      id: 'pilar-flow-2',
      status: 'draft',
      trigger: 'shopify_order_created',
      stopOnReply: false,
      title: 'pitch.canvasVoiceTest',
    },
    {
      steps: [
        {
          config: {
            operand: 'financial_status',
            value: 'pending',
            op: 'eq',
            subject: 'context_var',
          },
          id: 'pilar-flow-3-step-0',
          parent: null,
          type: 'condition',
          branch: null,
          position: 0,
        },
        {
          config: {
            amount: 1,
            unit: 'hours',
          },
          id: 'pilar-flow-3-step-1',
          parent: 'pilar-flow-3-step-0',
          type: 'wait',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            template_name: 'pago_pendiente_1',
            variables: {
              '1': '{{vars.customer_name}}',
              '2': '{{vars.order_name}}',
              '3': '{{vars.total_price}}',
            },
          },
          id: 'pilar-flow-3-step-2',
          parent: 'pilar-flow-3-step-8',
          type: 'send_template',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            template_name: 'pago_pendiente_2',
            variables: {
              '1': '{{vars.customer_name}}',
              '2': '{{vars.order_name}}',
              '3': '{{vars.total_price}}',
            },
          },
          id: 'pilar-flow-3-step-3',
          parent: 'pilar-flow-3-step-9',
          type: 'send_template',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            template_name: 'pago_pendiente_3',
            variables: {
              '1': '{{vars.customer_name}}',
              '2': '{{vars.order_name}}',
              '3': '{{vars.total_price}}',
            },
          },
          id: 'pilar-flow-3-step-4',
          parent: 'pilar-flow-3-step-10',
          type: 'send_template',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            amount: 5,
            unit: 'hours',
          },
          id: 'pilar-flow-3-step-5',
          parent: 'pilar-flow-3-step-8',
          type: 'wait',
          branch: 'yes',
          position: 1,
        },
        {
          config: {
            amount: 18,
            unit: 'hours',
          },
          id: 'pilar-flow-3-step-6',
          parent: 'pilar-flow-3-step-9',
          type: 'wait',
          branch: 'yes',
          position: 1,
        },
        {
          config: {},
          id: 'pilar-flow-3-step-7',
          parent: 'pilar-flow-3-step-10',
          type: 'add_tag',
          branch: 'yes',
          position: 1,
        },
        {
          config: {
            value: 'false',
            subject: 'order_paid',
          },
          id: 'pilar-flow-3-step-8',
          parent: 'pilar-flow-3-step-0',
          type: 'condition',
          branch: 'yes',
          position: 1,
        },
        {
          config: {
            value: 'false',
            subject: 'order_paid',
          },
          id: 'pilar-flow-3-step-9',
          parent: 'pilar-flow-3-step-8',
          type: 'condition',
          branch: 'yes',
          position: 2,
        },
        {
          config: {
            value: 'false',
            subject: 'order_paid',
          },
          id: 'pilar-flow-3-step-10',
          parent: 'pilar-flow-3-step-9',
          type: 'condition',
          branch: 'yes',
          position: 2,
        },
      ],
      id: 'pilar-flow-3',
      status: 'draft',
      trigger: 'shopify_order_created',
      stopOnReply: false,
      title: 'pitch.canvasPending',
    },
    {
      steps: [
        {
          config: {
            template_name: 'pago_rechazado_recuperacion',
            variables: {
              '1': '{{vars.customer_name}}',
              '2': '{{vars.total_price}}',
            },
          },
          id: 'pilar-flow-4-step-0',
          parent: 'pilar-flow-4-step-1',
          type: 'send_template',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            operand: '48h',
            value: 'false',
            subject: 'messaged',
          },
          id: 'pilar-flow-4-step-1',
          parent: 'pilar-flow-4-step-3',
          type: 'condition',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            amount: 10,
            unit: 'minutes',
          },
          id: 'pilar-flow-4-step-2',
          parent: null,
          type: 'wait',
          branch: null,
          position: 0,
        },
        {
          config: {
            operand: 'since_trigger',
            value: 'false',
            subject: 'purchased',
          },
          id: 'pilar-flow-4-step-3',
          parent: null,
          type: 'condition',
          branch: null,
          position: 1,
        },
        {
          config: {},
          id: 'pilar-flow-4-step-4',
          parent: 'pilar-flow-4-step-1',
          type: 'add_tag',
          branch: 'yes',
          position: 1,
        },
      ],
      id: 'pilar-flow-4',
      status: 'active',
      trigger: 'payment_rejected',
      stopOnReply: false,
      title: 'pitch.canvasRejected',
    },
    {
      steps: [
        {
          config: {
            operand: '48h',
            value: 'false',
            subject: 'messaged',
          },
          id: 'pilar-flow-5-step-0',
          parent: 'pilar-flow-5-step-4',
          type: 'condition',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            template_name: 'carrito_abandonado_2',
            variables: {},
          },
          id: 'pilar-flow-5-step-1',
          parent: 'pilar-flow-5-step-0',
          type: 'send_template',
          branch: 'yes',
          position: 0,
        },
        {
          config: {},
          id: 'pilar-flow-5-step-2',
          parent: 'pilar-flow-5-step-7',
          type: 'add_tag',
          branch: 'yes',
          position: 0,
        },
        {
          config: {},
          id: 'pilar-flow-5-step-3',
          parent: null,
          type: 'add_tag',
          branch: null,
          position: 0,
        },
        {
          config: {
            operand: '48h',
            value: 'false',
            subject: 'rejected_open',
          },
          id: 'pilar-flow-5-step-4',
          parent: 'pilar-flow-5-step-8',
          type: 'condition',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            amount: 48,
            unit: 'hours',
          },
          id: 'pilar-flow-5-step-5',
          parent: 'pilar-flow-5-step-0',
          type: 'wait',
          branch: 'yes',
          position: 1,
        },
        {
          config: {
            amount: 15,
            unit: 'minutes',
          },
          id: 'pilar-flow-5-step-6',
          parent: null,
          type: 'wait',
          branch: null,
          position: 1,
        },
        {
          config: {
            operand: 'since_trigger',
            value: 'true',
            subject: 'purchased',
          },
          id: 'pilar-flow-5-step-7',
          parent: 'pilar-flow-5-step-0',
          type: 'condition',
          branch: 'yes',
          position: 2,
        },
        {
          config: {
            operand: 'since_trigger',
            value: 'false',
            subject: 'purchased',
          },
          id: 'pilar-flow-5-step-8',
          parent: null,
          type: 'condition',
          branch: null,
          position: 2,
        },
      ],
      id: 'pilar-flow-5',
      status: 'active',
      trigger: 'shopify_abandoned_checkout',
      stopOnReply: false,
      title: 'pitch.canvasCart',
    },
    {
      steps: [
        {
          config: {
            template_name: 'tracking_envio',
            variables: {
              '1': '{{vars.tracking_url}}',
            },
          },
          id: 'pilar-flow-6-step-0',
          parent: null,
          type: 'send_template',
          branch: null,
          position: 0,
        },
      ],
      id: 'pilar-flow-6',
      status: 'active',
      trigger: 'shopify_order_fulfilled',
      stopOnReply: false,
      title: 'pitch.canvasShipping',
    },
  ],
  rasmiaw: [
    {
      steps: [
        {
          config: {
            template_name: 'rasmiaw_pago_rechazado',
            variables: {},
          },
          id: 'rasmiaw-flow-0-step-0',
          parent: null,
          type: 'send_template',
          branch: null,
          position: 0,
        },
        {
          config: {
            values: {
              benefit_percent: 5,
            },
          },
          id: 'rasmiaw-flow-0-step-1',
          parent: null,
          type: 'set_context',
          branch: null,
          position: 1,
        },
        {
          config: {
            amount: 24,
            unit: 'hours',
          },
          id: 'rasmiaw-flow-0-step-2',
          parent: null,
          type: 'wait',
          branch: null,
          position: 2,
        },
      ],
      id: 'rasmiaw-flow-0',
      // Inactive draft: the audited Mercado Pago integration is still missing.
      status: 'blocked',
      trigger: 'payment_rejected',
      stopOnReply: true,
      title: 'pitch.canvasRejected',
    },
    {
      steps: [
        {
          config: {
            amount: 1,
            unit: 'hours',
          },
          id: 'rasmiaw-flow-1-step-0',
          parent: null,
          type: 'wait',
          branch: null,
          position: 0,
        },
        {
          config: {
            operand: 'since_trigger',
            value: 'true',
            subject: 'purchased',
          },
          id: 'rasmiaw-flow-1-step-1',
          parent: 'rasmiaw-flow-1-step-4',
          type: 'condition',
          branch: 'no',
          position: 0,
        },
        {
          config: {
            template_name: 'rasmiaw_carrito_abandonado_1',
            variables: {},
          },
          id: 'rasmiaw-flow-1-step-2',
          parent: 'rasmiaw-flow-1-step-1',
          type: 'send_template',
          branch: 'no',
          position: 0,
        },
        {
          config: {
            template_name: 'rasmiaw_carrito_abandonado_2',
            variables: {},
          },
          id: 'rasmiaw-flow-1-step-3',
          parent: 'rasmiaw-flow-1-step-6',
          type: 'send_template',
          branch: 'no',
          position: 0,
        },
        {
          config: {
            operand: 'since_trigger',
            value: 'true',
            subject: 'rejected_open',
          },
          id: 'rasmiaw-flow-1-step-4',
          parent: null,
          type: 'condition',
          branch: null,
          position: 1,
        },
        {
          config: {
            amount: 23,
            unit: 'hours',
          },
          id: 'rasmiaw-flow-1-step-5',
          parent: 'rasmiaw-flow-1-step-1',
          type: 'wait',
          branch: 'no',
          position: 1,
        },
        {
          config: {
            operand: 'since_trigger',
            value: 'true',
            subject: 'purchased',
          },
          id: 'rasmiaw-flow-1-step-6',
          parent: 'rasmiaw-flow-1-step-1',
          type: 'condition',
          branch: 'no',
          position: 2,
        },
      ],
      id: 'rasmiaw-flow-1',
      status: 'active',
      trigger: 'shopify_abandoned_checkout',
      stopOnReply: false,
      title: 'pitch.canvasCart',
    },
    {
      steps: [
        {
          config: {
            template_name: 'rasmiaw_envio_tracking',
            variables: {
              '1': '{{vars.tracking_number}}',
            },
          },
          id: 'rasmiaw-flow-2-step-0',
          parent: null,
          type: 'send_template',
          branch: null,
          position: 0,
        },
      ],
      id: 'rasmiaw-flow-2',
      status: 'active',
      trigger: 'shopify_order_fulfilled',
      stopOnReply: false,
      title: 'pitch.canvasShipping',
    },
    {
      steps: [
        {
          config: {
            operand: 'financial_status',
            value: 'paid',
            subject: 'context_var',
          },
          id: 'rasmiaw-flow-3-step-0',
          parent: null,
          type: 'condition',
          branch: null,
          position: 0,
        },
        {
          config: {
            template_name: 'rasmiaw_preparando_pedido',
            variables: {},
          },
          id: 'rasmiaw-flow-3-step-1',
          parent: 'rasmiaw-flow-3-step-0',
          type: 'send_template',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            operand: 'financial_status',
            value: 'pending',
            subject: 'context_var',
          },
          id: 'rasmiaw-flow-3-step-2',
          parent: 'rasmiaw-flow-3-step-0',
          type: 'condition',
          branch: 'no',
          position: 0,
        },
        {
          config: {
            template_name: 'rasmiaw_preparando_pedido',
            variables: {},
          },
          id: 'rasmiaw-flow-3-step-3',
          parent: 'rasmiaw-flow-3-step-2',
          type: 'send_template',
          branch: 'yes',
          position: 0,
        },
        {
          config: {
            amount: 3,
            unit: 'seconds',
          },
          id: 'rasmiaw-flow-3-step-4',
          parent: 'rasmiaw-flow-3-step-2',
          type: 'wait',
          branch: 'yes',
          position: 1,
        },
        {
          config: {
            template_name: 'rasmiaw_beneficio_contraentrega',
            variables: {},
          },
          id: 'rasmiaw-flow-3-step-5',
          parent: 'rasmiaw-flow-3-step-2',
          type: 'send_template',
          branch: 'yes',
          position: 2,
        },
        {
          config: {
            values: {
              benefit_percent: 5,
            },
          },
          id: 'rasmiaw-flow-3-step-6',
          parent: 'rasmiaw-flow-3-step-2',
          type: 'set_context',
          branch: 'yes',
          position: 3,
        },
        {
          config: {
            amount: 3,
            unit: 'hours',
          },
          id: 'rasmiaw-flow-3-step-7',
          parent: 'rasmiaw-flow-3-step-2',
          type: 'wait',
          branch: 'yes',
          position: 4,
        },
        {
          config: {
            template_name: 'rasmiaw_recordatorio_contraentrega',
            variables: {},
          },
          id: 'rasmiaw-flow-3-step-8',
          parent: 'rasmiaw-flow-3-step-2',
          type: 'send_template',
          branch: 'yes',
          position: 5,
        },
        {
          config: {
            amount: 24,
            unit: 'hours',
          },
          id: 'rasmiaw-flow-3-step-9',
          parent: 'rasmiaw-flow-3-step-2',
          type: 'wait',
          branch: 'yes',
          position: 6,
        },
        {
          config: {
            values: {
              benefit_percent: 10,
            },
          },
          id: 'rasmiaw-flow-3-step-10',
          parent: 'rasmiaw-flow-3-step-2',
          type: 'set_context',
          branch: 'yes',
          position: 7,
        },
        {
          config: {
            template_name: 'rasmiaw_ultima_oportunidad_contraentrega',
            variables: {},
          },
          id: 'rasmiaw-flow-3-step-11',
          parent: 'rasmiaw-flow-3-step-2',
          type: 'send_template',
          branch: 'yes',
          position: 8,
        },
        {
          config: {
            amount: 24,
            unit: 'hours',
          },
          id: 'rasmiaw-flow-3-step-12',
          parent: 'rasmiaw-flow-3-step-2',
          type: 'wait',
          branch: 'yes',
          position: 9,
        },
      ],
      id: 'rasmiaw-flow-3',
      status: 'active',
      trigger: 'shopify_order_created',
      stopOnReply: true,
      title: 'pitch.canvasOrder',
    },
  ],
};
