// Configuration snapshot reviewed 2026-09-09; proposals do not change live flows.
export const brands = ['pilar', 'rasmiaw', 'contraentrega'] as const;
export type Brand = (typeof brands)[number];
export const auditCases = [
  {
    id: 'audit-1',
    group: 0,
    title: 'onboarding.audit0Title',
    difference: 'onboarding.audit0Difference',
    pilar: [
      'onboarding.audit0P0',
      'onboarding.audit0P1',
      'onboarding.audit0P2',
    ],
    rasmiaw: [
      'onboarding.audit0R0',
      'onboarding.audit0R1',
      'onboarding.audit0R2',
    ],
    pilarStatus: 'onboarding.audit0PS',
    rasmiawStatus: 'onboarding.audit0RS',
  },
  {
    id: 'audit-2',
    group: 0,
    title: 'onboarding.audit1Title',
    difference: 'onboarding.audit1Difference',
    pilar: [
      'onboarding.audit1P0',
      'onboarding.audit1P1',
      'onboarding.audit1P2',
    ],
    rasmiaw: [
      'onboarding.audit1R0',
      'onboarding.audit1R1',
      'onboarding.audit1R2',
    ],
    pilarStatus: 'onboarding.audit1PS',
    rasmiawStatus: 'onboarding.audit1RS',
  },
  {
    id: 'audit-3',
    group: 0,
    title: 'onboarding.audit2Title',
    difference: 'onboarding.audit2Difference',
    pilar: [
      'onboarding.audit2P0',
      'onboarding.audit2P1',
      'onboarding.audit2P2',
    ],
    rasmiaw: [
      'onboarding.audit2R0',
      'onboarding.audit2R1',
      'onboarding.audit2R2',
    ],
    pilarStatus: 'onboarding.audit2PS',
    rasmiawStatus: 'onboarding.audit2RS',
  },
  {
    id: 'audit-4',
    group: 0,
    title: 'onboarding.audit3Title',
    difference: 'onboarding.audit3Difference',
    pilar: ['onboarding.audit3P0', 'onboarding.audit3P1'],
    rasmiaw: ['onboarding.audit3R0', 'onboarding.audit3R1'],
    pilarStatus: 'onboarding.audit3PS',
    rasmiawStatus: 'onboarding.audit3RS',
  },
  {
    id: 'audit-5',
    group: 0,
    title: 'onboarding.audit4Title',
    difference: 'onboarding.audit4Difference',
    pilar: [
      'onboarding.audit4P0',
      'onboarding.audit4P1',
      'onboarding.audit4P2',
    ],
    rasmiaw: ['onboarding.audit4R0', 'onboarding.audit4R1'],
    pilarStatus: 'onboarding.audit4PS',
    rasmiawStatus: 'onboarding.audit4RS',
  },
  {
    id: 'audit-6',
    group: 0,
    title: 'onboarding.audit5Title',
    difference: 'onboarding.audit5Difference',
    pilar: [
      'onboarding.audit5P0',
      'onboarding.audit5P1',
      'onboarding.audit5P2',
    ],
    rasmiaw: ['onboarding.audit5R0', 'onboarding.audit5R1'],
    pilarStatus: 'onboarding.audit5PS',
    rasmiawStatus: 'onboarding.audit5RS',
  },
  {
    id: 'audit-7',
    group: 1,
    title: 'onboarding.audit6Title',
    difference: 'onboarding.audit6Difference',
    pilar: [
      'onboarding.audit6P0',
      'onboarding.audit6P1',
      'onboarding.audit6P2',
      'onboarding.audit6P3',
    ],
    rasmiaw: [
      'onboarding.audit6R0',
      'onboarding.audit6R1',
      'onboarding.audit6R2',
      'onboarding.audit6R3',
    ],
    pilarStatus: 'onboarding.audit6PS',
    rasmiawStatus: 'onboarding.audit6RS',
  },
  {
    id: 'audit-8',
    group: 1,
    title: 'onboarding.audit7Title',
    difference: 'onboarding.audit7Difference',
    pilar: ['onboarding.audit7P0', 'onboarding.audit7P1'],
    rasmiaw: ['onboarding.audit7R0', 'onboarding.audit7R1'],
    pilarStatus: 'onboarding.audit7PS',
    rasmiawStatus: 'onboarding.audit7RS',
  },
  {
    id: 'audit-9',
    group: 1,
    title: 'onboarding.audit8Title',
    difference: 'onboarding.audit8Difference',
    pilar: ['onboarding.audit8P0', 'onboarding.audit8P1'],
    rasmiaw: [
      'onboarding.audit8R0',
      'onboarding.audit8R1',
      'onboarding.audit8R2',
    ],
    pilarStatus: 'onboarding.audit8PS',
    rasmiawStatus: 'onboarding.audit8RS',
  },
  {
    id: 'audit-10',
    group: 1,
    title: 'onboarding.audit9Title',
    difference: 'onboarding.audit9Difference',
    pilar: ['onboarding.audit9P0', 'onboarding.audit9P1'],
    rasmiaw: [
      'onboarding.audit9R0',
      'onboarding.audit9R1',
      'onboarding.audit9R2',
    ],
    pilarStatus: 'onboarding.audit9PS',
    rasmiawStatus: 'onboarding.audit9RS',
  },
  {
    id: 'audit-11',
    group: 1,
    title: 'onboarding.audit10Title',
    difference: 'onboarding.audit10Difference',
    pilar: [
      'onboarding.audit10P0',
      'onboarding.audit10P1',
      'onboarding.audit10P2',
    ],
    rasmiaw: [
      'onboarding.audit10R0',
      'onboarding.audit10R1',
      'onboarding.audit10R2',
    ],
    pilarStatus: 'onboarding.audit10PS',
    rasmiawStatus: 'onboarding.audit10RS',
  },
  {
    id: 'audit-12',
    group: 1,
    title: 'onboarding.audit11Title',
    difference: 'onboarding.audit11Difference',
    pilar: ['onboarding.audit11P0'],
    rasmiaw: ['onboarding.audit11R0', 'onboarding.audit11R1'],
    pilarStatus: 'onboarding.audit11PS',
    rasmiawStatus: 'onboarding.audit11RS',
  },
  {
    id: 'audit-13',
    group: 2,
    title: 'onboarding.audit12Title',
    difference: 'onboarding.audit12Difference',
    pilar: ['onboarding.audit12P0', 'onboarding.audit12P1'],
    rasmiaw: [
      'onboarding.audit12R0',
      'onboarding.audit12R1',
      'onboarding.audit12R2',
    ],
    pilarStatus: 'onboarding.audit12PS',
    rasmiawStatus: 'onboarding.audit12RS',
  },
  {
    id: 'audit-14',
    group: 2,
    title: 'onboarding.audit13Title',
    difference: 'onboarding.audit13Difference',
    pilar: ['onboarding.audit13P0', 'onboarding.audit13P1'],
    rasmiaw: [
      'onboarding.audit13R0',
      'onboarding.audit13R1',
      'onboarding.audit13R2',
      'onboarding.audit13R3',
    ],
    pilarStatus: 'onboarding.audit13PS',
    rasmiawStatus: 'onboarding.audit13RS',
  },
  {
    id: 'audit-15',
    group: 2,
    title: 'onboarding.audit14Title',
    difference: 'onboarding.audit14Difference',
    pilar: ['onboarding.audit14P0', 'onboarding.audit14P1'],
    rasmiaw: ['onboarding.audit14R0', 'onboarding.audit14R1'],
    pilarStatus: 'onboarding.audit14PS',
    rasmiawStatus: 'onboarding.audit14RS',
  },
  {
    id: 'audit-16',
    group: 2,
    title: 'onboarding.audit15Title',
    difference: 'onboarding.audit15Difference',
    pilar: ['onboarding.audit15P0', 'onboarding.audit15P1'],
    rasmiaw: [
      'onboarding.audit15R0',
      'onboarding.audit15R1',
      'onboarding.audit15R2',
    ],
    pilarStatus: 'onboarding.audit15PS',
    rasmiawStatus: 'onboarding.audit15RS',
  },
  {
    id: 'audit-17',
    group: 2,
    title: 'onboarding.audit16Title',
    difference: 'onboarding.audit16Difference',
    pilar: ['onboarding.audit16P0', 'onboarding.audit16P1'],
    rasmiaw: [
      'onboarding.audit16R0',
      'onboarding.audit16R1',
      'onboarding.audit16R2',
    ],
    pilarStatus: 'onboarding.audit16PS',
    rasmiawStatus: 'onboarding.audit16RS',
  },
  {
    id: 'audit-18',
    group: 2,
    title: 'onboarding.audit17Title',
    difference: 'onboarding.audit17Difference',
    pilar: ['onboarding.audit17P0'],
    rasmiaw: [
      'onboarding.audit17R0',
      'onboarding.audit17R1',
      'onboarding.audit17R2',
    ],
    pilarStatus: 'onboarding.audit17PS',
    rasmiawStatus: 'onboarding.audit17RS',
  },
  {
    id: 'audit-19',
    group: 2,
    title: 'onboarding.audit18Title',
    difference: 'onboarding.audit18Difference',
    pilar: ['onboarding.audit18P0', 'onboarding.audit18P1'],
    rasmiaw: [
      'onboarding.audit18R0',
      'onboarding.audit18R1',
      'onboarding.audit18R2',
    ],
    pilarStatus: 'onboarding.audit18PS',
    rasmiawStatus: 'onboarding.audit18RS',
  },
  {
    id: 'audit-20',
    group: 2,
    title: 'onboarding.audit19Title',
    difference: 'onboarding.audit19Difference',
    pilar: ['onboarding.audit19P0'],
    rasmiaw: [
      'onboarding.audit19R0',
      'onboarding.audit19R1',
      'onboarding.audit19R2',
    ],
    pilarStatus: 'onboarding.audit19PS',
    rasmiawStatus: 'onboarding.audit19RS',
  },
  {
    id: 'audit-21',
    group: 2,
    title: 'onboarding.audit20Title',
    difference: 'onboarding.audit20Difference',
    pilar: ['onboarding.audit20P0'],
    rasmiaw: [
      'onboarding.audit20R0',
      'onboarding.audit20R1',
      'onboarding.audit20R2',
    ],
    pilarStatus: 'onboarding.audit20PS',
    rasmiawStatus: 'onboarding.audit20RS',
  },
  {
    id: 'audit-22',
    group: 3,
    title: 'onboarding.audit21Title',
    difference: 'onboarding.audit21Difference',
    pilar: ['onboarding.audit21P0', 'onboarding.audit21P1'],
    rasmiaw: ['onboarding.audit21R0', 'onboarding.audit21R1'],
    pilarStatus: 'onboarding.audit21PS',
    rasmiawStatus: 'onboarding.audit21RS',
  },
  {
    id: 'audit-23',
    group: 3,
    title: 'onboarding.audit22Title',
    difference: 'onboarding.audit22Difference',
    pilar: ['onboarding.audit22P0', 'onboarding.audit22P1'],
    rasmiaw: ['onboarding.audit22R0', 'onboarding.audit22R1'],
    pilarStatus: 'onboarding.audit22PS',
    rasmiawStatus: 'onboarding.audit22RS',
  },
  {
    id: 'audit-24',
    group: 3,
    title: 'onboarding.audit23Title',
    difference: 'onboarding.audit23Difference',
    pilar: ['onboarding.audit23P0', 'onboarding.audit23P1'],
    rasmiaw: ['onboarding.audit23R0', 'onboarding.audit23R1'],
    pilarStatus: 'onboarding.audit23PS',
    rasmiawStatus: 'onboarding.audit23RS',
  },
  {
    id: 'audit-25',
    group: 3,
    title: 'onboarding.audit24Title',
    difference: 'onboarding.audit24Difference',
    pilar: ['onboarding.audit24P0', 'onboarding.audit24P1'],
    rasmiaw: ['onboarding.audit24R0', 'onboarding.audit24R1'],
    pilarStatus: 'onboarding.audit24PS',
    rasmiawStatus: 'onboarding.audit24RS',
  },
  {
    id: 'audit-26',
    group: 3,
    title: 'onboarding.audit25Title',
    difference: 'onboarding.audit25Difference',
    pilar: ['onboarding.audit25P0', 'onboarding.audit25P1'],
    rasmiaw: ['onboarding.audit25R0', 'onboarding.audit25R1'],
    pilarStatus: 'onboarding.audit25PS',
    rasmiawStatus: 'onboarding.audit25RS',
  },
  {
    id: 'audit-27',
    group: 3,
    title: 'onboarding.audit26Title',
    difference: 'onboarding.audit26Difference',
    pilar: ['onboarding.audit26P0', 'onboarding.audit26P1'],
    rasmiaw: ['onboarding.audit26R0', 'onboarding.audit26R1'],
    pilarStatus: 'onboarding.audit26PS',
    rasmiawStatus: 'onboarding.audit26RS',
  },
  {
    id: 'audit-28',
    group: 4,
    title: 'onboarding.audit27Title',
    difference: 'onboarding.audit27Difference',
    pilar: ['onboarding.audit27P0', 'onboarding.audit27P1'],
    rasmiaw: ['onboarding.audit27R0', 'onboarding.audit27R1'],
    pilarStatus: 'onboarding.audit27PS',
    rasmiawStatus: 'onboarding.audit27RS',
  },
  {
    id: 'audit-29',
    group: 4,
    title: 'onboarding.audit28Title',
    difference: 'onboarding.audit28Difference',
    pilar: ['onboarding.audit28P0', 'onboarding.audit28P1'],
    rasmiaw: ['onboarding.audit28R0'],
    pilarStatus: 'onboarding.audit28PS',
    rasmiawStatus: 'onboarding.audit28RS',
  },
  {
    id: 'audit-30',
    group: 4,
    title: 'onboarding.audit29Title',
    difference: 'onboarding.audit29Difference',
    pilar: [
      'onboarding.audit29P0',
      'onboarding.audit29P1',
      'onboarding.audit29P2',
    ],
    rasmiaw: ['onboarding.audit29R0'],
    pilarStatus: 'onboarding.audit29PS',
    rasmiawStatus: 'onboarding.audit29RS',
  },
  {
    id: 'audit-31',
    group: 4,
    title: 'onboarding.audit30Title',
    difference: 'onboarding.audit30Difference',
    pilar: ['onboarding.audit30P0', 'onboarding.audit30P1'],
    rasmiaw: ['onboarding.audit30R0', 'onboarding.audit30R1'],
    pilarStatus: 'onboarding.audit30PS',
    rasmiawStatus: 'onboarding.audit30RS',
  },
  {
    id: 'audit-32',
    group: 4,
    title: 'onboarding.audit31Title',
    difference: 'onboarding.audit31Difference',
    pilar: ['onboarding.audit31P0'],
    rasmiaw: ['onboarding.audit31R0'],
    pilarStatus: 'onboarding.audit31PS',
    rasmiawStatus: 'onboarding.audit31RS',
  },
  {
    id: 'audit-33',
    group: 4,
    title: 'onboarding.audit32Title',
    difference: 'onboarding.audit32Difference',
    pilar: ['onboarding.audit32P0', 'onboarding.audit32P1'],
    rasmiaw: ['onboarding.audit32R0', 'onboarding.audit32R1'],
    pilarStatus: 'onboarding.audit32PS',
    rasmiawStatus: 'onboarding.audit32RS',
  },
  {
    id: 'audit-34',
    group: 4,
    title: 'onboarding.audit33Title',
    difference: 'onboarding.audit33Difference',
    pilar: ['onboarding.audit33P0', 'onboarding.audit33P1'],
    rasmiaw: ['onboarding.audit33R0', 'onboarding.audit33R1'],
    pilarStatus: 'onboarding.audit33PS',
    rasmiawStatus: 'onboarding.audit33RS',
  },
  {
    id: 'audit-35',
    group: 4,
    title: 'onboarding.audit34Title',
    difference: 'onboarding.audit34Difference',
    pilar: [
      'onboarding.audit34P0',
      'onboarding.audit34P1',
      'onboarding.audit34P2',
    ],
    rasmiaw: ['onboarding.audit34R0'],
    pilarStatus: 'onboarding.audit34PS',
    rasmiawStatus: 'onboarding.audit34RS',
  },
];
export const scenarios = [
  {
    id: 'catalog',
    group: 0,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.catalogtitle',
    trigger: 'onboarding.catalogtrigger',
    action: 'onboarding.catalogaction',
    exception: 'onboarding.catalogexception',
    question: 'onboarding.catalogquestion',
  },
  {
    id: 'comments',
    group: 0,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.commentstitle',
    trigger: 'onboarding.commentstrigger',
    action: 'onboarding.commentsaction',
    exception: 'onboarding.commentsexception',
    question: 'onboarding.commentsquestion',
  },
  {
    id: 'checkout',
    group: 0,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.checkouttitle',
    trigger: 'onboarding.checkouttrigger',
    action: 'onboarding.checkoutaction',
    exception: 'onboarding.checkoutexception',
    question: 'onboarding.checkoutquestion',
  },
  {
    id: 'cart',
    group: 1,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.carttitle',
    trigger: 'onboarding.carttrigger',
    action: 'onboarding.cartaction',
    exception: 'onboarding.cartexception',
    question: 'onboarding.cartquestion',
  },
  {
    id: 'rejected',
    group: 1,
    brands: ['pilar', 'rasmiaw'],
    title: 'onboarding.rejectedtitle',
    trigger: 'onboarding.rejectedtrigger',
    action: 'onboarding.rejectedaction',
    exception: 'onboarding.rejectedexception',
    question: 'onboarding.rejectedquestion',
  },
  {
    id: 'pending',
    group: 2,
    brands: ['pilar', 'rasmiaw'],
    title: 'onboarding.pendingtitle',
    trigger: 'onboarding.pendingtrigger',
    action: 'onboarding.pendingaction',
    exception: 'onboarding.pendingexception',
    question: 'onboarding.pendingquestion',
  },
  {
    id: 'benefit',
    group: 2,
    brands: ['rasmiaw'],
    title: 'onboarding.benefittitle',
    trigger: 'onboarding.benefittrigger',
    action: 'onboarding.benefitaction',
    exception: 'onboarding.benefitexception',
    question: 'onboarding.benefitquestion',
  },
  {
    id: 'receipt',
    group: 2,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.receipttitle',
    trigger: 'onboarding.receipttrigger',
    action: 'onboarding.receiptaction',
    exception: 'onboarding.receiptexception',
    question: 'onboarding.receiptquestion',
  },
  {
    id: 'confirm',
    group: 2,
    brands: ['contraentrega'],
    title: 'onboarding.confirmtitle',
    trigger: 'onboarding.confirmtrigger',
    action: 'onboarding.confirmaction',
    exception: 'onboarding.confirmexception',
    question: 'onboarding.confirmquestion',
  },
  {
    id: 'address',
    group: 2,
    brands: ['contraentrega'],
    title: 'onboarding.addresstitle',
    trigger: 'onboarding.addresstrigger',
    action: 'onboarding.addressaction',
    exception: 'onboarding.addressexception',
    question: 'onboarding.addressquestion',
  },
  {
    id: 'codpayment',
    group: 2,
    brands: ['contraentrega'],
    title: 'onboarding.codpaymenttitle',
    trigger: 'onboarding.codpaymenttrigger',
    action: 'onboarding.codpaymentaction',
    exception: 'onboarding.codpaymentexception',
    question: 'onboarding.codpaymentquestion',
  },
  {
    id: 'tracking',
    group: 3,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.trackingtitle',
    trigger: 'onboarding.trackingtrigger',
    action: 'onboarding.trackingaction',
    exception: 'onboarding.trackingexception',
    question: 'onboarding.trackingquestion',
  },
  {
    id: 'change',
    group: 3,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.changetitle',
    trigger: 'onboarding.changetrigger',
    action: 'onboarding.changeaction',
    exception: 'onboarding.changeexception',
    question: 'onboarding.changequestion',
  },
  {
    id: 'incident',
    group: 3,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.incidenttitle',
    trigger: 'onboarding.incidenttrigger',
    action: 'onboarding.incidentaction',
    exception: 'onboarding.incidentexception',
    question: 'onboarding.incidentquestion',
  },
  {
    id: 'refusal',
    group: 3,
    brands: ['contraentrega'],
    title: 'onboarding.refusaltitle',
    trigger: 'onboarding.refusaltrigger',
    action: 'onboarding.refusalaction',
    exception: 'onboarding.refusalexception',
    question: 'onboarding.refusalquestion',
  },
  {
    id: 'collection',
    group: 3,
    brands: ['contraentrega'],
    title: 'onboarding.collectiontitle',
    trigger: 'onboarding.collectiontrigger',
    action: 'onboarding.collectionaction',
    exception: 'onboarding.collectionexception',
    question: 'onboarding.collectionquestion',
  },
  {
    id: 'returns',
    group: 3,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.returnstitle',
    trigger: 'onboarding.returnstrigger',
    action: 'onboarding.returnsaction',
    exception: 'onboarding.returnsexception',
    question: 'onboarding.returnsquestion',
  },
  {
    id: 'care',
    group: 4,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.caretitle',
    trigger: 'onboarding.caretrigger',
    action: 'onboarding.careaction',
    exception: 'onboarding.careexception',
    question: 'onboarding.carequestion',
  },
  {
    id: 'satisfaction',
    group: 4,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.satisfactiontitle',
    trigger: 'onboarding.satisfactiontrigger',
    action: 'onboarding.satisfactionaction',
    exception: 'onboarding.satisfactionexception',
    question: 'onboarding.satisfactionquestion',
  },
  {
    id: 'repeat',
    group: 4,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.repeattitle',
    trigger: 'onboarding.repeattrigger',
    action: 'onboarding.repeataction',
    exception: 'onboarding.repeatexception',
    question: 'onboarding.repeatquestion',
  },
  {
    id: 'handoff',
    group: 4,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.handofftitle',
    trigger: 'onboarding.handofftrigger',
    action: 'onboarding.handoffaction',
    exception: 'onboarding.handoffexception',
    question: 'onboarding.handoffquestion',
  },
  {
    id: 'deliveryfailure',
    group: 4,
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.deliveryfailuretitle',
    trigger: 'onboarding.deliveryfailuretrigger',
    action: 'onboarding.deliveryfailureaction',
    exception: 'onboarding.deliveryfailureexception',
    question: 'onboarding.deliveryfailurequestion',
  },
];
export const questions = [
  {
    id: 'goal',
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.goalQ',
    why: 'onboarding.goalWhy',
  },
  {
    id: 'channels',
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.channelsQ',
    why: 'onboarding.channelsWhy',
  },
  {
    id: 'truth',
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.truthQ',
    why: 'onboarding.truthWhy',
  },
  {
    id: 'promise',
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.promiseQ',
    why: 'onboarding.promiseWhy',
  },
  {
    id: 'payment',
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.paymentQ',
    why: 'onboarding.paymentWhy',
  },
  {
    id: 'recovery',
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.recoveryQ',
    why: 'onboarding.recoveryWhy',
  },
  {
    id: 'logistics',
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.logisticsQ',
    why: 'onboarding.logisticsWhy',
  },
  {
    id: 'changes',
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.changesQ',
    why: 'onboarding.changesWhy',
  },
  {
    id: 'policy',
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.policyQ',
    why: 'onboarding.policyWhy',
  },
  {
    id: 'owners',
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.ownersQ',
    why: 'onboarding.ownersWhy',
  },
  {
    id: 'consent',
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.consentQ',
    why: 'onboarding.consentWhy',
  },
  {
    id: 'aftercare',
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.aftercareQ',
    why: 'onboarding.aftercareWhy',
  },
  {
    id: 'pilarClaims',
    brands: ['pilar'],
    title: 'onboarding.pilarClaimsQ',
    why: 'onboarding.pilarClaimsWhy',
  },
  {
    id: 'pilarCart',
    brands: ['pilar'],
    title: 'onboarding.pilarCartQ',
    why: 'onboarding.pilarCartWhy',
  },
  {
    id: 'rasmiawFit',
    brands: ['rasmiaw'],
    title: 'onboarding.rasmiawFitQ',
    why: 'onboarding.rasmiawFitWhy',
  },
  {
    id: 'rasmiawBenefit',
    brands: ['rasmiaw'],
    title: 'onboarding.rasmiawBenefitQ',
    why: 'onboarding.rasmiawBenefitWhy',
  },
  {
    id: 'rasmiawPending',
    brands: ['rasmiaw'],
    title: 'onboarding.rasmiawPendingQ',
    why: 'onboarding.rasmiawPendingWhy',
  },
  {
    id: 'codConfirm',
    brands: ['contraentrega'],
    title: 'onboarding.codConfirmQ',
    why: 'onboarding.codConfirmWhy',
  },
  {
    id: 'codCoverage',
    brands: ['contraentrega'],
    title: 'onboarding.codCoverageQ',
    why: 'onboarding.codCoverageWhy',
  },
  {
    id: 'codFailed',
    brands: ['contraentrega'],
    title: 'onboarding.codFailedQ',
    why: 'onboarding.codFailedWhy',
  },
  {
    id: 'codReconcile',
    brands: ['contraentrega'],
    title: 'onboarding.codReconcileQ',
    why: 'onboarding.codReconcileWhy',
  },
  {
    id: 'launch',
    brands: ['pilar', 'rasmiaw', 'contraentrega'],
    title: 'onboarding.launchQ',
    why: 'onboarding.launchWhy',
  },
];
