// Read-only configuration snapshot. Bodies retain the customer's original language.
export interface OriginalTemplate {
  id: string;
  name: string;
  language: string;
  body: string;
  header: string;
  footer: string;
  buttons: { text: string; type: string; url: string; urlVariable: string }[];
  metaStatus: string;
  usage: 'active' | 'draft' | 'blocked' | 'available';
  flows: string[];
  variables: Record<string, string>;
}
export const templateSnapshotDate = '2026-09-10';
export const originals: Record<string, OriginalTemplate[]> = {
  pilar: [
    {
      id: 'pilar-template-0',
      name: 'recompra_1',
      language: 'es',
      body: 'Hola ✨\n\nTe saludamos de Pilar Oficial. Queremos pasar un momento por aquí para saber: ¿Cómo ha sido tu experiencia con el Serum hasta ahora? 🌸\n\nPara nosotros es vital saber si ya empezaste a notar esa firmeza y luminosidad extra que brindan la Rosa Mosqueta y la Jojoba en tu rostro y cuello.\n\n¿Algún cambio que te haya sorprendido especialmente? Nos encantaría leerte.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-1',
      name: 'tracking',
      language: 'es',
      body: 'Tu pedido ya está confirmado y fue despachado 🚚 📦 \n\nTe dejamos tu numerito de seguimiento: {{1}} \n\nCualquier cosa que necesites, estamos para ayudarte.\n\n¡Gracias por elegirnos! 💛',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-2',
      name: 'carrito_abandonado',
      language: 'es',
      body: 'Hola, notamos que dejaste algunos artículos en tu carrito. ¡No dejes que se escapen! 🛒\n\nSi tienes alguna duda, ¡estamos aquí para ayudarte!\n\nPuedes completar tu compra fácilmente aquí:',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Terminar Pedido',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: 'abandoned_checkout',
        },
      ],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-3',
      name: 'nuevo_pedido',
      language: 'es',
      body: 'Hola, muchas gracias por tu compra 😊\n\n👉 Si elegiste abonar por transferencia:\n\nNecesitamos que nos envíes por acá el comprobante para confirmar el pago y avanzar con el despacho. Por las dudas, te recordamos nuestro alias: \n\npilarskin\n\nApenas el pago esté validado, activamos el envío\n\n👉 Si pagaste por otro medio:\n\n¡No te preocupes que ya está todo OK! ✅ y en breve te vamos a enviar el número de seguimiento para que puedas ver el estado de tu envío por Andreani\n\nSi tienes alguna pregunta, nos puedes escribir por aquí o por email',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'active',
      flows: ['Nuevo pedido'],
      variables: {},
    },
    {
      id: 'pilar-template-4',
      name: 'carrito_abandonado_pilar_v3',
      language: 'es',
      body: 'Hola {{1}}, guardamos tu Serum Pilar.\n\nSi todavía tienes dudas: no contiene retinol ni ácidos y se usa con 3 o 4 gotas antes de dormir.\n\nRetoma tu compra desde el botón o responde este mensaje si necesitas ayuda con el envío o el pago.',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Retomar compra',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: 'abandoned_checkout',
        },
      ],
      metaStatus: 'Approved',
      usage: 'draft',
      flows: ['Carrito abandonado — 3 intentos'],
      variables: {
        '1': '{{vars.contact_first_name}}',
      },
    },
    {
      id: 'pilar-template-5',
      name: 'pago_rechazado_recuperacion',
      language: 'es',
      body: 'Hola {{1}}, no pudimos procesar el pago de tu pedido por {{2}}.\n\nResponde este mensaje y te ayudamos a completar la compra.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'active',
      flows: ['Pago rechazado'],
      variables: {
        '1': '{{vars.customer_name}}',
        '2': '{{vars.total_price}}',
      },
    },
    {
      id: 'pilar-template-6',
      name: 'carrito_abandonado_2',
      language: 'es',
      body: 'Hola, notamos que dejaste algunos artículos en tu carrito. ¡No dejes que se escapen! 🛒\n\nSi tienes alguna duda, ¡estamos aquí para ayudarte!\n\nPuedes completar tu compra fácilmente aquí:',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Terminar Pedido',
          type: 'URL',
          url: 'https://pilarargentina.store/products/serum-pilar',
          urlVariable: '',
        },
      ],
      metaStatus: 'Approved',
      usage: 'active',
      flows: ['Carrito abandonado'],
      variables: {},
    },
    {
      id: 'pilar-template-7',
      name: 'carrito_abandonado_pilar_v3',
      language: 'es',
      body: 'Hola {{1}}, guardamos tu Serum Pilar.\n\nSi todavía tienes dudas: no contiene retinol ni ácidos y se usa con 3 o 4 gotas antes de dormir.\n\nRetoma tu compra desde el botón o responde este mensaje si necesitas ayuda con el envío o el pago.',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Retomar compra',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: '',
        },
      ],
      metaStatus: 'Approved',
      usage: 'draft',
      flows: ['Carrito abandonado — 3 intentos'],
      variables: {
        '1': '{{vars.contact_first_name}}',
      },
    },
    {
      id: 'pilar-template-8',
      name: 'llamada_pago_pedido',
      language: 'es',
      body: 'Hola {{1}}, aquí tienes el link para pagar el pedido que acabas de confirmar por teléfono: {{2}} Si el pago no se procesa o los datos no coinciden, responde este mensaje y lo revisamos.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-9',
      name: 'llamada_info_producto',
      language: 'es',
      body: 'Hola {{1}}, aquí tienes la información del producto que nos pediste por teléfono: {{2}} Cualquier duda, responde este mensaje y te ayudamos.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-10',
      name: 'seguimiento_llamada',
      language: 'es',
      body: 'Hola {{1}}, te dejamos por aca lo que hablamos recien por telefono: {{2}} Si necesitas algo mas, responde este mensaje y te ayudamos.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-11',
      name: 'pago_pendiente_3',
      language: 'es',
      body: 'Hola {{1}}, tu pedido {{2}} por {{3}} sigue sin pago y no vamos a poder seguir reservándolo.\n\nAlias: pilarskin\n\nSi ya transferiste, envíanos el comprobante por aquí y lo activamos.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'draft',
      flows: ['Pago pendiente'],
      variables: {
        '1': '{{vars.customer_name}}',
        '2': '{{vars.order_name}}',
        '3': '{{vars.total_price}}',
      },
    },
    {
      id: 'pilar-template-12',
      name: 'pago_pendiente_2',
      language: 'es',
      body: 'Hola {{1}}, seguimos guardando tu pedido {{2}} por {{3}}.\n\nAlias: pilarskin\n\nSi tuviste algún problema con la transferencia, escríbenos por aquí y lo resolvemos.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'draft',
      flows: ['Pago pendiente'],
      variables: {
        '1': '{{vars.customer_name}}',
        '2': '{{vars.order_name}}',
        '3': '{{vars.total_price}}',
      },
    },
    {
      id: 'pilar-template-13',
      name: 'llamada_link_de_pago',
      language: 'es',
      body: 'Hola {{1}}, como acabamos de hablar por teléfono, aquí tienes el link para completar tu compra: {{2}} Si tienes algún problema al pagar, responde este mensaje y te ayudamos.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-14',
      name: 'carrito_abandonado_pilar_v4',
      language: 'es',
      body: 'Hola {{1}}, te escribo de nuevo por el Serum Pilar que dejaste en tu carrito.\n\nSi te frenó la duda de cómo usarlo: aplica 3 o 4 gotas por la noche, antes de dormir. No contiene retinol ni ácidos.\n\nPuedes retomar tu compra abajo o responderme si necesitas ayuda con el envío o el pago.',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Retomar compra',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: 'abandoned_checkout',
        },
      ],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-15',
      name: 'carrito_abandonado_pilar_v5',
      language: 'es',
      body: 'Hola {{1}}, este es el último recordatorio sobre tu Serum Pilar.\n\nTu carrito sigue disponible si todavía quieres completar la compra. Puedes retomarlo desde el botón.\n\nSi tienes alguna duda, responde este mensaje. Si no, cerramos el seguimiento aquí.',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Retomar compra',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: 'abandoned_checkout',
        },
      ],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-16',
      name: 'llamada_lo_que_pediste',
      language: 'es',
      body: 'Hola {{1}}, te enviamos lo que nos pediste durante la llamada: {{2}} Si necesitas que lo corrijamos o falta algún dato, responde este mensaje.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-17',
      name: 'llamada_seguimiento_envio',
      language: 'es',
      body: 'Hola {{1}}, aquí tienes el seguimiento de tu pedido, como te comentamos por teléfono: {{2}} Si el envío no avanza en las próximas horas, responde este mensaje y lo revisamos.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-18',
      name: 'pago_pendiente_1',
      language: 'es',
      body: 'Hola {{1}}, tu pedido {{2}} por {{3}} quedó reservado y estamos esperando la transferencia.\n\nAlias: pilarskin\n\nCuando la hagas, envíanos el comprobante por aquí y activamos el envío.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'draft',
      flows: ['Pago pendiente'],
      variables: {
        '1': '{{vars.customer_name}}',
        '2': '{{vars.order_name}}',
        '3': '{{vars.total_price}}',
      },
    },
    {
      id: 'pilar-template-19',
      name: 'llamada_resumen_pedido',
      language: 'es',
      body: 'Hola {{1}}, te confirmamos por escrito lo que acordamos en la llamada: {{2}} Si algo no coincide, responde este mensaje y lo corregimos antes de despachar.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-20',
      name: 'tracking_envio',
      language: 'es',
      body: 'Tu pedido ya está confirmado y fue despachado 🚚 📦 \n\nTe dejamos el seguimiento de tu envío: {{1}} \n\nCualquier cosa que necesites, estamos para ayudarte.\n\n¡Gracias por elegirnos! 💛',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'active',
      flows: ['Enviar tracking'],
      variables: {
        '1': '{{vars.tracking_url}}',
      },
    },
    {
      id: 'pilar-template-21',
      name: 'carrito_abandonado_pilar_intento_3',
      language: 'es',
      body: 'Hola {{1}}, este es el último mensaje sobre tu Serum Pilar.\n\nSi el cuello te hace evitar escotes o buscar otro ángulo en las fotos, esperar mantiene todo igual. Los cambios necesitan constancia: las 8 semanas empiezan la noche en que empiezas tú.\n\nTu carrito sigue disponible ahora. Retómalo desde el botón antes de que cerremos este seguimiento.',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Empezar ahora',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: '',
        },
      ],
      metaStatus: 'Approved',
      usage: 'draft',
      flows: ['Carrito abandonado — 3 intentos'],
      variables: {
        '1': '{{vars.contact_first_name}}',
      },
    },
    {
      id: 'pilar-template-22',
      name: 'carrito_abandonado_pilar_intento_2',
      language: 'es',
      body: 'Hola {{1}}, tu Serum Pilar sigue guardado.\n\nLa piel del cuello produce menos grasa que la del rostro. Por eso muchas cremas faciales se quedan cortas y los activos fuertes pueden irritarla.\n\nPilar se aplica en 60 segundos, con 3 o 4 gotas antes de dormir. En el estudio de la marca, el 94% mostró la piel visiblemente más tensa a las 8 semanas y no se reportó irritación.\n\nRetoma tu compra desde el botón. Si algo te frena, responde y te ayudo.',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Retomar compra',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: '',
        },
      ],
      metaStatus: 'Approved',
      usage: 'draft',
      flows: ['Carrito abandonado — 3 intentos'],
      variables: {
        '1': '{{vars.contact_first_name}}',
      },
    },
    {
      id: 'pilar-template-23',
      name: 'llamada_datos_transferencia',
      language: 'es',
      body: 'Hola {{1}}, te dejamos los datos para la transferencia que acabamos de conversar: {{2}} Cuando la hagas, envíanos el comprobante por aquí y activamos tu envío.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-24',
      name: 'carrito_abandonado_pilar_intento_3',
      language: 'es',
      body: 'Hola {{1}}, este es el último mensaje sobre tu Serum Pilar.\n\nSi el cuello te hace evitar escotes o buscar otro ángulo en las fotos, esperar mantiene todo igual. Los cambios necesitan constancia: las 8 semanas empiezan la noche en que empiezas tú.\n\nTu carrito sigue disponible ahora. Retómalo desde el botón antes de que cerremos este seguimiento.',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Empezar ahora',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: 'abandoned_checkout',
        },
      ],
      metaStatus: 'Approved',
      usage: 'draft',
      flows: ['Carrito abandonado — 3 intentos'],
      variables: {
        '1': '{{vars.contact_first_name}}',
      },
    },
    {
      id: 'pilar-template-25',
      name: 'carrito_abandonado_pilar_intento_2',
      language: 'es',
      body: 'Hola {{1}}, tu Serum Pilar sigue guardado.\n\nLa piel del cuello produce menos grasa que la del rostro. Por eso muchas cremas faciales se quedan cortas y los activos fuertes pueden irritarla.\n\nPilar se aplica en 60 segundos, con 3 o 4 gotas antes de dormir. En el estudio de la marca, el 94% mostró la piel visiblemente más tensa a las 8 semanas y no se reportó irritación.\n\nRetoma tu compra desde el botón. Si algo te frena, responde y te ayudo.',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Retomar compra',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: 'abandoned_checkout',
        },
      ],
      metaStatus: 'Approved',
      usage: 'draft',
      flows: ['Carrito abandonado — 3 intentos'],
      variables: {
        '1': '{{vars.contact_first_name}}',
      },
    },
    {
      id: 'pilar-template-26',
      name: 'carrito_abandonado_pilar_v5',
      language: 'es',
      body: 'Hola {{1}}, este es el último recordatorio sobre tu Serum Pilar.\n\nTu carrito sigue disponible si todavía quieres completar la compra. Puedes retomarlo desde el botón.\n\nSi tienes alguna duda, responde este mensaje. Si no, cerramos el seguimiento aquí.',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Retomar compra',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: '',
        },
      ],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-27',
      name: 'carrito_abandonado_pilar_v4',
      language: 'es',
      body: 'Hola {{1}}, te escribo de nuevo por el Serum Pilar que dejaste en tu carrito.\n\nSi te frenó la duda de cómo usarlo: aplica 3 o 4 gotas por la noche, antes de dormir. No contiene retinol ni ácidos.\n\nPuedes retomar tu compra abajo o responderme si necesitas ayuda con el envío o el pago.',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Retomar compra',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: '',
        },
      ],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-28',
      name: 'carrito_abandonado',
      language: 'es',
      body: 'Hola, notamos que dejaste algunos artículos en tu carrito. ¡No dejes que se escapen! 🛒\n\nSi tienes alguna duda, ¡estamos aquí para ayudarte!\n\nPuedes completar tu compra fácilmente aquí:',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Terminar Pedido',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: '',
        },
      ],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'pilar-template-29',
      name: 'nuevo_pedido_two',
      language: 'es',
      body: 'Hola, muchas gracias por tu compra 😊\n\n👉 Si elegiste abonar por transferencia:\n\nNecesitamos que nos envíes por acá el comprobante para confirmar el pago y avanzar con el despacho. Por las dudas, te recordamos nuestro alias: \n\npilarskin.arg\n\nApenas el pago esté validado, activamos el envío\n\n👉 Si pagaste por otro medio:\n\n¡No te preocupes que ya está todo OK! ✅ y en breve te vamos a enviar el número de seguimiento para que puedas ver el estado de tu envío por Andreani\n\nSi tienes alguna pregunta, nos puedes escribir por aquí o por email',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
  ],
  rasmiaw: [
    {
      id: 'rasmiaw-template-0',
      name: 'rasmiaw_beneficio_contraentrega_v2',
      language: 'es',
      body: '🎈 ¡Tenemos un beneficio para ti!\n\nSi cambias tu forma de pago y eliges pagar por Transferencia, Llave, Bold o Addi, recibirás un 5% de descuento en tu compra. 💛\n\nAsí podremos gestionar tu pedido más rápido, evitar retrasos y lograr que tu michi disfrute de su rascador lo antes posible. 😻\n\nResponde “RECIBIR BENEFICIO” para cambiar el método de pago.\n\nResponde “MANTENER CONTRAENTREGA” si prefieres conservar tu pago contra entrega.',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'RECIBIR BENEFICIO',
          type: 'QUICK_REPLY',
          url: '',
          urlVariable: '',
        },
        {
          text: 'MANTENER CONTRAENTREGA',
          type: 'QUICK_REPLY',
          url: '',
          urlVariable: '',
        },
      ],
      metaStatus: 'Approved',
      usage: 'active',
      flows: ['Rasmiaw · Nuevo pedido'],
      variables: {},
    },
    {
      id: 'rasmiaw-template-1',
      name: 'rasmiaw_recordatorio_contraentrega_v2',
      language: 'es',
      body: '¿Te ayudamos a finalizar tu pedido? 😻\n\nAprovecha tu 5% de descuento y recibe tu Rasmiaw sin complicaciones. 💛\n\nResponde “RECIBIR BENEFICIO” para cambiar tu método de pago y aplicar el descuento.\n\nResponde “MANTENER CONTRAENTREGA” si prefieres conservar tu pago contra entrega.',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'RECIBIR BENEFICIO',
          type: 'QUICK_REPLY',
          url: '',
          urlVariable: '',
        },
        {
          text: 'MANTENER CONTRAENTREGA',
          type: 'QUICK_REPLY',
          url: '',
          urlVariable: '',
        },
      ],
      metaStatus: 'Approved',
      usage: 'active',
      flows: ['Rasmiaw · Nuevo pedido'],
      variables: {},
    },
    {
      id: 'rasmiaw-template-2',
      name: 'riverz_como_te_fue',
      language: 'es',
      body: 'Hola {{1}}, ¿cómo te fue con {{2}}?\n\nSi algo no salió como esperabas, respondes por acá y lo resolvemos.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'rasmiaw-template-3',
      name: 'riverz_pago_rechazado',
      language: 'es',
      body: 'Hola {{1}}, tu pago de {{2}} no pasó. Casi siempre es el límite de la tarjeta o un dato mal copiado, así que tu pedido sigue guardado.\n\nLo intentas otra vez con el mismo medio o con otro, y no pierdes nada de lo que elegiste.\n\n¿Te paso el link de pago?',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'rasmiaw-template-4',
      name: 'riverz_carrito_abandonado',
      language: 'es',
      body: 'Hola {{1}}, te guardamos el carrito tal como lo dejaste.\n\nNo tienes que elegir nada de nuevo: lo retomas donde ibas en {{2}} y en un minuto queda.\n\n¿Lo terminamos?',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'rasmiaw-template-5',
      name: 'rasmiaw_carrito_abandonado_2',
      language: 'es',
      body: '¡Tu michi todavía está esperando!\n\nRetoma tu carrito y obtén un 10% de descuento por completar tu compra. 🎉\n\n¡No dejes que se te escape!\n\nAquí puedes completar tu compra de forma fácil y rápida…',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Completar con 10% OFF',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: 'abandoned_checkout',
        },
      ],
      metaStatus: 'Approved',
      usage: 'active',
      flows: ['Rasmiaw · Carrito abandonado'],
      variables: {},
    },
    {
      id: 'rasmiaw-template-6',
      name: 'rasmiaw_pago_rechazado',
      language: 'es',
      body: '¡Ups! Algo salió mal con tu pago. 😿\n\nNo pudimos procesar tu pedido a través de Mercado Pago, pero no te preocupes, ¡tu carrito sigue esperándote! 😻\n\nResponde este mensaje y te ofreceremos otras formas de pago para que puedas completar tu compra fácilmente.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'blocked',
      flows: ['Rasmiaw · Pago rechazado'],
      variables: {},
    },
    {
      id: 'rasmiaw-template-7',
      name: 'rasmiaw_carrito_abandonado_1',
      language: 'es',
      body: '¡No dejes que se te escape!\n\nNuestro rascador te ayudará a que tu gato desgaste sus uñas, libere estrés, se mantenga activo y tenga su propio espacio para rascar, jugar y descansar. 😻\n\nCompleta tu compra de forma fácil y rápida y vive la experiencia Rasmiaw.',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'Volver a mi carrito',
          type: 'URL',
          url: 'https://riverz.co/r/{{1}}',
          urlVariable: 'product',
        },
      ],
      metaStatus: 'Approved',
      usage: 'active',
      flows: ['Rasmiaw · Carrito abandonado'],
      variables: {},
    },
    {
      id: 'rasmiaw-template-8',
      name: 'riverz_pedido_en_camino',
      language: 'es',
      body: 'Hola {{1}}, tu pedido {{2}} ya salió.\n\nLo sigues acá: {{3}}\n\nCualquier cosa que necesites con la entrega, respondes por este chat.',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'rasmiaw-template-9',
      name: 'riverz_esperando_transferencia',
      language: 'es',
      body: 'Hola {{1}}, tu pedido {{2}} por {{3}} quedó reservado a tu nombre y esperando la transferencia.\n\nApenas la hagas, mándanos el comprobante por aquí y lo preparamos el mismo día.\n\n¿Necesitas los datos de la cuenta?',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'available',
      flows: [],
      variables: {},
    },
    {
      id: 'rasmiaw-template-10',
      name: 'rasmiaw_preparando_pedido',
      language: 'es',
      body: '¡Estamos preparando tu pedido de Rasmiaw! 💛\n\nQueremos contarte que tu pedido de Rasmiaw está en proceso de alistamiento y personalización 🎨🐾\n\nCada rascador lo hacemos especialmente para ti, eligiendo colores y juguetes con mucho cuidado, por eso nos toma unos días dejarlo perfecto ✨\n\nTe estaremos enviando un mensaje tan pronto esté listo, preparado y despachado 🚚\n\n¡Gracias por tu paciencia y por apoyar lo hecho con amor! 💛\n\nSi tienes alguna pregunta escríbenos por este medio',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'active',
      flows: ['Rasmiaw · Nuevo pedido'],
      variables: {},
    },
    {
      id: 'rasmiaw-template-11',
      name: 'rasmiaw_ultima_oportunidad_contraentrega_v2',
      language: 'es',
      body: '🚨 ¡Última oportunidad!\n\nSubimos tu beneficio al 10% de descuento 🎉, este beneficio es por tiempo limitado.\n\nSi quieres aprovecharlo, responde “RECIBIR BENEFICIO” y te ayudaremos a finalizar tu compra.\n\nSi prefieres mantener tu pedido original, responde “MANTENER CONTRAENTREGA” para conservar tu pago contra entrega.\n\nVálido durante las próximas 24 horas. 🏃',
      header: '',
      footer: '',
      buttons: [
        {
          text: 'RECIBIR BENEFICIO',
          type: 'QUICK_REPLY',
          url: '',
          urlVariable: '',
        },
        {
          text: 'MANTENER CONTRAENTREGA',
          type: 'QUICK_REPLY',
          url: '',
          urlVariable: '',
        },
      ],
      metaStatus: 'Approved',
      usage: 'active',
      flows: ['Rasmiaw · Nuevo pedido'],
      variables: {},
    },
    {
      id: 'rasmiaw-template-12',
      name: 'rasmiaw_envio_tracking',
      language: 'es',
      body: 'Me da gusto saludarte,\n\nTe informo, que tu Rasmiaw va en camino hacia tu 🏠!\n\nEnvío guía: {{1}}\n\nSi tienes alguna pregunta escríbenos por este medio',
      header: '',
      footer: '',
      buttons: [],
      metaStatus: 'Approved',
      usage: 'active',
      flows: ['Rasmiaw · Envío'],
      variables: {
        '1': '{{vars.tracking_number}}',
      },
    },
  ],
};
