import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {translate} from '@/lib/i18n/translate';
const h=vi.hoisted(()=>({enabled:true,locale:'es' as 'es'|'en',index:0,bank:[] as unknown[],fetch:vi.fn(),blob:null as Blob|null,click:vi.fn(),revoke:vi.fn()}));
vi.mock('@/lib/ui/improvements-preview',()=>({get SHOW_RIVERZ_IMPROVEMENTS(){return h.enabled;}}));vi.mock('@/hooks/use-locale',()=>({useLocale:()=>({t:(key:string,args?:Record<string,string>)=>translate(h.locale,key,args)})}));vi.mock('@/hooks/use-format',()=>({useFormat:()=>({number:String,dateTime:String})}));
vi.mock('next/link',()=>({default:({children,...props}:Record<string,unknown>)=>React.createElement('a',props,children as React.ReactNode)}));
vi.mock('react',async()=>({...await vi.importActual<typeof import('react')>('react'),useState:(initial:unknown)=>{const i=h.index++;if(!(i in h.bank))h.bank[i]=initial;return[h.bank[i],(next:unknown)=>{h.bank[i]=typeof next==='function'?next(h.bank[i]):next;}];},useRef:(initial:unknown)=>{const i=h.index++;if(!(i in h.bank))h.bank[i]={current:initial};return h.bank[i];},useEffect:vi.fn()}));
import {FlowMetricDetails} from './metric-details';
const flow='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222',conv='33333333-3333-4333-8333-333333333333';
const view={flow_id:flow,from_at:'2026-09-24T00:00:00Z',through_at:'2026-10-01T00:00:00Z',days:7,attribution:'recorded_execution',total_runs:1,node_entries:2,by_node:{start:2},by_status:{completed:1},evidence_filter:{node_key:null,status:null},matched_runs:1,records:[{id,conversation_id:conv,status:'completed',started_at:'2026-09-25T12:00:00.123456Z',ended_at:null}],next_cursor:null};
type Element=React.ReactElement<Record<string,unknown>>;
function nodes(node:React.ReactNode):Element[]{if(Array.isArray(node))return node.flatMap(nodes);if(!React.isValidElement(node))return[];const item=node as Element;return[item,...nodes(item.props.children as React.ReactNode)];}
function render(){h.index=0;return FlowMetricDetails({flowId:flow});}
function find(type:string,index=0){const node=nodes(render()).filter(item=>item.type===type)[index];if(!node)throw new Error('Missing '+type);return node;}
async function open(){const target={open:true};(find('details').props.onToggle as(event:unknown)=>void)({target,currentTarget:target});await vi.waitFor(()=>expect(h.bank[0]).not.toBeNull());}
function button(text:string){const item=nodes(render()).filter(node=>node.type==='button').find(node=>renderToStaticMarkup(node).includes(text));if(!item)throw new Error('Missing button '+text);return item;}
beforeEach(()=>{vi.clearAllMocks();h.enabled=true;h.locale='es';h.bank=[];h.blob=null;h.fetch.mockImplementation(async()=>new Response(JSON.stringify(view)));vi.stubGlobal('fetch',h.fetch);vi.spyOn(URL,'createObjectURL').mockImplementation(blob=>{h.blob=blob as Blob;return 'blob:synthetic';});vi.spyOn(URL,'revokeObjectURL').mockImplementation(h.revoke);});
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();});
describe('Flow metrics remain optional and export the observed cohort',()=>{
 it.each(['es','en'] as const)('stays hidden outside comparison in %s',locale=>{h.locale=locale;h.enabled=false;expect(renderToStaticMarkup(render())).toBe('');expect(h.fetch).not.toHaveBeenCalled();});
 it.each(['es','en'] as const)('loads on opening and links source cases in %s',async locale=>{h.locale=locale;render();expect(h.fetch).not.toHaveBeenCalled();await open();const html=renderToStaticMarkup(render());expect(html).toContain('/bandeja?c='+conv);expect(html).toContain(translate(locale,'flows.runStatusCompleted'));expect(html).not.toContain('flows.metric');expect(html).not.toContain('completed:');});
 it('opens node evidence using the same observation window',async()=>{await open();h.fetch.mockImplementation(async()=>new Response(JSON.stringify({...view,days:null,evidence_filter:{node_key:'start',status:null}})));(button('start:').props.onClick as()=>void)();await vi.waitFor(()=>expect(h.bank[3]).toBe(false));const url=new URL(h.fetch.mock.calls[1][0],'https://riverz.co');expect(url.searchParams.get('from')).toBe(view.from_at);expect(url.searchParams.get('through')).toBe(view.through_at);expect(url.searchParams.get('node_key')).toBe('start');});
 it('does not reload when a nested node detail opens',async()=>{await open();(find('details').props.onToggle as(event:unknown)=>void)({currentTarget:{open:true},target:{open:true}});expect(h.fetch).toHaveBeenCalledTimes(1);});
 it('does not show failed reads as zero runs',async()=>{await open();h.fetch.mockResolvedValue(new Response('{}',{status:503}));(button(translate('es','flows.metricRefresh')).props.onClick as()=>void)();await vi.waitFor(()=>expect(h.bank[0]).toBeNull());const html=renderToStaticMarkup(render());expect(html).toContain('role="alert"');expect(html).not.toContain(translate('es','flows.metricRuns')+': 0');});
 it.each(['es','en'] as const)('exports the observed summary with BOM and formula-safe references in %s',async locale=>{h.locale=locale;h.fetch.mockImplementation(async()=>new Response(JSON.stringify({...view,by_node:{'=SUM(A1)':2}})));await open();vi.stubGlobal('document',{createElement:()=>({click:h.click})});(button(translate(locale,'flows.metricDownload')).props.onClick as()=>void)();expect(h.fetch).toHaveBeenCalledTimes(1);expect(h.click).toHaveBeenCalledOnce();expect(h.revoke).toHaveBeenCalledWith('blob:synthetic');expect(Array.from(new Uint8Array(await h.blob!.arrayBuffer())).slice(0,3)).toEqual([239,187,191]);const csv=await h.blob!.text();expect(csv).toContain("'=SUM(A1)");expect(csv).toContain(view.from_at);expect(csv).not.toContain(conv);});
 it('rejects a report from another flow or an unrequested source filter',async()=>{for(const bad of [{...view,flow_id:id},{...view,evidence_filter:{node_key:'foreign',status:null}}]){h.bank=[];h.fetch.mockResolvedValue(new Response(JSON.stringify(bad)));const target={open:true};(find('details').props.onToggle as(event:unknown)=>void)({target,currentTarget:target});await vi.waitFor(()=>expect(h.bank[3]).toBe(false));expect(h.bank[0]).toBeNull();expect(renderToStaticMarkup(render())).toContain('role="alert"');}});
});
