import { describe, it, expect } from 'vitest'
import { buildResearchPrompt, parseResearchResponse } from './research'

/**
 * Tests the research pipeline with a model reply generated IN-SESSION by
 * Claude (this agent) instead of a live paid API call — proving the
 * prompt→parse→persist plumbing produces correct product fields before we
 * spend Anthropic credits. The fixture below is a genuine reply for the real
 * "Serum Pilar" product (a facial serum, Spanish store), wrapped in a little
 * prose to exercise the JSON-in-prose extraction too.
 */

const product = {
  title: 'Serum Pilar',
  description: '',
  product_type: '',
  vendor: 'Mi tienda',
  tags: [],
  custom_notes: null,
  structured_research: null,
  say_guidelines: null,
  never_say: [],
  escalation_triggers: [],
  price_min: 39990,
  price_max: 99900,
  bundle_app: null,
  custom_faqs: [],
}

const scrapedContent = `Serum Pilar — sérum facial hidratante.
¡Lleva más, paga menos!
1 Unidad $39.990,00
2 Unidades + 1 GRATIS $69.900,00
3 Unidades + 1 GRATIS $99.900,00
Envío gratis + regalo sorpresa.`

// --- Model reply generated by Claude (this session), as the ai-research route
//     would receive from the Anthropic API. ---
const MODEL_REPLY = `Claro, aquí tienes el material de soporte:

{
  "description": "Serum Pilar es un sérum facial concentrado que hidrata en profundidad y ayuda a unificar el tono de la piel. Su textura ligera se absorbe rápido y deja la piel luminosa sin sensación grasa. Ideal para el uso diario, de día y de noche.",
  "faqs": [
    {"q": "¿Cómo se usa el sérum?", "a": "Aplica 2 o 3 gotas sobre la piel limpia, mañana y noche, antes de tu crema hidratante."},
    {"q": "¿Sirve para piel grasa?", "a": "Sí. Su textura es ligera y de rápida absorción, así que funciona bien en piel grasa, mixta, seca o normal."},
    {"q": "¿Cuánto dura un frasco?", "a": "Con el uso diario recomendado, un frasco suele rendir entre 6 y 8 semanas."},
    {"q": "¿En cuánto tiempo se ven resultados?", "a": "La hidratación se nota desde los primeros días; el tono y la luminosidad, a partir de 3 o 4 semanas de uso constante."},
    {"q": "¿Se puede usar con maquillaje?", "a": "Sí, aplícalo antes de la crema y el maquillaje; al absorberse rápido sirve muy bien como base hidratante."},
    {"q": "¿Hacen envíos y cuánto demora?", "a": "Sí, enviamos a todo el país y te compartimos el número de seguimiento apenas despachamos."},
    {"q": "¿Puedo devolverlo si no me gusta?", "a": "Sí, contamos con política de devolución; escríbenos y te ayudamos con el proceso."}
  ],
  "research": "Serum Pilar es para personas que buscan una rutina de skincare simple y efectiva, enfocada en hidratación y luminosidad. Se compra para el cuidado diario o como primer sérum. Destaca por su textura ligera y absorción rápida. Las objeciones más comunes son el precio y la duda de si sirve para su tipo de piel.",
  "differentiators": [
    "Textura ligera de rápida absorción, sin sensación grasa",
    "Apto para todo tipo de piel, incluida la grasa",
    "Hidratación profunda y luminosidad en un solo paso",
    "Rinde 6-8 semanas con el uso diario"
  ],
  "objections": [
    {"objection": "Es caro", "rebuttal": "Un frasco rinde 6-8 semanas, así que el costo por día es bajo. Además hay packs con mejor precio por unidad."},
    {"objection": "No sé si sirve para mi piel", "rebuttal": "Su fórmula ligera funciona en piel seca, mixta, grasa y normal. Cuéntame tu tipo de piel y te confirmo."},
    {"objection": "¿Y si no veo resultados?", "rebuttal": "La hidratación se nota desde los primeros días; para tono y luminosidad, dale 3-4 semanas de uso constante."}
  ],
  "say_guidelines": "Enfatiza la textura ligera, que sirve para todo tipo de piel y el rendimiento por frasco. Ante el precio, menciona los packs con mejor precio por unidad.",
  "never_say": [
    "No prometas que cura o trata enfermedades de la piel (acné severo, rosácea, dermatitis).",
    "No garantices resultados en un plazo exacto ni que funciona igual para todas las personas."
  ],
  "escalation": [
    "Reacciones adversas o alergias en la piel",
    "Reclamos, reembolsos o problemas con un pedido ya pagado"
  ]
}

Espero que te sea útil.`

describe('buildResearchPrompt', () => {
  it('includes the product title, scraped content, and the localized output language', () => {
    const es = buildResearchPrompt(product, scrapedContent, 'es')
    expect(es).toContain('Serum Pilar')
    expect(es).toContain('Contenido de la página del producto')
    expect(es).toContain('2 Unidades + 1 GRATIS')
    const en = buildResearchPrompt(product, scrapedContent, 'en')
    // The output-language directive differs per locale.
    expect(en).not.toEqual(es)
  })
})

describe('parseResearchResponse — Serum Pilar (model reply generated this session)', () => {
  const { update, faqsCount } = parseResearchResponse(
    MODEL_REPLY,
    product,
    scrapedContent,
    'es',
  )

  it('marks the run done and keeps 5-10 valid FAQs', () => {
    expect(update.ai_research_status).toBe('done')
    const faqs = update.ai_generated_faqs as Array<{ q: string; a: string }>
    expect(faqs.length).toBe(7)
    expect(faqsCount).toBe(7)
    for (const f of faqs) {
      expect(f.q.trim()).not.toBe('')
      expect(f.a.trim()).not.toBe('')
    }
  })

  it('fills the empty description and a research brief', () => {
    expect(String(update.description)).toMatch(/^Serum Pilar es un sérum/)
    expect(String(update.ai_research)).toContain('rutina de skincare')
  })

  it('extracts structured differentiators + objections', () => {
    const sr = update.structured_research as {
      differentiators: string[]
      objections: Array<{ objection: string; rebuttal: string }>
    }
    expect(sr.differentiators).toHaveLength(4)
    expect(sr.objections).toHaveLength(3)
    expect(sr.objections[0]).toEqual({
      objection: 'Es caro',
      rebuttal: expect.stringContaining('costo por día'),
    })
  })

  it('captures never_say + escalation guardrails (health-sensitive)', () => {
    expect(update.never_say as string[]).toHaveLength(2)
    expect((update.never_say as string[])[0]).toMatch(/cura o trata enfermedades/)
    expect(update.escalation_triggers as string[]).toHaveLength(2)
  })

  it('compiles training_material the runner will inject live', () => {
    const tm = String(update.training_material)
    expect(tm).toContain('# Serum Pilar')
    expect(tm).toContain('## Descripción')
    expect(tm).toContain('## Preguntas frecuentes')
    expect(tm).toContain('¿Cómo se usa el sérum?')
    expect(tm).toContain('## Investigación adicional')
    expect(tm).toContain('rutina de skincare')
  })
})

describe('parseResearchResponse — safety behaviors', () => {
  it('does NOT overwrite a description the merchant already wrote', () => {
    const withDesc = { ...product, description: 'Mi descripción propia.' }
    const { update } = parseResearchResponse(MODEL_REPLY, withDesc, scrapedContent, 'es')
    expect(update.description).toBeUndefined()
    // ...but the AI arrays still refresh.
    expect((update.ai_generated_faqs as unknown[]).length).toBe(7)
  })

  it('throws when the reply has no JSON object', () => {
    expect(() => parseResearchResponse('no hay json aquí', product, scrapedContent, 'es')).toThrow()
  })
})
