import type { Locale } from "./config";

/**
 * AI generation language helpers.
 *
 * Merchant-facing content generated by the Anthropic API — product research
 * (FAQs / differentiators / objections / sales copy), the agent persona &
 * system prompt, and AI-built flow node messages — must come back in the
 * MERCHANT's language, not always Spanish. The prompt scaffolding (the
 * instructions to the model) can stay in Spanish; these helpers provide the
 * OUTPUT-language directive/labels to thread in so a new English merchant
 * gets English research, an English agent, and English flows end to end.
 *
 * The signal is the merchant's UI locale (`getLocale()` / `riverz_locale`),
 * or the agent's own `ai_agents.language` when an agent is in scope.
 */

/** Locale a generation directive can target (a free-text agent `language`
 *  column may hold values beyond es/en, so we normalize first). */
export function normalizeAiLocale(value: string | null | undefined): Locale {
  return value === "en" ? "en" : "es";
}

/** Short inline label, e.g. `respuesta breve en ${aiLangLabel(locale)}`. */
export function aiLangLabel(locale: Locale): string {
  return locale === "en" ? "inglés natural (en-US)" : "español neutro sin voseo";
}

/** Strong standalone directive to prepend to a generation prompt. */
export function aiLangDirective(locale: Locale): string {
  return locale === "en"
    ? "IMPORTANTE: Devuelve TODO el contenido generado en inglés natural (en-US)."
    : "IMPORTANTE: Devuelve TODO el contenido generado en español neutro, sin voseo.";
}

/** English name of the language, for prompts authored in English. */
export function aiLangName(locale: Locale): string {
  return locale === "en" ? "English" : "Spanish";
}
