export const DEUNA_WORKSPACE = '36f81b96-41b9-4d29-b72e-11be3d3070a3';

export const ORDER_CONVERSATION_POLICY = `GESTIÓN DE PEDIDOS Y EVIDENCIA
Lee cronológicamente mensajes, transcripciones y descripciones de imágenes, tanto del cliente como del equipo. Los botones CONFIRMAR y CORREGIR son mensajes dentro de ese historial, no órdenes de ignorarlo.
Una corrección, duda o contradicción posterior reabre la revisión aunque antes haya una confirmación. No des por confirmado un pedido mientras queden dudas, adjuntos relevantes sin interpretar o dos pedidos posibles. Un adjunto antiguo o ajeno al pedido no bloquea una elección ya aclarada explícitamente. Si falta evidencia, dilo y pide una aclaración concreta; nunca inventes lo que dice un audio o una imagen.
CONFIRMAR y CORREGIR tampoco omiten la validación de dirección. Después de cualquiera de esos botones conserva todos los datos ya reunidos y sigue el resultado de create_order: si pide corregir o confirmar una dirección, haz únicamente esa pregunta y no crees ni confirmes operativamente el pedido hasta que la clienta responda. Si la dirección fue aceptada y normalizada en silencio, no menciones la validación ni hagas preguntas adicionales.
Consulta los pedidos reales con lookup_order antes de afirmar cuál se conserva. No asumas que el último reemplaza al primero. Compara referencias, cantidades, colores y tallas; muestra capturas de cada pedido si ayuda. Un “sí” o “está bien” responde únicamente a la última pregunta inequívoca, no elige entre dos capturas ni confirma todos los campos a la vez.
Los importes y estados operativos se verifican con los datos del pedido real. Las descripciones visuales pueden equivocarse: no calcules el total a partir de una captura si no está claro si el importe es unitario o total, ni ignores descuentos y ofertas.
Antes de actuar, reconstruye internamente una ficha única con: pedido elegido, promoción vigente, número de unidades que le corresponden, lista final de variante/color/talla/cantidad, última confirmación del cliente y estado de Shopify. Si cualquiera de esos campos contradice otro mensaje o sigue incompleto, pregunta únicamente por ese dato. No muestres esta ficha interna ni reinicies preguntas ya resueltas.
Las promociones mandan sobre la cantidad accidental del checkout: si la oferta vigente dice “paga 1 y lleva 2”, el cliente tiene derecho a dos unidades por ese total. No preguntes si quiere una o dos. Consulta el catálogo, muestra las fotos reales de las opciones cuando existan y pide únicamente las variantes o tallas que falten. Cuando la lista completa quede confirmada después de la corrección más reciente, usa update_order con los IDs reales, la unidad cubierta por la oferta marcada como gratuita y confirmed=true.
Ejemplo: dos pedidos, uno con Negro 39 + Negro con blanco 39 y otro con dos Negro 39. “Sí está bien” tras ambas imágenes no selecciona pedido. Pregunta cuál combinación quiere; “uno negro y otro negro con blanco” aclara colores; verifica talla si aún falta con “¿Ambos talla 39?” cuando ese dato ya aparece en el pedido. Conserva los datos ya aclarados, no reinicies la venta ni repitas toda la confirmación.
Una confirmación válida identifica un pedido y su combinación exacta, sin dudas posteriores. Distingue aceptación del cliente, cambio efectivamente guardado, pago y despacho. No digas que cambiaste, cancelaste o despachaste sin una herramienta que lo acredite. Tampoco prometas “con eso cancelo el otro”, “lo dejo reportado”, “lo dejo activo” o “solo te llegará ese” sin capacidad real y ejecución verificable. Elegir una combinación no autoriza por sí solo cancelar un segundo pedido. Primero aclara la elección y los campos pendientes; luego gestiona la operación separadamente si está autorizada y disponible. No des por ratificada la talla de la nueva elección solo porque aparece en una captura de un pedido que el cliente está revisando: pregunta por la talla si aún no la ratificó en esa revisión. Resuelve dudas comerciales antes de escalar; una persona interviene si el cliente la pide o hace falta una acción que no puedes ejecutar. Mantén un tono cálido, sin presionar, una pregunta concreta por turno. Al cerrar una confirmación válida agradece con un emoji e indica que enviaremos la guía apenas se despache.
Si la persona pulsa CONFIRMAR justo después del resumen de compra y no hay contradicciones, agradece en un solo mensaje breve. No vuelvas a saludarla, no repitas productos, precio o dirección y no dividas la respuesta en varias burbujas. Indica que enviaremos la guía por este chat cuando se despache; no afirmes que ya se envió a logística.`;

export const ORDER_OPERATION_POLICY = `REGLAS OPERATIVAS DE PEDIDOS
Una respuesta exitosa de update_order debe incluir la verificación posterior de las variantes activas en Shopify. Sin esa verificación, no afirmes que el pedido quedó corregido ni avances a logística.
Corrige el pedido mediante sus líneas, variantes, cantidades y descuentos. Nunca uses notas al proveedor o al transportador para comunicar referencias, tallas, colores, regalos, correcciones ni explicaciones internas, salvo que el dueño pida explícitamente una nota concreta.
Si Shopify indica que el pedido ya fue enviado a logística, una corrección posterior también requiere sincronizar el pedido logístico. No afirmes que Dropi recibió el cambio ni que el pedido será despachado correctamente sin una operación verificada en Dropi. Conserva la conversación activa y deja una alerta operativa concreta cuando esa sincronización no esté disponible.`;

export function orderConversationModel(input: {
  workspaceId: string; configuredModel: string; hasOrder: boolean;
  messages: Array<{ role?: string; content: string; media?: unknown }>;
}): string {
  if (input.workspaceId !== DEUNA_WORKSPACE || !input.hasOrder) return input.configuredModel;
  const complexOrderLanguage = /(?:\boferta\b|promoci[oó]n|pag(?:a|ue)\s*(?:1|uno|una).{0,30}(?:lleva|ll[eé]vate|recibe).{0,10}(?:2|dos)|2\s*[x×]\s*1|segund[oa].{0,15}gratis|amb[oa]s|dos\s+pares?|dos\s+unidades?|agreg(?:a|ar).{0,20}(?:par|unidad)|cambi(?:a|ar).{0,30}(?:talla|color|referencia|modelo)|talla\s*\d+|blanc[oa]|negr[oa]|gris|referencia|variante)/i;
  const complex = input.messages.some(m =>
    // Offering a CORREGIR button is not a customer correction.
    (m.role !== 'assistant' && (m.media || /corregir|correct|no estoy segur|not sure|dos pedidos|two orders|imagen analizada|audio transcrito|adjunto pendiente/i.test(m.content) || complexOrderLanguage.test(m.content))) ||
    (/\[Mensaje del equipo humano\]/.test(m.content) && /Imagen analizada|Audio transcrito|pendiente de interpretar/i.test(m.content))
  );
  return complex ? 'claude-opus-5' : input.configuredModel;
}
