import { beforeEach, describe, it, expect, vi } from 'vitest';
const h=vi.hoisted(()=>({enabled:true,ctx:vi.fn(),csrf:vi.fn(),read:vi.fn(),write:vi.fn(),locale:'es' as 'es'|'en'}));
vi.mock('@/lib/ui/improvements-preview',()=>({get SHOW_RIVERZ_IMPROVEMENTS(){return h.enabled;}}));vi.mock('@/lib/inbox/server-context',()=>({inboxConversation:h.ctx}));vi.mock('@/lib/csrf',()=>({csrfGuard:h.csrf}));vi.mock('@/lib/i18n/server',()=>({getLocale:async()=>h.locale}));
vi.mock('@/lib/ai/rule-reviews',async original=>({...await original<object>(),readRuleReview:h.read,writeRuleReview:h.write}));
import {GET,POST} from './route';
const conv='11111111-1111-4111-8111-111111111111',turn='22222222-2222-4222-8222-222222222222',rule='33333333-3333-4333-8333-333333333333',actor='44444444-4444-4444-8444-444444444444',ws='55555555-5555-4555-8555-555555555555';
const route={params:Promise.resolve({id:conv})},db={},url=`https://riverz.co/api/conversations/${conv}/rule-reviews?turn_id=${turn}&rule_id=${rule}`;
const body={id:actor,expected_revision:0,decision:{application:'unverified',transfer:'not_assessed',note:'',confirmed:true}};
const request=(raw:unknown=body)=>new Request(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(raw)});
beforeEach(()=>{vi.clearAllMocks();h.enabled=true;h.locale='es';h.csrf.mockResolvedValue(null);h.ctx.mockResolvedValue({db,workspaceId:ws,userId:actor});h.read.mockResolvedValue({});h.write.mockResolvedValue({});});
describe('Private rule review routes retain current sessions and bounded input',()=>{
 it('returns private 404 outside comparison before auth and CSRF',async()=>{h.enabled=false;for(const response of [await GET(new Request(url),route),await POST(request(),route)]){expect(response.status).toBe(404);expect(response.headers.get('cache-control')).toBe('private, no-store');}expect(h.ctx).not.toHaveBeenCalled();expect(h.csrf).not.toHaveBeenCalled();});
 it('uses server actor and explicit turn/rule targets',async()=>{expect((await POST(request(),route)).status).toBe(200);expect(h.write).toHaveBeenCalledWith(db,ws,actor,conv,turn,rule,body);expect((await GET(new Request(url),route)).status).toBe(200);expect(h.read).toHaveBeenCalledWith(db,ws,actor,conv,turn,rule);});
 it('rejects failed CSRF and sessions before writes',async()=>{h.csrf.mockResolvedValueOnce(new Response('{}',{status:403}));expect((await POST(request(),route)).status).toBe(403);h.ctx.mockResolvedValue({response:new Response('{}',{status:401})});expect((await POST(request(),route)).status).toBe(401);expect(h.write).not.toHaveBeenCalled();});
 it.each(['&actor_id='+actor,'&turn_id='+turn,'&unknown=x'])('rejects duplicate or authority query %s',async suffix=>{expect((await GET(new Request(url+suffix),route)).status).toBe(400);expect(h.read).not.toHaveBeenCalled();});
 it.each(['es','en'] as const)('hides raw errors and localizes failures in %s',async locale=>{h.locale=locale;h.read.mockRejectedValue(new Error('SECRET'));const response=await GET(new Request(url),route),raw=await response.json();expect(response.status).toBe(503);expect(raw.error).not.toContain('SECRET');expect(raw.error).not.toContain('reglas.');});
 it('rejects non-JSON, oversized bytes and invalid UTF-8',async()=>{for(const init of [{headers:{'Content-Type':'text/plain'},body:'{}'},{headers:{'Content-Type':'application/json'},body:JSON.stringify({note:'界'.repeat(3000)})},{headers:{'Content-Type':'application/json'},body:new Uint8Array([0xff])}])expect((await POST(new Request(url,{method:'POST',...init}),route)).status).toBe(400);expect(h.write).not.toHaveBeenCalled();});
 it('withholds the view after the selected workspace or session changes',async()=>{h.ctx.mockResolvedValueOnce({db,workspaceId:ws,userId:actor}).mockResolvedValueOnce({db,workspaceId:actor,userId:actor});expect((await GET(new Request(url),route)).status).toBe(404);h.ctx.mockResolvedValueOnce({db,workspaceId:ws,userId:actor}).mockResolvedValueOnce({response:new Response('{}',{status:401})});expect((await GET(new Request(url),route)).status).toBe(401);});
});
