'use client';
import {useEffect,useRef,useState} from 'react';
import {Loader2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {useT} from '@/hooks/use-locale';
import {useFetchWithCsrf} from '@/lib/api/fetch-with-csrf';
import {SHOW_RIVERZ_IMPROVEMENTS} from '@/lib/ui/improvements-preview';
import {subscriptionSettings,subscriptionSettingsInput} from '@/lib/integrations/expansion/subscription-ui-contract';
import type {z} from 'zod';
export function SubscriptionSettings({workspaceId}:{workspaceId:string}){
 const t=useT(),fetch=useFetchWithCsrf(),version=useRef(0),inFlight=useRef(false);
 const [data,setData]=useState<z.infer<typeof subscriptionSettings>|null>(null),[shopId,setShopId]=useState(''),[storeId,setStoreId]=useState(''),[identifier,setIdentifier]=useState(''),[key,setKey]=useState(''),[enabled,setEnabled]=useState(false),[daily,setDaily]=useState(50),[mapping,setMapping]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{const lifecycle=version;lifecycle.current++;inFlight.current=false;setData(null);setShopId('');setStoreId('');setIdentifier('');setKey('');setEnabled(false);setDaily(50);setMapping(false);setBusy(false);setError('');setSaved(false);return()=>{lifecycle.current++;};},[workspaceId]);
 if(!SHOW_RIVERZ_IMPROVEMENTS)return null;
 function code(value:unknown){return typeof value==='string'&&['invalid','notAllowed','uncertain'].includes(value)?value:'unavailable';}
 function accept(value:z.infer<typeof subscriptionSettings>){setData(value);setShopId(value.configured?value.shopifyConnectionId:value.stores[0]?.id??'');setStoreId(value.configured?String(value.storeId):'');setIdentifier(value.configured?value.identifier:'');setEnabled(value.enabled);setDaily(value.configured?value.dailyChanges:50);setMapping(value.configured);setKey('');}
 async function load(){if(inFlight.current||!workspaceId)return;const generation=version.current;inFlight.current=true;setBusy(true);setError('');try{const response=await fetch('/api/integrations/subscriptions?view=settings',{cache:'no-store',headers:{'x-workspace-id':workspaceId}}),raw=await response.json();if(!response.ok)throw new Error(code(raw.code));const parsed=subscriptionSettings.safeParse(raw);if(!parsed.success)throw new Error('unavailable');if(version.current===generation)accept(parsed.data);}catch(cause){if(version.current===generation)setError(code(cause instanceof Error?cause.message:null));}finally{if(version.current===generation){inFlight.current=false;setBusy(false);}}}
 async function save(){if(!data||inFlight.current)return;const generation=version.current;inFlight.current=true;setBusy(true);setError('');setSaved(false);try{const selected=data.configured?{id:data.shopifyConnectionId,shopDomain:data.shopDomain}:data.stores.find(store=>store.id===shopId),draft={shopifyConnectionId:selected?.id,shopDomain:selected?.shopDomain,storeId:Number(storeId),identifier,...(key?{key}:{}),enabled,dailyChanges:daily,confirmedStoreMapping:mapping};if(!subscriptionSettingsInput.safeParse(draft).success||!data.configured&&!key)throw new Error('invalid');const response=await fetch('/api/integrations/subscriptions',{method:'POST',headers:{'Content-Type':'application/json','x-workspace-id':workspaceId},body:JSON.stringify({action:'settings',input:draft})}),raw=await response.json();if(!response.ok)throw new Error(code(raw.code));const parsed=subscriptionSettings.safeParse(raw);if(!parsed.success)throw new Error('unavailable');if(version.current===generation){accept(parsed.data);setSaved(true);}}catch(cause){if(version.current===generation)setError(code(cause instanceof Error?cause.message:null));}finally{if(version.current===generation){inFlight.current=false;setBusy(false);}}}
 return <li className="min-w-0 rounded-2xl border border-border bg-card p-4 shadow-sm sm:p-5"><details onToggle={event=>{if(event.currentTarget.open&&!data&&!inFlight.current)void load();}}><summary className="cursor-pointer text-sm font-semibold">{t('settings.subscriptionTitle')}</summary><div className="mt-3 min-w-0 space-y-3">
 {busy&&!data?<Loader2 className="size-4 animate-spin"/>:data?<fieldset disabled={busy} className="min-w-0 space-y-3">{!data.configured&&!data.stores.length?<p className="text-xs text-muted-foreground">{t('settings.subscriptionNoStores')}</p>:<>
 <label className="block space-y-1 text-xs">{t('settings.reviewShop')}{data.configured?<Input readOnly value={data.shopDomain}/>:<select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={shopId} onChange={event=>{setShopId(event.target.value);setMapping(false);setSaved(false);}}>{data.stores.map(store=><option key={store.id} value={store.id}>{store.shopDomain}</option>)}</select>}</label>
 <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={event=>{setEnabled(event.target.checked);setSaved(false);}}/>{t('settings.subscriptionEnabled')}</label>
 <label className="block space-y-1 text-xs">{t('settings.subscriptionDailyLimit')}<Input type="number" min={1} max={1000} value={daily} onChange={event=>{setDaily(Number(event.target.value));setSaved(false);}}/></label>
 <details open={!data.configured}><summary className="cursor-pointer text-xs font-medium">{t('settings.smsInstallation')}</summary><div className="mt-2 space-y-2">
 <label className="block space-y-1 text-xs">{t('settings.subscriptionStoreId')}<Input type="number" min={1} readOnly={data.configured} value={storeId} onChange={event=>{setStoreId(event.target.value);setMapping(false);setSaved(false);}}/></label>
 <label className="block space-y-1 text-xs">{t('settings.subscriptionIdentifier')}<Input readOnly={data.configured} maxLength={500} value={identifier} onChange={event=>{setIdentifier(event.target.value);setMapping(false);setSaved(false);}}/></label>
 <label className="block space-y-1 text-xs">{t('settings.subscriptionKey')}<Input type="password" autoComplete="new-password" value={key} placeholder={data.configured?t('settings.subscriptionKeepKey'):''} onChange={event=>{setKey(event.target.value);setMapping(false);setSaved(false);}}/></label>
 <label className="flex items-start gap-2 text-xs"><input type="checkbox" checked={mapping} onChange={event=>{setMapping(event.target.checked);setSaved(false);}}/>{t('settings.subscriptionStoreMapping')}</label><p className="text-xs text-muted-foreground">{t('settings.subscriptionInstallNote')}</p>
 </div></details><Button size="sm" disabled={busy||!mapping} onClick={save}>{busy?<Loader2 className="size-4 animate-spin"/>:t('settings.subscriptionSave')}</Button></>}
 </fieldset>:<Button variant="outline" size="sm" disabled={busy} onClick={load}>{t('settings.subscriptionLoad')}</Button>}
 {saved&&<p role="status" className="text-xs">{t('settings.subscriptionSaved')}</p>}{error&&<p role="alert" className="text-xs text-destructive">{t(`settings.subscriptionError_${code(error)}`)}</p>}
 </div></details></li>;
}
